jobs:
  - setup_sector_mappings: {}

# find diagram shift tree

  - find_diagram_shifts:
      qgraf_file: "myqgraf/PPh-qqb-gg-1r0v.qgraf.yaml"
      output_file: "myresults/PPh-qqb-gg-1r0v.match.yaml"
      info_file_form: "myresults/PPh-qqb-gg-1r0v.match.info.inc"

  - find_diagram_shifts:
      qgraf_file: "myqgraf/PPh-qqb-ghgh-1r0v.qgraf.yaml"
      output_file: "myresults/PPh-qqb-ghgh-1r0v.match.yaml"
      info_file_form: "myresults/PPh-qqb-ghgh-1r0v.match.info.inc"

  - find_diagram_shifts:
      qgraf_file: "myqgraf/PPh-gqb-qbg-1r0v.qgraf.yaml"
      output_file: "myresults/PPh-gqb-qbg-1r0v.match.yaml"
      info_file_form: "myresults/PPh-gqb-qbg-1r0v.match.info.inc"

# find diagram shift 1 loop

  - find_diagram_shifts:
      qgraf_file: "myqgraf/PPh-qqb-gg-1r1v.qgraf.yaml"
      output_file: "myresults/PPh-qqb-gg-1r1v.match.yaml"
      info_file_form: "myresults/PPh-qqb-gg-1r1v.match.info.inc"

  - find_diagram_shifts:
      qgraf_file: "myqgraf/PPh-qqb-ghgh-1r1v.qgraf.yaml"
      output_file: "myresults/PPh-qqb-ghgh-1r1v.match.yaml"
      info_file_form: "myresults/PPh-qqb-ghgh-1r1v.match.info.inc"

  - find_diagram_shifts:
      qgraf_file: "myqgraf/PPh-gqb-qbg-1r1v.qgraf.yaml"
      output_file: "myresults/PPh-gqb-qbg-1r1v.match.yaml"
      info_file_form: "myresults/PPh-gqb-qbg-1r1v.match.info.inc"