
# global symbols
global_symbols:
  coupling_constants: [g, e, gh]
  su_n_dimensions:
    adjoint: Na              # = Nc^2 - 1
    fundamental: Nc
  space_time_dimension: dim    # can be defined here instead of in the kinematics file

# eg. path to the Fermat executable
# paths: {}

paths:
#  fermat: /home/lvernazz/local/bin/fer64
  fermat: ../Ferl7/fer64
