{
tmpPPhsqqqbg0r0vcomp1X1 -> 
  INT["tree",0,0,0,0,{}] *
      (-t^(-1)*e^2*(-4+4*dim-dim^2)*Color[(-1+Nc)*(1+Nc)]*g^2*u),

tmpPPhsqqqbg0r0vcomp1X2 -> 
  INT["tree",0,0,0,0,{}] *
      (-e^2*(-8+6*dim-dim^2)*Color[(-1+Nc)*(1+Nc)]*g^2),

tmpPPhsqqqbg0r0vcomp2X1 -> 
  INT["tree",0,0,0,0,{}] *
      (-e^2*(-8+6*dim-dim^2)*Color[(-1+Nc)*(1+Nc)]*g^2),

tmpPPhsqqqbg0r0vcomp2X2 -> 
  INT["tree",0,0,0,0,{}] *
      (-t*e^2*(-4+4*dim-dim^2)*Color[(-1+Nc)*(1+Nc)]*g^2*u^(-1)),

tmpPPhsqgqbqb0r0vcomp1X1 -> 
  INT["tree",0,0,0,0,{}] *
      (e^2*(t*dim^2+4*t-4*dim*u-4*t*dim+dim^2*u+4*u)*(t+u)^(-2)*Color[(-1+Nc)*(1+Nc)]*g^2*u),

tmpPPhsqgqbqb0r0vcomp1X2 -> 
  INT["tree",0,0,0,0,{}] *
      (-(t*dim^2+8*t-6*dim*u-6*t*dim+dim^2*u+8*u)*e^2*(t+u)^(-1)*Color[(-1+Nc)*(1+Nc)]*g^2),

tmpPPhsqgqbqb0r0vcomp2X1 -> 
  INT["tree",0,0,0,0,{}] *
      (-(t*dim^2+8*t-6*dim*u-6*t*dim+dim^2*u+8*u)*e^2*(t+u)^(-1)*Color[(-1+Nc)*(1+Nc)]*g^2),

tmpPPhsqgqbqb0r0vcomp2X2 -> 
  INT["tree",0,0,0,0,{}] *
      (e^2*Color[(-1+Nc)*(1+Nc)]*(4+t*dim^2*u^(-1)-4*dim+4*t*u^(-1)-4*t*dim*u^(-1)+dim^2)*g^2)
}
