name = tmpPPhsqgqbqb0r1vcomp1X1
  boxx234 2 5  2 1  1 0 1 -1
   -(1/4*I)*e^2*(t+u)^(-3)*Color(Nc^(-1)*(-1+Nc)^2*(1+Nc)^2)*(24*t*dim*u+12*dim*u^2-16*t*u-8*t^2+dim^3*u^2+12*t^2*dim+2*t*dim^3*u+t^2*dim^3-8*u^2-6*dim^2*u^2-6*t^2*dim^2-12*t*dim^2*u)*g^4
    boxx234 2 5  2 1  1 -1 1 0
     -(1/4*I)*e^2*(t+u)^(-3)*Color(Nc^(-1)*(-1+Nc)^2*(1+Nc)^2)*(24*t*dim*u+12*dim*u^2-16*t*u-8*t^2+dim^3*u^2+12*t^2*dim+2*t*dim^3*u+t^2*dim^3-8*u^2-6*dim^2*u^2-6*t^2*dim^2-12*t*dim^2*u)*g^4
    boxx234 2 5  2 0  1 0 1 0
     (1/4*I)*(24*dim*u^3-24*t^2*dim^2*u-40*t*u^2-8*t^3+4*t^2*dim^3*u+60*t*dim*u^2-30*t*dim^2*u^2+t^3*dim^3+2*dim^3*u^3-32*t^2*u-6*t^3*dim^2+48*t^2*dim*u+12*t^3*dim+5*t*dim^3*u^2-16*u^3-12*dim^2*u^3)*e^2*(t+u)^(-3)*Color(Nc^(-1)*(-1+Nc)^2*(1+Nc)^2)*g^4
    boxx234 1 4  1 0  0 0 1 0
     (1/4*I)*(36*t*dim*u+24*dim*u^2-24*t*u-8*t^2+2*dim^3*u^2+12*t^2*dim+3*t*dim^3*u+t^2*dim^3-16*u^2-12*dim^2*u^2-6*t^2*dim^2-18*t*dim^2*u)*e^2*(t+u)^(-3)*Color(Nc^(-1)*(-1+Nc)^2*(1+Nc)^2)*g^4
    boxx234 1 1  1 0  1 0 0 0
     -(1/4*I)*t*e^2*(t+u)^(-3)*Color(Nc^(-1)*(-1+Nc)^2*(1+Nc)^2)*(6*t*dim^2-t*dim^3+8*t-12*dim*u-12*t*dim+6*dim^2*u+8*u-dim^3*u)*g^4
;
name = tmpPPhsqgqbqb0r1vcomp1X2
  boxx234 2 5  2 1  1 0 1 -1
   (1/4*I)*e^2*(t+u)^(-2)*Color(Nc^(-1)*(-1+Nc)^2*(1+Nc)^2)*(36*t^2*dim*u^(-1)-20*t*dim^2+2*t*dim^3-48*t+20*dim*u-32*t^2*u^(-1)+56*t*dim-8*dim^2*u+t^2*dim^3*u^(-1)-12*t^2*dim^2*u^(-1)-16*u+dim^3*u)*g^4
    boxx234 2 5  2 1  1 -1 1 0
     (1/4*I)*e^2*(t+u)^(-2)*Color(Nc^(-1)*(-1+Nc)^2*(1+Nc)^2)*(36*t^2*dim*u^(-1)-20*t*dim^2+2*t*dim^3-48*t+20*dim*u-32*t^2*u^(-1)+56*t*dim-8*dim^2*u+t^2*dim^3*u^(-1)-12*t^2*dim^2*u^(-1)-16*u+dim^3*u)*g^4
    boxx234 2 5  2 0  1 0 1 0
     -(1/4*I)*e^2*(t^3*dim^3*u^(-1)+116*t*dim*u-32*t^3*u^(-1)+40*dim*u^2-96*t*u-12*t^3*dim^2*u^(-1)-96*t^2+2*dim^3*u^2+112*t^2*dim+5*t*dim^3*u+36*t^3*dim*u^(-1)+4*t^2*dim^3-32*u^2-16*dim^2*u^2-40*t^2*dim^2-44*t*dim^2*u)*(t+u)^(-2)*Color(Nc^(-1)*(-1+Nc)^2*(1+Nc)^2)*g^4
    boxx234 1 4  1 0  0 0 1 0
     -(1/4*I)*e^2*(36*t^2*dim*u^(-1)-28*t*dim^2+3*t*dim^3-64*t+40*dim*u-32*t^2*u^(-1)+76*t*dim-16*dim^2*u+t^2*dim^3*u^(-1)-12*t^2*dim^2*u^(-1)-32*u+2*dim^3*u)*(t+u)^(-2)*Color(Nc^(-1)*(-1+Nc)^2*(1+Nc)^2)*g^4
    boxx234 1 1  1 0  1 0 0 0
     (1/4*I)*t*e^2*(t+u)^(-2)*Color(Nc^(-1)*(-1+Nc)^2*(1+Nc)^2)*(32+12*t*dim^2*u^(-1)-t*dim^3*u^(-1)-36*dim+32*t*u^(-1)-36*t*dim*u^(-1)-dim^3+12*dim^2)*g^4
;
name = tmpPPhsqgqbqb0r1vcomp2X1
  box 2 5  2 1  1 0 1 -1
   (1/4*I)*e^2*(t+u)^(-1)*(-16+4*t*dim^2*u^(-1)+20*dim+16*t*u^(-1)-16*t*dim*u^(-1)+dim^3-8*dim^2)*Color(Nc^(-1)*(-1+Nc)^2*(1+Nc)^2)*g^4
    box 2 5  2 1  1 -1 1 0
     -(1/4*I)*e^2*(t+u)^(-1)*(-16+4*t*dim^2*u^(-1)+20*dim+16*t*u^(-1)-16*t*dim*u^(-1)+dim^3-8*dim^2)*Color(Nc^(-1)*(-1+Nc)^2*(1+Nc)^2)*g^4
    box 2 5  2 0  1 0 1 0
     (1/4*I)*e^2*(t+u)^(-1)*(8*t*dim^2-t*dim^3+16*t-20*dim*u-20*t*dim+8*dim^2*u+16*u-dim^3*u)*Color(Nc^(-1)*(-1+Nc)^2*(1+Nc)^2)*g^4
    box 1 4  1 0  0 0 1 0
     -(1/4*I)*e^2*(t+u)^(-1)*Color(Nc^(-1)*(-1+Nc)^2*(1+Nc)^2)*(16+8*t*dim^2*u^(-1)-t*dim^3*u^(-1)-20*dim+16*t*u^(-1)-20*t*dim*u^(-1)-dim^3+8*dim^2)*g^4
    box 1 1  1 0  1 0 0 0
     (1/4*I)*e^2*(t+u)^(-1)*Color(Nc^(-1)*(-1+Nc)^2*(1+Nc)^2)*(16+8*t*dim^2*u^(-1)-t*dim^3*u^(-1)-20*dim+16*t*u^(-1)-20*t*dim*u^(-1)-dim^3+8*dim^2)*g^4
;
name = tmpPPhsqgqbqb0r1vcomp2X2
  box 2 5  2 1  1 0 1 -1
   -(1/4*I)*e^2*Color(Nc^(-1)*(-1+Nc)^2*(1+Nc)^2)*(-8+12*dim+dim^3-6*dim^2)*g^4*u^(-1)
    box 2 5  2 1  1 -1 1 0
     (1/4*I)*e^2*Color(Nc^(-1)*(-1+Nc)^2*(1+Nc)^2)*(-8+12*dim+dim^3-6*dim^2)*g^4*u^(-1)
    box 2 5  2 0  1 0 1 0
     -(1/4*I)*e^2*(8+6*t*dim^2*u^(-1)-t*dim^3*u^(-1)-12*dim+8*t*u^(-1)-12*t*dim*u^(-1)-dim^3+6*dim^2)*Color(Nc^(-1)*(-1+Nc)^2*(1+Nc)^2)*g^4
    box 1 4  1 0  0 0 1 0
     (1/4*I)*e^2*(8+6*t*dim^2*u^(-1)-t*dim^3*u^(-1)-12*dim+8*t*u^(-1)-12*t*dim*u^(-1)-dim^3+6*dim^2)*Color(Nc^(-1)*(-1+Nc)^2*(1+Nc)^2)*g^4*u^(-1)
    box 1 1  1 0  1 0 0 0
     -(1/4*I)*e^2*(8+6*t*dim^2*u^(-1)-t*dim^3*u^(-1)-12*dim+8*t*u^(-1)-12*t*dim*u^(-1)-dim^3+6*dim^2)*Color(Nc^(-1)*(-1+Nc)^2*(1+Nc)^2)*g^4*u^(-1)
;
name = tmpPPhsqgqbqb0r1vcomp3X1
  boxx132 3 7  3 1  1 1 1 -1
   -(1/4*I)*e^2*(t+u)^(-2)*Color(Nc^(-1)*(-1+Nc)^2*(1+Nc)^2)*(72*t*dim*u+36*dim*u^2-64*t*u-32*t^2+dim^3*u^2+36*t^2*dim+2*t*dim^3*u+t^2*dim^3-32*u^2-12*dim^2*u^2-12*t^2*dim^2-24*t*dim^2*u)*g^4
    boxx132 3 7  3 0  1 1 1 0
     (1/4*I)*t*e^2*(t+u)^(-2)*Color(Nc^(-1)*(-1+Nc)^2*(1+Nc)^2)*(72*t*dim*u+36*dim*u^2-64*t*u-32*t^2+dim^3*u^2+36*t^2*dim+2*t*dim^3*u+t^2*dim^3-32*u^2-12*dim^2*u^2-12*t^2*dim^2-24*t*dim^2*u)*g^4
    boxx132 2 6  2 0  0 1 1 0
     (1/4*I)*e^2*(52*t*dim*u+16*dim*u^2-48*t*u-32*t^2+36*t^2*dim+t*dim^3*u+t^2*dim^3-16*u^2-4*dim^2*u^2-12*t^2*dim^2-16*t*dim^2*u)*(t+u)^(-2)*Color(Nc^(-1)*(-1+Nc)^2*(1+Nc)^2)*g^4
    boxx132 2 5  2 1  1 0 1 -1
     -I*e^2*(t*dim^2+4*t-4*dim*u-4*t*dim+dim^2*u+4*u)*(t+u)^(-2)*Color(Nc^(-1)*(-1+Nc)^2*(1+Nc)^2)*g^4
    boxx132 2 5  2 0  1 0 1 0
     -(1/4*I)*(56*t*dim*u+20*dim*u^2-48*t*u-32*t^2+dim^3*u^2+36*t^2*dim+2*t*dim^3*u+t^2*dim^3-16*u^2-8*dim^2*u^2-12*t^2*dim^2-20*t*dim^2*u)*e^2*(t+u)^(-2)*Color(Nc^(-1)*(-1+Nc)^2*(1+Nc)^2)*g^4
    boxx132 2 3  2 1  1 1 0 -1
     I*e^2*(t*dim^2+4*t-4*dim*u-4*t*dim+dim^2*u+4*u)*(t+u)^(-2)*Color(Nc^(-1)*(-1+Nc)^2*(1+Nc)^2)*g^4
    boxx132 2 3  2 0  1 1 0 0
     -(1/4*I)*t*e^2*(t+u)^(-2)*Color(Nc^(-1)*(-1+Nc)^2*(1+Nc)^2)*(12*t*dim^2-t*dim^3+32*t-36*dim*u-36*t*dim+12*dim^2*u+32*u-dim^3*u)*g^4
    boxx132 1 4  1 0  0 0 1 0
     I*e^2*(t*dim^2+4*t-4*dim*u-4*t*dim+dim^2*u+4*u)*(t+u)^(-2)*Color(Nc^(-1)*(-1+Nc)^2*(1+Nc)^2)*g^4
    boxx132 1 2  1 0  0 1 0 0
     -I*e^2*(t*dim^2+4*t-4*dim*u-4*t*dim+dim^2*u+4*u)*(t+u)^(-2)*Color(Nc^(-1)*(-1+Nc)^2*(1+Nc)^2)*g^4
;
name = tmpPPhsqgqbqb0r1vcomp3X2
  boxx132 3 7  3 2  1 1 1 -2
   (1/2*I)*e^2*(t+u)^(-1)*Color(Nc^(-1)*(-1+Nc)^2*(1+Nc)^2)*(4+t*dim^2*u^(-1)-4*dim+4*t*u^(-1)-4*t*dim*u^(-1)+dim^2)*g^4
    boxx132 3 7  3 1  1 1 1 -1
     (1/4*I)*(84*t^2*dim*u^(-1)-34*t*dim^2+2*t*dim^3-224*t+72*dim*u-120*t^2*u^(-1)+156*t*dim-16*dim^2*u+t^2*dim^3*u^(-1)-18*t^2*dim^2*u^(-1)-104*u+dim^3*u)*e^2*(t+u)^(-1)*Color(Nc^(-1)*(-1+Nc)^2*(1+Nc)^2)*g^4
    boxx132 3 7  3 0  1 1 1 0
     -(1/4*I)*t*e^2*(t+u)^(-1)*Color(Nc^(-1)*(-1+Nc)^2*(1+Nc)^2)*g^4*(76*t^2*dim*u^(-1)-32*t*dim^2+2*t*dim^3-216*t+72*dim*u-112*t^2*u^(-1)+148*t*dim-16*dim^2*u+t^2*dim^3*u^(-1)-16*t^2*dim^2*u^(-1)-104*u+dim^3*u)
    boxx132 2 6  2 1  0 1 1 -1
     -(1/2*I)*e^2*(t+u)^(-1)*Color(Nc^(-1)*(-1+Nc)^2*(1+Nc)^2)*(8+2*t*dim^2*u^(-1)-6*dim+12*t*u^(-1)-10*t*dim*u^(-1)+dim^2)*g^4
    boxx132 2 6  2 1  -1 1 1 0
     -(1/2*I)*t*e^2*(-8+6*dim-dim^2)*(t+u)^(-1)*Color(Nc^(-1)*(-1+Nc)^2*(1+Nc)^2)*g^4*u^(-1)
    boxx132 2 6  2 0  0 1 1 0
     -(1/4*I)*e^2*(t+u)^(-1)*Color(Nc^(-1)*(-1+Nc)^2*(1+Nc)^2)*(88*t^2*dim*u^(-1)-22*t*dim^2+t*dim^3-168*t+24*dim*u-128*t^2*u^(-1)+116*t*dim-4*dim^2*u+t^2*dim^3*u^(-1)-18*t^2*dim^2*u^(-1)-32*u)*g^4
    boxx132 2 5  2 1  1 0 1 -1
     (1/2*I)*e^2*(t+u)^(-1)*Color(Nc^(-1)*(-1+Nc)^2*(1+Nc)^2)*g^4*(8+t*dim^2*u^(-1)-6*dim+8*t*u^(-1)-6*t*dim*u^(-1)+dim^2)
    boxx132 2 5  2 1  1 -1 1 0
     -I*e^2*(t+u)^(-1)*Color(Nc^(-1)*(-1+Nc)^2*(1+Nc)^2)*(-2+dim-2*t*u^(-1)+t*dim*u^(-1))*g^4
    boxx132 2 5  2 0  1 0 1 0
     (1/4*I)*e^2*(t+u)^(-1)*Color(Nc^(-1)*(-1+Nc)^2*(1+Nc)^2)*(80*t^2*dim*u^(-1)-24*t*dim^2+2*t*dim^3-112*t+16*dim*u-120*t^2*u^(-1)+96*t*dim-8*dim^2*u+t^2*dim^3*u^(-1)-16*t^2*dim^2*u^(-1)+8*u+dim^3*u)*g^4
    boxx132 2 3  2 1  1 1 0 -1
     -(1/2*I)*e^2*(t+u)^(-1)*Color(Nc^(-1)*(-1+Nc)^2*(1+Nc)^2)*(8+t*dim^2*u^(-1)-8*dim+4*t*u^(-1)-4*t*dim*u^(-1)+2*dim^2)*g^4
    boxx132 2 3  2 0  1 1 0 0
     (1/4*I)*t*e^2*(t+u)^(-1)*(104+16*t*dim^2*u^(-1)-t*dim^3*u^(-1)-72*dim+112*t*u^(-1)-76*t*dim*u^(-1)-dim^3+16*dim^2)*Color(Nc^(-1)*(-1+Nc)^2*(1+Nc)^2)*g^4
    boxx132 1 4  1 0  0 0 1 0
     -(1/2*I)*e^2*(8+t*dim^2*u^(-1)-6*dim+12*t*u^(-1)-8*t*dim*u^(-1)+dim^2)*(t+u)^(-1)*Color(Nc^(-1)*(-1+Nc)^2*(1+Nc)^2)*g^4
    boxx132 1 2  1 0  0 1 0 0
     (1/2*I)*e^2*(16+t*dim^2*u^(-1)-12*dim+8*t*u^(-1)-6*t*dim*u^(-1)+2*dim^2)*(t+u)^(-1)*Color(Nc^(-1)*(-1+Nc)^2*(1+Nc)^2)*g^4
    boxx132 1 1  1 0  1 0 0 0
     I*(-4+2*dim-2*t*u^(-1)+t*dim*u^(-1))*e^2*(t+u)^(-1)*Color(Nc^(-1)*(-1+Nc)^2*(1+Nc)^2)*g^4
;
name = tmpPPhsqgqbqb0r1vcomp4X1
  boxx12x34 3 7  3 2  1 1 1 -2
   (1/2*I)*e^2*(t+u)^(-1)*Color(Nc^(-1)*(-1+Nc)^2*(1+Nc)^2)*(-4+4*dim-dim^2)*g^4
    boxx12x34 3 7  3 1  1 1 1 -1
     -(1/4*I)*(2*t*dim^2+16*t+56*dim*u-12*t*dim-12*dim^2*u-88*u+dim^3*u)*e^2*(t+u)^(-1)*Color(Nc^(-1)*(-1+Nc)^2*(1+Nc)^2)*g^4
    boxx12x34 3 7  3 0  1 1 1 0
     -(1/4*I)*e^2*(t+u)^(-1)*Color(Nc^(-1)*(-1+Nc)^2*(1+Nc)^2)*g^4*(60*t*dim*u+64*dim*u^2-88*t*u+8*t^2+dim^3*u^2-4*t^2*dim+t*dim^3*u-96*u^2-14*dim^2*u^2-14*t*dim^2*u)
    boxx12x34 2 6  2 1  0 1 1 -1
     (1/2*I)*t*e^2*(t+u)^(-1)*Color(Nc^(-1)*(-1+Nc)^2*(1+Nc)^2)*(-4+4*dim-dim^2)*g^4*u^(-1)
    boxx12x34 2 6  2 1  -1 1 1 0
     (1/2*I)*e^2*(t+u)^(-1)*Color(Nc^(-1)*(-1+Nc)^2*(1+Nc)^2)*(4+t*dim^2*u^(-1)-4*dim+4*t*u^(-1)-4*t*dim*u^(-1)+dim^2)*g^4
    boxx12x34 2 6  2 0  0 1 1 0
     -(1/4*I)*e^2*(t+u)^(-1)*Color(Nc^(-1)*(-1+Nc)^2*(1+Nc)^2)*(4*t^2*dim*u^(-1)+16*t*dim^2-t*dim^3+96*t-72*dim*u-8*t^2*u^(-1)-68*t*dim+16*dim^2*u+104*u-dim^3*u)*g^4
    boxx12x34 2 5  2 1  1 0 1 -1
     -(1/2*I)*e^2*(-8+6*dim-dim^2)*(t+u)^(-1)*Color(Nc^(-1)*(-1+Nc)^2*(1+Nc)^2)*g^4
    boxx12x34 2 5  2 1  1 -1 1 0
     I*e^2*(t+u)^(-1)*(-2+dim)*Color(Nc^(-1)*(-1+Nc)^2*(1+Nc)^2)*g^4
    boxx12x34 2 5  2 0  1 0 1 0
     (1/4*I)*(8*t*dim^2+128*t+4*dim*u-64*t*dim-6*dim^2*u+24*u+dim^3*u)*e^2*(t+u)^(-1)*Color(Nc^(-1)*(-1+Nc)^2*(1+Nc)^2)*g^4
    boxx12x34 2 3  2 1  1 1 0 -1
     (1/2*I)*e^2*(t+u)^(-1)*Color(Nc^(-1)*(-1+Nc)^2*(1+Nc)^2)*g^4*(t*dim^2*u^(-1)-2*dim+4*t*u^(-1)-4*t*dim*u^(-1)+dim^2)
    boxx12x34 2 3  2 1  1 1 -1 0
     -I*e^2*(t+u)^(-1)*Color(Nc^(-1)*(-1+Nc)^2*(1+Nc)^2)*(-2+dim-2*t*u^(-1)+t*dim*u^(-1))*g^4
    boxx12x34 2 3  2 0  1 1 0 0
     (1/4*I)*(4*t^2*dim*u^(-1)-10*t*dim^2+t*dim^3-80*t+44*dim*u-8*t^2*u^(-1)+48*t*dim-10*dim^2*u-72*u+dim^3*u)*e^2*(t+u)^(-1)*Color(Nc^(-1)*(-1+Nc)^2*(1+Nc)^2)*g^4
    boxx12x34 1 4  1 0  0 0 1 0
     (1/2*I)*e^2*(t+u)^(-1)*Color(Nc^(-1)*(-1+Nc)^2*(1+Nc)^2)*(2*dim+4*t*u^(-1)-2*t*dim*u^(-1)-dim^2)*g^4
    boxx12x34 1 2  1 0  0 1 0 0
     -(1/2*I)*e^2*(t+u)^(-1)*Color(Nc^(-1)*(-1+Nc)^2*(1+Nc)^2)*g^4*(8+t*dim^2*u^(-1)-6*dim+8*t*u^(-1)-6*t*dim*u^(-1)+dim^2)
    boxx12x34 1 1  1 0  1 0 0 0
     I*t*e^2*(t+u)^(-1)*(-2+dim)*Color(Nc^(-1)*(-1+Nc)^2*(1+Nc)^2)*g^4*u^(-1)
;
name = tmpPPhsqgqbqb0r1vcomp4X2
  boxx12x34 3 7  3 1  1 1 1 -1
   (1/4*I)*(-32+36*dim+dim^3-12*dim^2)*e^2*Color(Nc^(-1)*(-1+Nc)^2*(1+Nc)^2)*g^4
    boxx12x34 3 7  3 0  1 1 1 0
     -(1/4*I)*e^2*Color(Nc^(-1)*(-1+Nc)^2*(1+Nc)^2)*(12*t*dim^2-t*dim^3+32*t-36*dim*u-36*t*dim+12*dim^2*u+32*u-dim^3*u)*g^4
    boxx12x34 2 6  2 1  0 1 1 -1
     -I*e^2*Color(Nc^(-1)*(-1+Nc)^2*(1+Nc)^2)*(-4+4*dim-dim^2)*g^4*u^(-1)
    boxx12x34 2 6  2 1  -1 1 1 0
     I*e^2*Color(Nc^(-1)*(-1+Nc)^2*(1+Nc)^2)*(-4+4*dim-dim^2)*g^4*u^(-1)
    boxx12x34 2 6  2 0  0 1 1 0
     (1/4*I)*(48+12*t*dim^2*u^(-1)-t*dim^3*u^(-1)-52*dim+32*t*u^(-1)-36*t*dim*u^(-1)-dim^3+16*dim^2)*e^2*Color(Nc^(-1)*(-1+Nc)^2*(1+Nc)^2)*g^4
    boxx12x34 2 5  2 1  1 0 1 -1
     I*e^2*Color(Nc^(-1)*(-1+Nc)^2*(1+Nc)^2)*(-4+4*dim-dim^2)*g^4*u^(-1)
    boxx12x34 2 5  2 0  1 0 1 0
     -(1/4*I)*(4*t*dim^2*u^(-1)+4*dim+16*t*u^(-1)-16*t*dim*u^(-1)+dim^3-4*dim^2)*e^2*Color(Nc^(-1)*(-1+Nc)^2*(1+Nc)^2)*g^4
    boxx12x34 2 3  2 0  1 1 0 0
     (1/4*I)*e^2*Color(Nc^(-1)*(-1+Nc)^2*(1+Nc)^2)*(16+8*t*dim^2*u^(-1)-t*dim^3*u^(-1)-20*dim+16*t*u^(-1)-20*t*dim*u^(-1)-dim^3+8*dim^2)*g^4
    boxx12x34 1 4  1 0  0 0 1 0
     -I*e^2*Color(Nc^(-1)*(-1+Nc)^2*(1+Nc)^2)*(-4+4*dim-dim^2)*g^4*u^(-1)
;
name = tmpPPhsqgqbqb0r1vcomp5X1
  box 3 7  3 2  1 1 1 -2
   -(1/2*I)*Color(Nc^(-1)*(-1+Nc)*(1+Nc))*e^2*(t+u)^(-1)*(-4+4*dim-dim^2)*g^4
    box 3 7  3 1  1 1 1 -1
     (1/4*I)*Color(Nc^(-1)*(-1+Nc)*(1+Nc))*(2*t*dim^2+16*t+56*dim*u-12*t*dim-12*dim^2*u-88*u+dim^3*u)*e^2*(t+u)^(-1)*g^4
    box 3 7  3 0  1 1 1 0
     (1/4*I)*Color(Nc^(-1)*(-1+Nc)*(1+Nc))*e^2*(t+u)^(-1)*g^4*(60*t*dim*u+64*dim*u^2-88*t*u+8*t^2+dim^3*u^2-4*t^2*dim+t*dim^3*u-96*u^2-14*dim^2*u^2-14*t*dim^2*u)
    box 2 6  2 1  0 1 1 -1
     -(1/2*I)*Color(Nc^(-1)*(-1+Nc)*(1+Nc))*e^2*(t+u)^(-1)*g^4*(t*dim^2*u^(-1)-2*dim+4*t*u^(-1)-4*t*dim*u^(-1)+dim^2)
    box 2 6  2 1  -1 1 1 0
     I*Color(Nc^(-1)*(-1+Nc)*(1+Nc))*e^2*(t+u)^(-1)*(-2+dim-2*t*u^(-1)+t*dim*u^(-1))*g^4
    box 2 6  2 0  0 1 1 0
     -(1/4*I)*Color(Nc^(-1)*(-1+Nc)*(1+Nc))*(4*t^2*dim*u^(-1)-10*t*dim^2+t*dim^3-80*t+44*dim*u-8*t^2*u^(-1)+48*t*dim-10*dim^2*u-72*u+dim^3*u)*e^2*(t+u)^(-1)*g^4
    box 2 5  2 1  1 0 1 -1
     (1/2*I)*Color(Nc^(-1)*(-1+Nc)*(1+Nc))*e^2*(-8+6*dim-dim^2)*(t+u)^(-1)*g^4
    box 2 5  2 1  1 -1 1 0
     -I*Color(Nc^(-1)*(-1+Nc)*(1+Nc))*e^2*(t+u)^(-1)*(-2+dim)*g^4
    box 2 5  2 0  1 0 1 0
     -(1/4*I)*(8*t*dim^2+128*t+4*dim*u-64*t*dim-6*dim^2*u+24*u+dim^3*u)*Color(Nc^(-1)*(-1+Nc)*(1+Nc))*e^2*(t+u)^(-1)*g^4
    box 2 3  2 1  1 1 0 -1
     -(1/2*I)*Color(Nc^(-1)*(-1+Nc)*(1+Nc))*t*e^2*(t+u)^(-1)*(-4+4*dim-dim^2)*g^4*u^(-1)
    box 2 3  2 1  1 1 -1 0
     -(1/2*I)*Color(Nc^(-1)*(-1+Nc)*(1+Nc))*e^2*(t+u)^(-1)*(4+t*dim^2*u^(-1)-4*dim+4*t*u^(-1)-4*t*dim*u^(-1)+dim^2)*g^4
    box 2 3  2 0  1 1 0 0
     (1/4*I)*Color(Nc^(-1)*(-1+Nc)*(1+Nc))*e^2*(t+u)^(-1)*(4*t^2*dim*u^(-1)+16*t*dim^2-t*dim^3+96*t-72*dim*u-8*t^2*u^(-1)-68*t*dim+16*dim^2*u+104*u-dim^3*u)*g^4
    box 1 4  1 0  0 0 1 0
     -I*Color(Nc^(-1)*(-1+Nc)*(1+Nc))*t*e^2*(t+u)^(-1)*(-2+dim)*g^4*u^(-1)
    box 1 2  1 0  0 1 0 0
     (1/2*I)*Color(Nc^(-1)*(-1+Nc)*(1+Nc))*e^2*(t+u)^(-1)*g^4*(8+t*dim^2*u^(-1)-6*dim+8*t*u^(-1)-6*t*dim*u^(-1)+dim^2)
    box 1 1  1 0  1 0 0 0
     -(1/2*I)*Color(Nc^(-1)*(-1+Nc)*(1+Nc))*e^2*(t+u)^(-1)*(2*dim+4*t*u^(-1)-2*t*dim*u^(-1)-dim^2)*g^4
;
name = tmpPPhsqgqbqb0r1vcomp5X2
  box 3 7  3 1  1 1 1 -1
   -(1/4*I)*(-32+36*dim+dim^3-12*dim^2)*Color(Nc^(-1)*(-1+Nc)*(1+Nc))*e^2*g^4
    box 3 7  3 0  1 1 1 0
     (1/4*I)*Color(Nc^(-1)*(-1+Nc)*(1+Nc))*e^2*(12*t*dim^2-t*dim^3+32*t-36*dim*u-36*t*dim+12*dim^2*u+32*u-dim^3*u)*g^4
    box 2 6  2 0  0 1 1 0
     -(1/4*I)*Color(Nc^(-1)*(-1+Nc)*(1+Nc))*e^2*(16+8*t*dim^2*u^(-1)-t*dim^3*u^(-1)-20*dim+16*t*u^(-1)-20*t*dim*u^(-1)-dim^3+8*dim^2)*g^4
    box 2 5  2 1  1 0 1 -1
     -I*Color(Nc^(-1)*(-1+Nc)*(1+Nc))*e^2*(-4+4*dim-dim^2)*g^4*u^(-1)
    box 2 5  2 0  1 0 1 0
     (1/4*I)*Color(Nc^(-1)*(-1+Nc)*(1+Nc))*(4*t*dim^2*u^(-1)+4*dim+16*t*u^(-1)-16*t*dim*u^(-1)+dim^3-4*dim^2)*e^2*g^4
    box 2 3  2 1  1 1 0 -1
     I*Color(Nc^(-1)*(-1+Nc)*(1+Nc))*e^2*(-4+4*dim-dim^2)*g^4*u^(-1)
    box 2 3  2 1  1 1 -1 0
     -I*Color(Nc^(-1)*(-1+Nc)*(1+Nc))*e^2*(-4+4*dim-dim^2)*g^4*u^(-1)
    box 2 3  2 0  1 1 0 0
     -(1/4*I)*(48+12*t*dim^2*u^(-1)-t*dim^3*u^(-1)-52*dim+32*t*u^(-1)-36*t*dim*u^(-1)-dim^3+16*dim^2)*Color(Nc^(-1)*(-1+Nc)*(1+Nc))*e^2*g^4
    box 1 1  1 0  1 0 0 0
     I*Color(Nc^(-1)*(-1+Nc)*(1+Nc))*e^2*(-4+4*dim-dim^2)*g^4*u^(-1)
;
name = tmpPPhsqgqbqb0r1vcomp6X1
  box 3 7  3 2  1 1 1 -2
   -(1/2*I)*Color(Nc*(-1+Nc)*(1+Nc))*e^2*(t+u)^(-1)*(-4+4*dim-dim^2)*g^4
    box 3 7  3 1  1 1 1 -1
     (1/4*I)*Color(Nc*(-1+Nc)*(1+Nc))*e^2*(3*t*dim^2+12*t-38*dim*u-12*t*dim+6*dim^2*u+68*u)*(t+u)^(-1)*g^4
    box 3 7  3 0  1 1 1 0
     -(1/4*I)*(14*t*dim*u+6*dim*u^2-40*t*u-12*t^2+8*t^2*dim-28*u^2-t^2*dim^2-t*dim^2*u)*Color(Nc*(-1+Nc)*(1+Nc))*e^2*(t+u)^(-1)*g^4
    box 2 6  2 1  0 1 1 -1
     -(1/2*I)*Color(Nc*(-1+Nc)*(1+Nc))*e^2*(t+u)^(-1)*g^4*(t*dim^2*u^(-1)-2*dim+4*t*u^(-1)-4*t*dim*u^(-1)+dim^2)
    box 2 6  2 1  -1 1 1 0
     I*Color(Nc*(-1+Nc)*(1+Nc))*e^2*(t+u)^(-1)*(-2+dim-2*t*u^(-1)+t*dim*u^(-1))*g^4
    box 2 6  2 0  0 1 1 0
     (1/4*I)*Color(Nc*(-1+Nc)*(1+Nc))*e^2*(t+u)^(-1)*(8*t^2*dim*u^(-1)-t*dim^2-32*t+2*dim*u-12*t^2*u^(-1)+10*t*dim-t^2*dim^2*u^(-1)-20*u)*g^4
    box 2 5  2 1  1 0 1 -1
     (1/2*I)*Color(Nc*(-1+Nc)*(1+Nc))*e^2*(-8+6*dim-dim^2)*(t+u)^(-1)*g^4
    box 2 5  2 1  1 -1 1 0
     -I*Color(Nc*(-1+Nc)*(1+Nc))*e^2*(t+u)^(-1)*(-2+dim)*g^4
    box 2 5  2 0  1 0 1 0
     (1/4*I)*Color(Nc*(-1+Nc)*(1+Nc))*e^2*(t+u)^(-1)*g^4*(5*t*dim^2+108*t-22*dim*u-48*t*dim+2*dim^2*u+52*u)
    box 2 3  2 1  1 1 0 -1
     -(1/2*I)*Color(Nc*(-1+Nc)*(1+Nc))*t*e^2*(t+u)^(-1)*(-4+4*dim-dim^2)*g^4*u^(-1)
    box 2 3  2 1  1 1 -1 0
     -(1/2*I)*Color(Nc*(-1+Nc)*(1+Nc))*e^2*(t+u)^(-1)*(4+t*dim^2*u^(-1)-4*dim+4*t*u^(-1)-4*t*dim*u^(-1)+dim^2)*g^4
    box 2 3  2 0  1 1 0 0
     -(1/4*I)*Color(Nc*(-1+Nc)*(1+Nc))*e^2*(8*t^2*dim*u^(-1)-t*dim^2+24*t-10*dim*u-12*t^2*u^(-1)-2*t*dim-t^2*dim^2*u^(-1)+36*u)*(t+u)^(-1)*g^4
    box 1 4  1 0  0 0 1 0
     -I*Color(Nc*(-1+Nc)*(1+Nc))*t*e^2*(t+u)^(-1)*(-2+dim)*g^4*u^(-1)
    box 1 2  1 0  0 1 0 0
     (1/2*I)*Color(Nc*(-1+Nc)*(1+Nc))*e^2*(t+u)^(-1)*g^4*(8+t*dim^2*u^(-1)-6*dim+8*t*u^(-1)-6*t*dim*u^(-1)+dim^2)
    box 1 1  1 0  1 0 0 0
     -(1/2*I)*Color(Nc*(-1+Nc)*(1+Nc))*e^2*(t+u)^(-1)*(2*dim+4*t*u^(-1)-2*t*dim*u^(-1)-dim^2)*g^4
;
name = tmpPPhsqgqbqb0r1vcomp6X2
  box 3 7  3 1  1 1 1 -1
   (1/2*I)*Color(Nc*(-1+Nc)*(1+Nc))*e^2*(-4+4*dim-dim^2)*g^4
    box 3 7  3 0  1 1 1 0
     (1/2*I)*Color(Nc*(-1+Nc)*(1+Nc))*e^2*(t*dim^2+4*t-4*dim*u-4*t*dim+dim^2*u+4*u)*g^4
    box 2 6  2 0  0 1 1 0
     -(1/2*I)*Color(Nc*(-1+Nc)*(1+Nc))*e^2*(4+t*dim^2*u^(-1)-4*dim+4*t*u^(-1)-4*t*dim*u^(-1)+dim^2)*g^4
    box 2 5  2 1  1 0 1 -1
     -I*Color(Nc*(-1+Nc)*(1+Nc))*e^2*(-4+4*dim-dim^2)*g^4*u^(-1)
    box 2 5  2 0  1 0 1 0
     I*Color(Nc*(-1+Nc)*(1+Nc))*t*e^2*(-4+4*dim-dim^2)*g^4*u^(-1)
    box 2 3  2 1  1 1 0 -1
     I*Color(Nc*(-1+Nc)*(1+Nc))*e^2*(-4+4*dim-dim^2)*g^4*u^(-1)
    box 2 3  2 1  1 1 -1 0
     -I*Color(Nc*(-1+Nc)*(1+Nc))*e^2*(-4+4*dim-dim^2)*g^4*u^(-1)
    box 2 3  2 0  1 1 0 0
     -(1/2*I)*Color(Nc*(-1+Nc)*(1+Nc))*e^2*(8+t*dim^2*u^(-1)-8*dim+4*t*u^(-1)-4*t*dim*u^(-1)+2*dim^2)*g^4
    box 1 1  1 0  1 0 0 0
     I*Color(Nc*(-1+Nc)*(1+Nc))*e^2*(-4+4*dim-dim^2)*g^4*u^(-1)
;
name = tmpPPhsqgqbqb0r1vcomp7X1
  boxx34 3 7  3 3  1 1 1 -3
   (8*I)*t^(-1)*e^2*Tag({25,31,32})*(t+u)^(-1)*Color((-1+Nc)*(1+Nc))*g^4
    boxx34 3 7  3 2  1 1 1 -2
     (4*I)*(3+2*t^(-1)*u)*e^2*Tag({25,31,32})*(t+u)^(-1)*Color((-1+Nc)*(1+Nc))*g^4
    boxx34 3 7  3 1  1 1 1 -1
     (1/2*I)*e^2*Tag({25,31,32})*(t+u)^(-1)*(4*t-2*dim*u+t*dim+12*u)*Color((-1+Nc)*(1+Nc))*g^4
    boxx34 3 7  3 0  1 1 1 0
     -(1/2*I)*e^2*Tag({25,31,32})*(t+u)^(-1)*Color((-1+Nc)*(1+Nc))*(t*dim*u+2*dim*u^2+4*t^2-t^2*dim-4*u^2)*g^4
    boxx34 2 6  2 2  0 1 1 -2
     -(8*I)*t^(-1)*e^2*Tag({25,31,32})*(t+u)^(-1)*Color((-1+Nc)*(1+Nc))*g^4
    boxx34 2 6  2 1  0 1 1 -1
     -I*e^2*Tag({25,31,32})*(t+u)^(-1)*Color((-1+Nc)*(1+Nc))*g^4*(2+dim+4*t^(-1)*u)
    boxx34 2 6  2 1  -1 1 1 0
     -I*e^2*Tag({25,31,32})*(t+u)^(-1)*Color((-1+Nc)*(1+Nc))*(-2+t^(-1)*dim*u+dim-2*t^(-1)*u)*g^4
    boxx34 2 6  2 0  0 1 1 0
     (1/2*I)*e^2*Tag({25,31,32})*(t+u)^(-1)*(3*dim*u+2*t^(-1)*dim*u^2+t*dim-4*t^(-1)*u^2-4*u)*Color((-1+Nc)*(1+Nc))*g^4
    boxx34 2 5  2 2  1 0 1 -2
     -(8*I)*t^(-1)*e^2*Tag({25,31,32})*(t+u)^(-1)*Color((-1+Nc)*(1+Nc))*g^4
    boxx34 2 5  2 1  1 0 1 -1
     -I*(2+2*t^(-1)*dim*u+dim-4*t^(-1)*u)*e^2*Tag({25,31,32})*(t+u)^(-1)*Color((-1+Nc)*(1+Nc))*g^4
    boxx34 2 5  2 1  1 -1 1 0
     -I*e^2*Tag({25,31,32})*(t+u)^(-1)*(-2+dim)*Color((-1+Nc)*(1+Nc))*g^4
    boxx34 2 5  2 0  1 0 1 0
     (1/2*I)*e^2*Tag({25,31,32})*(2*dim*u-t*dim-8*u)*(t+u)^(-1)*Color((-1+Nc)*(1+Nc))*g^4
    boxx34 2 3  2 2  1 1 0 -2
     -(8*I)*t^(-1)*e^2*Tag({25,31,32})*(t+u)^(-1)*Color((-1+Nc)*(1+Nc))*g^4
    boxx34 2 3  2 1  1 1 0 -1
     -I*e^2*Tag({25,31,32})*(t+u)^(-1)*Color((-1+Nc)*(1+Nc))*g^4*(2+dim+4*t^(-1)*u)
    boxx34 2 3  2 1  1 1 -1 0
     -I*e^2*Tag({25,31,32})*(t+u)^(-1)*Color((-1+Nc)*(1+Nc))*(-2+t^(-1)*dim*u+dim-2*t^(-1)*u)*g^4
    boxx34 2 3  2 0  1 1 0 0
     (1/2*I)*e^2*Tag({25,31,32})*(t+u)^(-1)*(3*dim*u+2*t^(-1)*dim*u^2+t*dim-4*t^(-1)*u^2-4*u)*Color((-1+Nc)*(1+Nc))*g^4
    boxx34 1 4  1 1  0 0 1 -1
     (8*I)*t^(-1)*e^2*Tag({25,31,32})*(t+u)^(-1)*Color((-1+Nc)*(1+Nc))*g^4
    boxx34 1 4  1 0  0 0 1 0
     I*e^2*Tag({25,31,32})*(-4+t^(-1)*dim*u+2*dim-2*t^(-1)*u)*(t+u)^(-1)*Color((-1+Nc)*(1+Nc))*g^4
    boxx34 1 2  1 1  0 1 0 -1
     (8*I)*t^(-1)*e^2*Tag({25,31,32})*(t+u)^(-1)*Color((-1+Nc)*(1+Nc))*g^4
    boxx34 1 2  1 0  0 1 0 0
     (2*I)*e^2*Tag({25,31,32})*(t+u)^(-1)*Color((-1+Nc)*(1+Nc))*(-2+t^(-1)*dim*u+dim-2*t^(-1)*u)*g^4
    boxx34 1 1  1 1  1 0 0 -1
     (8*I)*t^(-1)*e^2*Tag({25,31,32})*(t+u)^(-1)*Color((-1+Nc)*(1+Nc))*g^4
    boxx34 1 1  1 0  1 0 0 0
     I*e^2*Tag({25,31,32})*(-4+t^(-1)*dim*u+2*dim-2*t^(-1)*u)*(t+u)^(-1)*Color((-1+Nc)*(1+Nc))*g^4
    boxx34 0 0  0 0  0 0 0 0
     -(8*I)*t^(-1)*e^2*Tag({25,31,32})*(t+u)^(-1)*Color((-1+Nc)*(1+Nc))*g^4
;
name = tmpPPhsqgqbqb0r1vcomp7X2
  boxx34 3 7  3 3  1 1 1 -3
   -(8*I)*t^(-1)*e^2*Tag({25,31,32})*Color((-1+Nc)*(1+Nc))*g^4*u^(-1)
    boxx34 3 7  3 2  1 1 1 -2
     -(4*I)*(5*u^(-1)+2*t^(-1))*e^2*Tag({25,31,32})*Color((-1+Nc)*(1+Nc))*g^4
    boxx34 3 7  3 1  1 1 1 -1
     -(1/2*I)*e^2*Tag({25,31,32})*(20+2*dim+24*t*u^(-1)+3*t*dim*u^(-1))*Color((-1+Nc)*(1+Nc))*g^4
    boxx34 3 7  3 0  1 1 1 0
     -(1/2*I)*e^2*Tag({25,31,32})*Color((-1+Nc)*(1+Nc))*(3*t^2*dim*u^(-1)-4*t+2*dim*u+5*t*dim-4*u)*g^4
    boxx34 2 6  2 2  0 1 1 -2
     (16*I)*t^(-1)*e^2*Tag({25,31,32})*Color((-1+Nc)*(1+Nc))*g^4*u^(-1)
    boxx34 2 6  2 2  -1 1 1 -1
     -(8*I)*t^(-1)*e^2*Tag({25,31,32})*Color((-1+Nc)*(1+Nc))*g^4*u^(-1)
    boxx34 2 6  2 1  0 1 1 -1
     I*e^2*Tag({25,31,32})*Color((-1+Nc)*(1+Nc))*(22*u^(-1)+dim*u^(-1)+12*t^(-1))*g^4
    boxx34 2 6  2 1  -1 1 1 0
     -I*e^2*Tag({25,31,32})*(2*u^(-1)+dim*u^(-1)+6*t^(-1)-t^(-1)*dim)*Color((-1+Nc)*(1+Nc))*g^4
    boxx34 2 6  2 0  0 1 1 0
     (1/2*I)*e^2*Tag({25,31,32})*Color((-1+Nc)*(1+Nc))*(8+2*t^(-1)*dim*u+3*dim+4*t*u^(-1)+5*t*dim*u^(-1)-4*t^(-1)*u)*g^4
    boxx34 2 5  2 2  1 0 1 -2
     -(8*I)*t^(-1)*e^2*Tag({25,31,32})*Color((-1+Nc)*(1+Nc))*g^4*u^(-1)
    boxx34 2 5  2 1  1 0 1 -1
     -I*e^2*Tag({25,31,32})*(10*u^(-1)+dim*u^(-1)-4*t^(-1)+2*t^(-1)*dim)*Color((-1+Nc)*(1+Nc))*g^4
    boxx34 2 5  2 1  1 -1 1 0
     -I*e^2*Tag({25,31,32})*(-2+dim)*Color((-1+Nc)*(1+Nc))*g^4*u^(-1)
    boxx34 2 5  2 0  1 0 1 0
     -(1/2*I)*e^2*Tag({25,31,32})*(-16+6*dim-4*t*u^(-1)+5*t*dim*u^(-1))*Color((-1+Nc)*(1+Nc))*g^4
    boxx34 2 3  2 2  1 1 0 -2
     (16*I)*t^(-1)*e^2*Tag({25,31,32})*Color((-1+Nc)*(1+Nc))*g^4*u^(-1)
    boxx34 2 3  2 2  1 1 -1 -1
     -(8*I)*t^(-1)*e^2*Tag({25,31,32})*Color((-1+Nc)*(1+Nc))*g^4*u^(-1)
    boxx34 2 3  2 1  1 1 0 -1
     I*e^2*Tag({25,31,32})*Color((-1+Nc)*(1+Nc))*(22*u^(-1)+dim*u^(-1)+12*t^(-1))*g^4
    boxx34 2 3  2 1  1 1 -1 0
     -I*e^2*Tag({25,31,32})*(2*u^(-1)+dim*u^(-1)+6*t^(-1)-t^(-1)*dim)*Color((-1+Nc)*(1+Nc))*g^4
    boxx34 2 3  2 0  1 1 0 0
     (1/2*I)*e^2*Tag({25,31,32})*Color((-1+Nc)*(1+Nc))*(8+2*t^(-1)*dim*u+3*dim+4*t*u^(-1)+5*t*dim*u^(-1)-4*t^(-1)*u)*g^4
    boxx34 1 4  1 1  0 0 1 -1
     (8*I)*t^(-1)*e^2*Tag({25,31,32})*Color((-1+Nc)*(1+Nc))*g^4*u^(-1)
    boxx34 1 4  1 0  0 0 1 0
     I*e^2*Tag({25,31,32})*(2*dim*u^(-1)-2*t^(-1)+t^(-1)*dim)*Color((-1+Nc)*(1+Nc))*g^4
    boxx34 1 2  1 1  0 1 0 -1
     -(24*I)*t^(-1)*e^2*Tag({25,31,32})*Color((-1+Nc)*(1+Nc))*g^4*u^(-1)
    boxx34 1 2  1 1  0 1 -1 0
     (8*I)*t^(-1)*e^2*Tag({25,31,32})*Color((-1+Nc)*(1+Nc))*g^4*u^(-1)
    boxx34 1 2  1 1  -1 1 0 0
     (8*I)*t^(-1)*e^2*Tag({25,31,32})*Color((-1+Nc)*(1+Nc))*g^4*u^(-1)
    boxx34 1 2  1 0  0 1 0 0
     -(2*I)*(6*u^(-1)+dim*u^(-1)+2*t^(-1)+t^(-1)*dim)*e^2*Tag({25,31,32})*Color((-1+Nc)*(1+Nc))*g^4
    boxx34 1 1  1 1  1 0 0 -1
     (8*I)*t^(-1)*e^2*Tag({25,31,32})*Color((-1+Nc)*(1+Nc))*g^4*u^(-1)
    boxx34 1 1  1 0  1 0 0 0
     I*e^2*Tag({25,31,32})*(2*dim*u^(-1)-2*t^(-1)+t^(-1)*dim)*Color((-1+Nc)*(1+Nc))*g^4
    boxx34 0 0  0 0  0 0 0 0
     -(8*I)*t^(-1)*e^2*Tag({25,31,32})*Color((-1+Nc)*(1+Nc))*g^4*u^(-1)
;
name = tmpPPhsqgqbqb0r1vcomp8X1
  boxx34 3 7  3 3  1 1 1 -3
   -(8*I)*t^(-1)*e^2*Tag({25,31,32})*(t+u)^(-1)*Color((-1+Nc)*(1+Nc))*g^4
    boxx34 3 7  3 2  1 1 1 -2
     -(4*I)*(3+2*t^(-1)*u)*e^2*Tag({25,31,32})*(t+u)^(-1)*Color((-1+Nc)*(1+Nc))*g^4
    boxx34 3 7  3 1  1 1 1 -1
     -(1/2*I)*e^2*Tag({25,31,32})*(t+u)^(-1)*(4*t-2*dim*u+t*dim+12*u)*Color((-1+Nc)*(1+Nc))*g^4
    boxx34 3 7  3 0  1 1 1 0
     (1/2*I)*e^2*Tag({25,31,32})*(t+u)^(-1)*Color((-1+Nc)*(1+Nc))*(t*dim*u+2*dim*u^2+4*t^2-t^2*dim-4*u^2)*g^4
    boxx34 2 6  2 2  0 1 1 -2
     (8*I)*t^(-1)*e^2*Tag({25,31,32})*(t+u)^(-1)*Color((-1+Nc)*(1+Nc))*g^4
    boxx34 2 6  2 1  0 1 1 -1
     I*e^2*Tag({25,31,32})*(t+u)^(-1)*Color((-1+Nc)*(1+Nc))*g^4*(2+dim+4*t^(-1)*u)
    boxx34 2 6  2 1  -1 1 1 0
     I*e^2*Tag({25,31,32})*(t+u)^(-1)*Color((-1+Nc)*(1+Nc))*(-2+t^(-1)*dim*u+dim-2*t^(-1)*u)*g^4
    boxx34 2 6  2 0  0 1 1 0
     -(1/2*I)*e^2*Tag({25,31,32})*(t+u)^(-1)*(3*dim*u+2*t^(-1)*dim*u^2+t*dim-4*t^(-1)*u^2-4*u)*Color((-1+Nc)*(1+Nc))*g^4
    boxx34 2 5  2 2  1 0 1 -2
     (8*I)*t^(-1)*e^2*Tag({25,31,32})*(t+u)^(-1)*Color((-1+Nc)*(1+Nc))*g^4
    boxx34 2 5  2 1  1 0 1 -1
     I*(2+2*t^(-1)*dim*u+dim-4*t^(-1)*u)*e^2*Tag({25,31,32})*(t+u)^(-1)*Color((-1+Nc)*(1+Nc))*g^4
    boxx34 2 5  2 1  1 -1 1 0
     I*e^2*Tag({25,31,32})*(t+u)^(-1)*(-2+dim)*Color((-1+Nc)*(1+Nc))*g^4
    boxx34 2 5  2 0  1 0 1 0
     -(1/2*I)*e^2*Tag({25,31,32})*(2*dim*u-t*dim-8*u)*(t+u)^(-1)*Color((-1+Nc)*(1+Nc))*g^4
    boxx34 2 3  2 2  1 1 0 -2
     (8*I)*t^(-1)*e^2*Tag({25,31,32})*(t+u)^(-1)*Color((-1+Nc)*(1+Nc))*g^4
    boxx34 2 3  2 1  1 1 0 -1
     I*e^2*Tag({25,31,32})*(t+u)^(-1)*Color((-1+Nc)*(1+Nc))*g^4*(2+dim+4*t^(-1)*u)
    boxx34 2 3  2 1  1 1 -1 0
     I*e^2*Tag({25,31,32})*(t+u)^(-1)*Color((-1+Nc)*(1+Nc))*(-2+t^(-1)*dim*u+dim-2*t^(-1)*u)*g^4
    boxx34 2 3  2 0  1 1 0 0
     -(1/2*I)*e^2*Tag({25,31,32})*(t+u)^(-1)*(3*dim*u+2*t^(-1)*dim*u^2+t*dim-4*t^(-1)*u^2-4*u)*Color((-1+Nc)*(1+Nc))*g^4
    boxx34 1 4  1 1  0 0 1 -1
     -(8*I)*t^(-1)*e^2*Tag({25,31,32})*(t+u)^(-1)*Color((-1+Nc)*(1+Nc))*g^4
    boxx34 1 4  1 0  0 0 1 0
     -I*e^2*Tag({25,31,32})*(-4+t^(-1)*dim*u+2*dim-2*t^(-1)*u)*(t+u)^(-1)*Color((-1+Nc)*(1+Nc))*g^4
    boxx34 1 2  1 1  0 1 0 -1
     -(8*I)*t^(-1)*e^2*Tag({25,31,32})*(t+u)^(-1)*Color((-1+Nc)*(1+Nc))*g^4
    boxx34 1 2  1 0  0 1 0 0
     -(2*I)*e^2*Tag({25,31,32})*(t+u)^(-1)*Color((-1+Nc)*(1+Nc))*(-2+t^(-1)*dim*u+dim-2*t^(-1)*u)*g^4
    boxx34 1 1  1 1  1 0 0 -1
     -(8*I)*t^(-1)*e^2*Tag({25,31,32})*(t+u)^(-1)*Color((-1+Nc)*(1+Nc))*g^4
    boxx34 1 1  1 0  1 0 0 0
     -I*e^2*Tag({25,31,32})*(-4+t^(-1)*dim*u+2*dim-2*t^(-1)*u)*(t+u)^(-1)*Color((-1+Nc)*(1+Nc))*g^4
    boxx34 0 0  0 0  0 0 0 0
     (8*I)*t^(-1)*e^2*Tag({25,31,32})*(t+u)^(-1)*Color((-1+Nc)*(1+Nc))*g^4
;
name = tmpPPhsqgqbqb0r1vcomp8X2
  boxx34 3 7  3 3  1 1 1 -3
   (8*I)*t^(-1)*e^2*Tag({25,31,32})*Color((-1+Nc)*(1+Nc))*g^4*u^(-1)
    boxx34 3 7  3 2  1 1 1 -2
     (4*I)*(5*u^(-1)+2*t^(-1))*e^2*Tag({25,31,32})*Color((-1+Nc)*(1+Nc))*g^4
    boxx34 3 7  3 1  1 1 1 -1
     (1/2*I)*e^2*Tag({25,31,32})*(20+2*dim+24*t*u^(-1)+3*t*dim*u^(-1))*Color((-1+Nc)*(1+Nc))*g^4
    boxx34 3 7  3 0  1 1 1 0
     (1/2*I)*e^2*Tag({25,31,32})*Color((-1+Nc)*(1+Nc))*(3*t^2*dim*u^(-1)-4*t+2*dim*u+5*t*dim-4*u)*g^4
    boxx34 2 6  2 2  0 1 1 -2
     -(16*I)*t^(-1)*e^2*Tag({25,31,32})*Color((-1+Nc)*(1+Nc))*g^4*u^(-1)
    boxx34 2 6  2 2  -1 1 1 -1
     (8*I)*t^(-1)*e^2*Tag({25,31,32})*Color((-1+Nc)*(1+Nc))*g^4*u^(-1)
    boxx34 2 6  2 1  0 1 1 -1
     -I*e^2*Tag({25,31,32})*Color((-1+Nc)*(1+Nc))*(22*u^(-1)+dim*u^(-1)+12*t^(-1))*g^4
    boxx34 2 6  2 1  -1 1 1 0
     I*e^2*Tag({25,31,32})*(2*u^(-1)+dim*u^(-1)+6*t^(-1)-t^(-1)*dim)*Color((-1+Nc)*(1+Nc))*g^4
    boxx34 2 6  2 0  0 1 1 0
     -(1/2*I)*e^2*Tag({25,31,32})*Color((-1+Nc)*(1+Nc))*(8+2*t^(-1)*dim*u+3*dim+4*t*u^(-1)+5*t*dim*u^(-1)-4*t^(-1)*u)*g^4
    boxx34 2 5  2 2  1 0 1 -2
     (8*I)*t^(-1)*e^2*Tag({25,31,32})*Color((-1+Nc)*(1+Nc))*g^4*u^(-1)
    boxx34 2 5  2 1  1 0 1 -1
     I*e^2*Tag({25,31,32})*(10*u^(-1)+dim*u^(-1)-4*t^(-1)+2*t^(-1)*dim)*Color((-1+Nc)*(1+Nc))*g^4
    boxx34 2 5  2 1  1 -1 1 0
     I*e^2*Tag({25,31,32})*(-2+dim)*Color((-1+Nc)*(1+Nc))*g^4*u^(-1)
    boxx34 2 5  2 0  1 0 1 0
     (1/2*I)*e^2*Tag({25,31,32})*(-16+6*dim-4*t*u^(-1)+5*t*dim*u^(-1))*Color((-1+Nc)*(1+Nc))*g^4
    boxx34 2 3  2 2  1 1 0 -2
     -(16*I)*t^(-1)*e^2*Tag({25,31,32})*Color((-1+Nc)*(1+Nc))*g^4*u^(-1)
    boxx34 2 3  2 2  1 1 -1 -1
     (8*I)*t^(-1)*e^2*Tag({25,31,32})*Color((-1+Nc)*(1+Nc))*g^4*u^(-1)
    boxx34 2 3  2 1  1 1 0 -1
     -I*e^2*Tag({25,31,32})*Color((-1+Nc)*(1+Nc))*(22*u^(-1)+dim*u^(-1)+12*t^(-1))*g^4
    boxx34 2 3  2 1  1 1 -1 0
     I*e^2*Tag({25,31,32})*(2*u^(-1)+dim*u^(-1)+6*t^(-1)-t^(-1)*dim)*Color((-1+Nc)*(1+Nc))*g^4
    boxx34 2 3  2 0  1 1 0 0
     -(1/2*I)*e^2*Tag({25,31,32})*Color((-1+Nc)*(1+Nc))*(8+2*t^(-1)*dim*u+3*dim+4*t*u^(-1)+5*t*dim*u^(-1)-4*t^(-1)*u)*g^4
    boxx34 1 4  1 1  0 0 1 -1
     -(8*I)*t^(-1)*e^2*Tag({25,31,32})*Color((-1+Nc)*(1+Nc))*g^4*u^(-1)
    boxx34 1 4  1 0  0 0 1 0
     -I*e^2*Tag({25,31,32})*(2*dim*u^(-1)-2*t^(-1)+t^(-1)*dim)*Color((-1+Nc)*(1+Nc))*g^4
    boxx34 1 2  1 1  0 1 0 -1
     (24*I)*t^(-1)*e^2*Tag({25,31,32})*Color((-1+Nc)*(1+Nc))*g^4*u^(-1)
    boxx34 1 2  1 1  0 1 -1 0
     -(8*I)*t^(-1)*e^2*Tag({25,31,32})*Color((-1+Nc)*(1+Nc))*g^4*u^(-1)
    boxx34 1 2  1 1  -1 1 0 0
     -(8*I)*t^(-1)*e^2*Tag({25,31,32})*Color((-1+Nc)*(1+Nc))*g^4*u^(-1)
    boxx34 1 2  1 0  0 1 0 0
     (2*I)*(6*u^(-1)+dim*u^(-1)+2*t^(-1)+t^(-1)*dim)*e^2*Tag({25,31,32})*Color((-1+Nc)*(1+Nc))*g^4
    boxx34 1 1  1 1  1 0 0 -1
     -(8*I)*t^(-1)*e^2*Tag({25,31,32})*Color((-1+Nc)*(1+Nc))*g^4*u^(-1)
    boxx34 1 1  1 0  1 0 0 0
     -I*e^2*Tag({25,31,32})*(2*dim*u^(-1)-2*t^(-1)+t^(-1)*dim)*Color((-1+Nc)*(1+Nc))*g^4
    boxx34 0 0  0 0  0 0 0 0
     (8*I)*t^(-1)*e^2*Tag({25,31,32})*Color((-1+Nc)*(1+Nc))*g^4*u^(-1)
;
name = tmpPPhsqgqbqb0r1vcomp9X1
  boxx234 3 7  3 1  1 1 1 -1
   (1/4*I)*Color(Nc^(-1)*(-1+Nc)*(1+Nc))*e^2*(t+u)^(-2)*(72*t*dim*u+36*dim*u^2-64*t*u-32*t^2+dim^3*u^2+36*t^2*dim+2*t*dim^3*u+t^2*dim^3-32*u^2-12*dim^2*u^2-12*t^2*dim^2-24*t*dim^2*u)*g^4
    boxx234 3 7  3 0  1 1 1 0
     -(1/4*I)*Color(Nc^(-1)*(-1+Nc)*(1+Nc))*t*e^2*(t+u)^(-2)*(72*t*dim*u+36*dim*u^2-64*t*u-32*t^2+dim^3*u^2+36*t^2*dim+2*t*dim^3*u+t^2*dim^3-32*u^2-12*dim^2*u^2-12*t^2*dim^2-24*t*dim^2*u)*g^4
    boxx234 2 6  2 0  0 1 1 0
     -(1/4*I)*Color(Nc^(-1)*(-1+Nc)*(1+Nc))*e^2*(52*t*dim*u+16*dim*u^2-48*t*u-32*t^2+36*t^2*dim+t*dim^3*u+t^2*dim^3-16*u^2-4*dim^2*u^2-12*t^2*dim^2-16*t*dim^2*u)*(t+u)^(-2)*g^4
    boxx234 2 5  2 1  1 0 1 -1
     I*Color(Nc^(-1)*(-1+Nc)*(1+Nc))*e^2*(t*dim^2+4*t-4*dim*u-4*t*dim+dim^2*u+4*u)*(t+u)^(-2)*g^4
    boxx234 2 5  2 0  1 0 1 0
     (1/4*I)*(56*t*dim*u+20*dim*u^2-48*t*u-32*t^2+dim^3*u^2+36*t^2*dim+2*t*dim^3*u+t^2*dim^3-16*u^2-8*dim^2*u^2-12*t^2*dim^2-20*t*dim^2*u)*Color(Nc^(-1)*(-1+Nc)*(1+Nc))*e^2*(t+u)^(-2)*g^4
    boxx234 2 3  2 1  1 1 0 -1
     -I*Color(Nc^(-1)*(-1+Nc)*(1+Nc))*e^2*(t*dim^2+4*t-4*dim*u-4*t*dim+dim^2*u+4*u)*(t+u)^(-2)*g^4
    boxx234 2 3  2 0  1 1 0 0
     (1/4*I)*Color(Nc^(-1)*(-1+Nc)*(1+Nc))*t*e^2*(t+u)^(-2)*(12*t*dim^2-t*dim^3+32*t-36*dim*u-36*t*dim+12*dim^2*u+32*u-dim^3*u)*g^4
    boxx234 1 4  1 0  0 0 1 0
     -I*Color(Nc^(-1)*(-1+Nc)*(1+Nc))*e^2*(t*dim^2+4*t-4*dim*u-4*t*dim+dim^2*u+4*u)*(t+u)^(-2)*g^4
    boxx234 1 2  1 0  0 1 0 0
     I*Color(Nc^(-1)*(-1+Nc)*(1+Nc))*e^2*(t*dim^2+4*t-4*dim*u-4*t*dim+dim^2*u+4*u)*(t+u)^(-2)*g^4
;
name = tmpPPhsqgqbqb0r1vcomp9X2
  boxx234 3 7  3 2  1 1 1 -2
   -(1/2*I)*Color(Nc^(-1)*(-1+Nc)*(1+Nc))*e^2*(t+u)^(-1)*(4+t*dim^2*u^(-1)-4*dim+4*t*u^(-1)-4*t*dim*u^(-1)+dim^2)*g^4
    boxx234 3 7  3 1  1 1 1 -1
     -(1/4*I)*Color(Nc^(-1)*(-1+Nc)*(1+Nc))*(84*t^2*dim*u^(-1)-34*t*dim^2+2*t*dim^3-224*t+72*dim*u-120*t^2*u^(-1)+156*t*dim-16*dim^2*u+t^2*dim^3*u^(-1)-18*t^2*dim^2*u^(-1)-104*u+dim^3*u)*e^2*(t+u)^(-1)*g^4
    boxx234 3 7  3 0  1 1 1 0
     (1/4*I)*Color(Nc^(-1)*(-1+Nc)*(1+Nc))*t*e^2*(t+u)^(-1)*g^4*(76*t^2*dim*u^(-1)-32*t*dim^2+2*t*dim^3-216*t+72*dim*u-112*t^2*u^(-1)+148*t*dim-16*dim^2*u+t^2*dim^3*u^(-1)-16*t^2*dim^2*u^(-1)-104*u+dim^3*u)
    boxx234 2 6  2 1  0 1 1 -1
     (1/2*I)*Color(Nc^(-1)*(-1+Nc)*(1+Nc))*e^2*(t+u)^(-1)*(8+2*t*dim^2*u^(-1)-6*dim+12*t*u^(-1)-10*t*dim*u^(-1)+dim^2)*g^4
    boxx234 2 6  2 1  -1 1 1 0
     (1/2*I)*Color(Nc^(-1)*(-1+Nc)*(1+Nc))*t*e^2*(-8+6*dim-dim^2)*(t+u)^(-1)*g^4*u^(-1)
    boxx234 2 6  2 0  0 1 1 0
     (1/4*I)*Color(Nc^(-1)*(-1+Nc)*(1+Nc))*e^2*(t+u)^(-1)*(88*t^2*dim*u^(-1)-22*t*dim^2+t*dim^3-168*t+24*dim*u-128*t^2*u^(-1)+116*t*dim-4*dim^2*u+t^2*dim^3*u^(-1)-18*t^2*dim^2*u^(-1)-32*u)*g^4
    boxx234 2 5  2 1  1 0 1 -1
     -(1/2*I)*Color(Nc^(-1)*(-1+Nc)*(1+Nc))*e^2*(t+u)^(-1)*g^4*(8+t*dim^2*u^(-1)-6*dim+8*t*u^(-1)-6*t*dim*u^(-1)+dim^2)
    boxx234 2 5  2 1  1 -1 1 0
     I*Color(Nc^(-1)*(-1+Nc)*(1+Nc))*e^2*(t+u)^(-1)*(-2+dim-2*t*u^(-1)+t*dim*u^(-1))*g^4
    boxx234 2 5  2 0  1 0 1 0
     -(1/4*I)*Color(Nc^(-1)*(-1+Nc)*(1+Nc))*e^2*(t+u)^(-1)*(80*t^2*dim*u^(-1)-24*t*dim^2+2*t*dim^3-112*t+16*dim*u-120*t^2*u^(-1)+96*t*dim-8*dim^2*u+t^2*dim^3*u^(-1)-16*t^2*dim^2*u^(-1)+8*u+dim^3*u)*g^4
    boxx234 2 3  2 1  1 1 0 -1
     (1/2*I)*Color(Nc^(-1)*(-1+Nc)*(1+Nc))*e^2*(t+u)^(-1)*(8+t*dim^2*u^(-1)-8*dim+4*t*u^(-1)-4*t*dim*u^(-1)+2*dim^2)*g^4
    boxx234 2 3  2 0  1 1 0 0
     -(1/4*I)*Color(Nc^(-1)*(-1+Nc)*(1+Nc))*t*e^2*(t+u)^(-1)*(104+16*t*dim^2*u^(-1)-t*dim^3*u^(-1)-72*dim+112*t*u^(-1)-76*t*dim*u^(-1)-dim^3+16*dim^2)*g^4
    boxx234 1 4  1 0  0 0 1 0
     (1/2*I)*Color(Nc^(-1)*(-1+Nc)*(1+Nc))*e^2*(8+t*dim^2*u^(-1)-6*dim+12*t*u^(-1)-8*t*dim*u^(-1)+dim^2)*(t+u)^(-1)*g^4
    boxx234 1 2  1 0  0 1 0 0
     -(1/2*I)*Color(Nc^(-1)*(-1+Nc)*(1+Nc))*e^2*(16+t*dim^2*u^(-1)-12*dim+8*t*u^(-1)-6*t*dim*u^(-1)+2*dim^2)*(t+u)^(-1)*g^4
    boxx234 1 1  1 0  1 0 0 0
     -I*Color(Nc^(-1)*(-1+Nc)*(1+Nc))*(-4+2*dim-2*t*u^(-1)+t*dim*u^(-1))*e^2*(t+u)^(-1)*g^4
;
name = tmpPPhsqgqbqb0r1vcomp10X1
  boxx234 3 7  3 1  1 1 1 -1
   -(1/2*I)*Color(Nc*(-1+Nc)*(1+Nc))*e^2*(t+u)^(-2)*(8*t*dim*u+4*dim*u^2-8*t*u-4*t^2+4*t^2*dim-4*u^2-dim^2*u^2-t^2*dim^2-2*t*dim^2*u)*g^4
    boxx234 3 7  3 0  1 1 1 0
     (1/2*I)*(8*dim*u^3-4*t^2*dim^2*u-20*t*u^2-4*t^3+20*t*dim*u^2-5*t*dim^2*u^2-16*t^2*u-t^3*dim^2+16*t^2*dim*u+4*t^3*dim-8*u^3-2*dim^2*u^3)*Color(Nc*(-1+Nc)*(1+Nc))*e^2*(t+u)^(-2)*g^4
    boxx234 2 6  2 0  0 1 1 0
     (1/2*I)*Color(Nc*(-1+Nc)*(1+Nc))*e^2*(t+u)^(-2)*(12*t*dim*u+8*dim*u^2-12*t*u-4*t^2+4*t^2*dim-8*u^2-2*dim^2*u^2-t^2*dim^2-3*t*dim^2*u)*g^4
    boxx234 2 5  2 1  1 0 1 -1
     I*Color(Nc*(-1+Nc)*(1+Nc))*e^2*(t*dim^2+4*t-4*dim*u-4*t*dim+dim^2*u+4*u)*(t+u)^(-2)*g^4
    boxx234 2 5  2 0  1 0 1 0
     -I*Color(Nc*(-1+Nc)*(1+Nc))*e^2*(t*dim^2+4*t-4*dim*u-4*t*dim+dim^2*u+4*u)*(t+u)^(-2)*g^4*u
    boxx234 2 3  2 1  1 1 0 -1
     -I*Color(Nc*(-1+Nc)*(1+Nc))*e^2*(t*dim^2+4*t-4*dim*u-4*t*dim+dim^2*u+4*u)*(t+u)^(-2)*g^4
    boxx234 2 3  2 0  1 1 0 0
     -(1/2*I)*Color(Nc*(-1+Nc)*(1+Nc))*e^2*(t*dim^2+4*t-4*dim*u-4*t*dim+dim^2*u+4*u)*(t+u)^(-2)*g^4*u
    boxx234 1 4  1 0  0 0 1 0
     -I*Color(Nc*(-1+Nc)*(1+Nc))*e^2*(t*dim^2+4*t-4*dim*u-4*t*dim+dim^2*u+4*u)*(t+u)^(-2)*g^4
    boxx234 1 2  1 0  0 1 0 0
     I*Color(Nc*(-1+Nc)*(1+Nc))*e^2*(t*dim^2+4*t-4*dim*u-4*t*dim+dim^2*u+4*u)*(t+u)^(-2)*g^4
;
name = tmpPPhsqgqbqb0r1vcomp10X2
  boxx234 3 7  3 2  1 1 1 -2
   -(1/2*I)*Color(Nc*(-1+Nc)*(1+Nc))*e^2*(t+u)^(-1)*(4+t*dim^2*u^(-1)-4*dim+4*t*u^(-1)-4*t*dim*u^(-1)+dim^2)*g^4
    boxx234 3 7  3 1  1 1 1 -1
     (1/4*I)*Color(Nc*(-1+Nc)*(1+Nc))*e^2*(t+u)^(-1)*(10*t^2*dim*u^(-1)-t*dim^2-92*t+22*dim*u-40*t^2*u^(-1)+32*t*dim-2*dim^2*u+t^2*dim^2*u^(-1)-52*u)*g^4
    boxx234 3 7  3 0  1 1 1 0
     -(1/4*I)*Color(Nc*(-1+Nc)*(1+Nc))*e^2*(t+u)^(-1)*(74*t*dim*u-48*t^3*u^(-1)+24*dim*u^2-124*t*u-t^3*dim^2*u^(-1)-140*t^2+68*t^2*dim+18*t^3*dim*u^(-1)-32*u^2-4*dim^2*u^2-7*t^2*dim^2-10*t*dim^2*u)*g^4
    boxx234 2 6  2 1  0 1 1 -1
     (1/2*I)*Color(Nc*(-1+Nc)*(1+Nc))*e^2*(t+u)^(-1)*(8+2*t*dim^2*u^(-1)-6*dim+12*t*u^(-1)-10*t*dim*u^(-1)+dim^2)*g^4
    boxx234 2 6  2 1  -1 1 1 0
     (1/2*I)*Color(Nc*(-1+Nc)*(1+Nc))*t*e^2*(-8+6*dim-dim^2)*(t+u)^(-1)*g^4*u^(-1)
    boxx234 2 6  2 0  0 1 1 0
     -(1/4*I)*Color(Nc*(-1+Nc)*(1+Nc))*e^2*(t+u)^(-1)*(6*t^2*dim*u^(-1)-4*t*dim^2-76*t+24*dim*u-32*t^2*u^(-1)+38*t*dim-4*dim^2*u+t^2*dim^2*u^(-1)-32*u)*g^4
    boxx234 2 5  2 1  1 0 1 -1
     -(1/2*I)*Color(Nc*(-1+Nc)*(1+Nc))*e^2*(t+u)^(-1)*g^4*(8+t*dim^2*u^(-1)-6*dim+8*t*u^(-1)-6*t*dim*u^(-1)+dim^2)
    boxx234 2 5  2 1  1 -1 1 0
     I*Color(Nc*(-1+Nc)*(1+Nc))*e^2*(t+u)^(-1)*(-2+dim-2*t*u^(-1)+t*dim*u^(-1))*g^4
    boxx234 2 5  2 0  1 0 1 0
     (1/4*I)*(14*t^2*dim*u^(-1)+3*t*dim^2+28*t-34*dim*u-40*t^2*u^(-1)-20*t*dim+4*dim^2*u-t^2*dim^2*u^(-1)+68*u)*Color(Nc*(-1+Nc)*(1+Nc))*e^2*(t+u)^(-1)*g^4
    boxx234 2 3  2 1  1 1 0 -1
     (1/2*I)*Color(Nc*(-1+Nc)*(1+Nc))*e^2*(t+u)^(-1)*(8+t*dim^2*u^(-1)-8*dim+4*t*u^(-1)-4*t*dim*u^(-1)+2*dim^2)*g^4
    boxx234 2 3  2 0  1 1 0 0
     -(1/4*I)*Color(Nc*(-1+Nc)*(1+Nc))*e^2*(18*t^2*dim*u^(-1)-2*t*dim^2-52*t+12*dim*u-48*t^2*u^(-1)+22*t*dim-2*dim^2*u-t^2*dim^2*u^(-1)-16*u)*(t+u)^(-1)*g^4
    boxx234 1 4  1 0  0 0 1 0
     (1/2*I)*Color(Nc*(-1+Nc)*(1+Nc))*e^2*(8+t*dim^2*u^(-1)-6*dim+12*t*u^(-1)-8*t*dim*u^(-1)+dim^2)*(t+u)^(-1)*g^4
    boxx234 1 2  1 0  0 1 0 0
     -(1/2*I)*Color(Nc*(-1+Nc)*(1+Nc))*e^2*(16+t*dim^2*u^(-1)-12*dim+8*t*u^(-1)-6*t*dim*u^(-1)+2*dim^2)*(t+u)^(-1)*g^4
    boxx234 1 1  1 0  1 0 0 0
     -I*Color(Nc*(-1+Nc)*(1+Nc))*(-4+2*dim-2*t*u^(-1)+t*dim*u^(-1))*e^2*(t+u)^(-1)*g^4
;
name = tmpPPhsqgqbqb0r1vcomp11X1
  boxx34 4 15  4 0  1 1 1 1
   (1/4*I)*Color(Nc^(-1)*(-1+Nc)*(1+Nc))*t*e^2*(144*t*dim*u+68*dim*u^2-216*t*u-112*t^2+dim^3*u^2+76*t^2*dim+2*t*dim^3*u+t^2*dim^3-104*u^2-14*dim^2*u^2-16*t^2*dim^2-30*t*dim^2*u)*(t+u)^(-1)*g^4
    boxx34 3 14  3 1  -1 1 1 1
     -I*Color(Nc^(-1)*(-1+Nc)*(1+Nc))*e^2*(t+u)^(-1)*(2*t-dim*u-t*dim+2*u)*g^4
    boxx34 3 14  3 0  0 1 1 1
     -(1/4*I)*Color(Nc^(-1)*(-1+Nc)*(1+Nc))*e^2*(t+u)^(-1)*(148*t*dim*u+68*dim*u^2-224*t*u-120*t^2+dim^3*u^2+80*t^2*dim+2*t*dim^3*u+t^2*dim^3-104*u^2-14*dim^2*u^2-16*t^2*dim^2-30*t*dim^2*u)*g^4
    boxx34 3 13  3 1  1 -1 1 1
     (1/4*I)*Color(Nc^(-1)*(-1+Nc)*(1+Nc))*t*e^2*(t+u)^(-1)*(-104+68*dim+dim^3-14*dim^2)*g^4
    boxx34 3 13  3 0  1 0 1 1
     -(1/2*I)*Color(Nc^(-1)*(-1+Nc)*(1+Nc))*(15*t*dim^2-t*dim^3+108*t-76*dim*u-72*t*dim+16*dim^2*u+112*u-dim^3*u)*t*e^2*(t+u)^(-1)*g^4
    boxx34 3 11  3 1  1 1 -1 1
     -I*Color(Nc^(-1)*(-1+Nc)*(1+Nc))*e^2*(t+u)^(-1)*(2*t-dim*u-t*dim+2*u)*g^4
    boxx34 3 11  3 0  1 1 0 1
     -(1/4*I)*Color(Nc^(-1)*(-1+Nc)*(1+Nc))*e^2*(t+u)^(-1)*(148*t*dim*u+68*dim*u^2-224*t*u-120*t^2+dim^3*u^2+80*t^2*dim+2*t*dim^3*u+t^2*dim^3-104*u^2-14*dim^2*u^2-16*t^2*dim^2-30*t*dim^2*u)*g^4
    boxx34 3 7  3 2  1 1 1 -2
     -(2*I)*Color(Nc^(-1)*(-1+Nc)*(1+Nc))*e^2*(t+u)^(-1)*(-2+dim)*g^4
    boxx34 3 7  3 1  1 1 1 -1
     -(2*I)*Color(Nc^(-1)*(-1+Nc)*(1+Nc))*e^2*(t+u)^(-1)*(dim*u+t*dim-2*u)*g^4
    boxx34 3 7  3 0  1 1 1 0
     -(1/4*I)*Color(Nc^(-1)*(-1+Nc)*(1+Nc))*t*e^2*(16*t*dim^2-t*dim^3+128*t-68*dim*u-76*t*dim+14*dim^2*u+120*u-dim^3*u)*(t+u)^(-1)*g^4
    boxx34 2 12  2 0  0 0 1 1
     (1/4*I)*Color(Nc^(-1)*(-1+Nc)*(1+Nc))*e^2*(t+u)^(-1)*(14*t*dim^2-t*dim^3+112*t-68*dim*u-72*t*dim+14*dim^2*u+104*u-dim^3*u)*g^4
    boxx34 2 10  2 0  0 1 0 1
     -(2*I)*Color(Nc^(-1)*(-1+Nc)*(1+Nc))*e^2*(t+u)^(-1)*(t*dim^2+16*t-8*dim*u-8*t*dim+dim^2*u+16*u)*g^4
    boxx34 2 9  2 0  1 0 0 1
     (1/4*I)*Color(Nc^(-1)*(-1+Nc)*(1+Nc))*e^2*(t+u)^(-1)*(14*t*dim^2-t*dim^3+112*t-68*dim*u-72*t*dim+14*dim^2*u+104*u-dim^3*u)*g^4
    boxx34 2 6  2 1  0 1 1 -1
     (2*I)*Color(Nc^(-1)*(-1+Nc)*(1+Nc))*e^2*(t+u)^(-1)*(-2+dim)*g^4
    boxx34 2 6  2 0  0 1 1 0
     I*(t*dim^2+14*t-8*dim*u-7*t*dim+dim^2*u+16*u)*Color(Nc^(-1)*(-1+Nc)*(1+Nc))*e^2*(t+u)^(-1)*g^4
    boxx34 2 5  2 1  1 0 1 -1
     (2*I)*Color(Nc^(-1)*(-1+Nc)*(1+Nc))*e^2*(t+u)^(-1)*(-2+dim)*g^4
    boxx34 2 5  2 0  1 0 1 0
     -(1/4*I)*Color(Nc^(-1)*(-1+Nc)*(1+Nc))*e^2*(t+u)^(-1)*(14*t*dim^2-t*dim^3+88*t-136*dim*u-68*t*dim+28*dim^2*u+208*u-2*dim^3*u)*g^4
    boxx34 2 3  2 1  1 1 0 -1
     (2*I)*Color(Nc^(-1)*(-1+Nc)*(1+Nc))*e^2*(t+u)^(-1)*(-2+dim)*g^4
    boxx34 2 3  2 0  1 1 0 0
     I*(t*dim^2+14*t-8*dim*u-7*t*dim+dim^2*u+16*u)*Color(Nc^(-1)*(-1+Nc)*(1+Nc))*e^2*(t+u)^(-1)*g^4
    boxx34 1 8  1 0  0 0 0 1
     (2*I)*Color(Nc^(-1)*(-1+Nc)*(1+Nc))*e^2*(t+u)^(-1)*(-2+dim)*g^4
    boxx34 1 4  1 0  0 0 1 0
     -(2*I)*Color(Nc^(-1)*(-1+Nc)*(1+Nc))*e^2*(t+u)^(-1)*(-2+dim)*g^4
    boxx34 1 2  1 0  0 1 0 0
     -(2*I)*Color(Nc^(-1)*(-1+Nc)*(1+Nc))*e^2*(t+u)^(-1)*(-2+dim)*g^4
    boxx34 1 1  1 0  1 0 0 0
     -(2*I)*Color(Nc^(-1)*(-1+Nc)*(1+Nc))*e^2*(t+u)^(-1)*(-2+dim)*g^4
;
name = tmpPPhsqgqbqb0r1vcomp11X2
  boxx34 4 15  4 0  1 1 1 1
   -(1/4*I)*Color(Nc^(-1)*(-1+Nc)*(1+Nc))*t*e^2*(88*t^2*dim*u^(-1)-34*t*dim^2+2*t*dim^3-256*t+76*dim*u-144*t^2*u^(-1)+164*t*dim-16*dim^2*u+t^2*dim^3*u^(-1)-18*t^2*dim^2*u^(-1)-112*u+dim^3*u)*g^4
    boxx34 3 14  3 1  -1 1 1 1
     (1/2*I)*Color(Nc^(-1)*(-1+Nc)*(1+Nc))*e^2*(24+t*dim^2*u^(-1)-10*dim+16*t*u^(-1)-6*t*dim*u^(-1)+dim^2)*g^4
    boxx34 3 14  3 0  0 1 1 1
     (1/4*I)*(100*t^2*dim*u^(-1)-36*t*dim^2+2*t*dim^3-304*t+76*dim*u-176*t^2*u^(-1)+184*t*dim-16*dim^2*u+t^2*dim^3*u^(-1)-20*t^2*dim^2*u^(-1)-112*u+dim^3*u)*Color(Nc^(-1)*(-1+Nc)*(1+Nc))*e^2*g^4
    boxx34 3 13  3 1  1 -1 1 1
     -(1/4*I)*Color(Nc^(-1)*(-1+Nc)*(1+Nc))*t*e^2*(-112+76*dim+dim^3-16*dim^2)*g^4*u^(-1)
    boxx34 3 13  3 0  1 0 1 1
     (1/2*I)*Color(Nc^(-1)*(-1+Nc)*(1+Nc))*t*e^2*(128+17*t*dim^2*u^(-1)-t*dim^3*u^(-1)-88*dim+128*t*u^(-1)-82*t*dim*u^(-1)-dim^3+18*dim^2)*g^4
    boxx34 3 11  3 1  1 1 -1 1
     (1/2*I)*Color(Nc^(-1)*(-1+Nc)*(1+Nc))*e^2*(24+t*dim^2*u^(-1)-10*dim+16*t*u^(-1)-6*t*dim*u^(-1)+dim^2)*g^4
    boxx34 3 11  3 0  1 1 0 1
     (1/4*I)*(100*t^2*dim*u^(-1)-36*t*dim^2+2*t*dim^3-304*t+76*dim*u-176*t^2*u^(-1)+184*t*dim-16*dim^2*u+t^2*dim^3*u^(-1)-20*t^2*dim^2*u^(-1)-112*u+dim^3*u)*Color(Nc^(-1)*(-1+Nc)*(1+Nc))*e^2*g^4
    boxx34 3 7  3 2  1 1 1 -2
     (2*I)*Color(Nc^(-1)*(-1+Nc)*(1+Nc))*e^2*(-2+dim)*g^4*u^(-1)
    boxx34 3 7  3 1  1 1 1 -1
     (2*I)*Color(Nc^(-1)*(-1+Nc)*(1+Nc))*e^2*(-2+dim-2*t*u^(-1)+2*t*dim*u^(-1))*g^4
    boxx34 3 7  3 0  1 1 1 0
     (1/4*I)*(112+18*t*dim^2*u^(-1)-t*dim^3*u^(-1)-68*dim+144*t*u^(-1)-80*t*dim*u^(-1)-dim^3+16*dim^2)*Color(Nc^(-1)*(-1+Nc)*(1+Nc))*t*e^2*g^4
    boxx34 2 12  2 0  0 0 1 1
     -(1/4*I)*Color(Nc^(-1)*(-1+Nc)*(1+Nc))*e^2*(112+18*t*dim^2*u^(-1)-t*dim^3*u^(-1)-76*dim+144*t*u^(-1)-88*t*dim*u^(-1)-dim^3+16*dim^2)*g^4
    boxx34 2 10  2 1  0 1 -1 1
     -(2*I)*Color(Nc^(-1)*(-1+Nc)*(1+Nc))*e^2*(-2+dim)*g^4*u^(-1)
    boxx34 2 10  2 1  -1 1 0 1
     -(2*I)*Color(Nc^(-1)*(-1+Nc)*(1+Nc))*e^2*(-2+dim)*g^4*u^(-1)
    boxx34 2 10  2 0  0 1 0 1
     I*Color(Nc^(-1)*(-1+Nc)*(1+Nc))*e^2*(4+t*dim^2*u^(-1)-4*dim+12*t*u^(-1)-4*t*dim*u^(-1)+dim^2)*g^4
    boxx34 2 9  2 0  1 0 0 1
     -(1/4*I)*Color(Nc^(-1)*(-1+Nc)*(1+Nc))*e^2*(112+18*t*dim^2*u^(-1)-t*dim^3*u^(-1)-76*dim+144*t*u^(-1)-88*t*dim*u^(-1)-dim^3+16*dim^2)*g^4
    boxx34 2 6  2 1  0 1 1 -1
     -(4*I)*Color(Nc^(-1)*(-1+Nc)*(1+Nc))*e^2*(-2+dim)*g^4*u^(-1)
    boxx34 2 6  2 1  -1 1 1 0
     (2*I)*Color(Nc^(-1)*(-1+Nc)*(1+Nc))*e^2*(-2+dim)*g^4*u^(-1)
    boxx34 2 6  2 0  0 1 1 0
     -(1/2*I)*Color(Nc^(-1)*(-1+Nc)*(1+Nc))*e^2*(24+t*dim^2*u^(-1)-12*dim+8*t*u^(-1)+2*t*dim*u^(-1)+2*dim^2)*g^4
    boxx34 2 5  2 1  1 0 1 -1
     (2*I)*Color(Nc^(-1)*(-1+Nc)*(1+Nc))*e^2*(-2+dim)*g^4*u^(-1)
    boxx34 2 5  2 0  1 0 1 0
     (1/4*I)*Color(Nc^(-1)*(-1+Nc)*(1+Nc))*e^2*(224+16*t*dim^2*u^(-1)-t*dim^3*u^(-1)-152*dim+112*t*u^(-1)-68*t*dim*u^(-1)-2*dim^3+32*dim^2)*g^4
    boxx34 2 3  2 1  1 1 0 -1
     -(4*I)*Color(Nc^(-1)*(-1+Nc)*(1+Nc))*e^2*(-2+dim)*g^4*u^(-1)
    boxx34 2 3  2 1  1 1 -1 0
     (2*I)*Color(Nc^(-1)*(-1+Nc)*(1+Nc))*e^2*(-2+dim)*g^4*u^(-1)
    boxx34 2 3  2 0  1 1 0 0
     -(1/2*I)*Color(Nc^(-1)*(-1+Nc)*(1+Nc))*e^2*(24+t*dim^2*u^(-1)-12*dim+8*t*u^(-1)+2*t*dim*u^(-1)+2*dim^2)*g^4
    boxx34 1 8  1 0  0 0 0 1
     (2*I)*Color(Nc^(-1)*(-1+Nc)*(1+Nc))*e^2*(-2+dim)*g^4*u^(-1)
    boxx34 1 4  1 0  0 0 1 0
     -(2*I)*Color(Nc^(-1)*(-1+Nc)*(1+Nc))*e^2*(-2+dim)*g^4*u^(-1)
    boxx34 1 2  1 0  0 1 0 0
     (6*I)*Color(Nc^(-1)*(-1+Nc)*(1+Nc))*e^2*(-2+dim)*g^4*u^(-1)
    boxx34 1 1  1 0  1 0 0 0
     -(2*I)*Color(Nc^(-1)*(-1+Nc)*(1+Nc))*e^2*(-2+dim)*g^4*u^(-1)
;
name = tmpPPhsqgqbqb0r1vcomp12X1
  box 4 15  4 0  1 1 1 1
   -(1/4*I)*Color(Nc*(-1+Nc)*(1+Nc))*e^2*(44*t*dim*u+18*dim*u^2-104*t*u-56*t^2+26*t^2*dim-48*u^2-dim^2*u^2-3*t^2*dim^2-4*t*dim^2*u)*(t+u)^(-1)*g^4*u
    box 3 14  3 1  -1 1 1 1
     -I*Color(Nc*(-1+Nc)*(1+Nc))*e^2*(t+u)^(-1)*(2*t-dim*u-t*dim+2*u)*g^4
    box 3 14  3 0  0 1 1 1
     (1/4*I)*Color(Nc*(-1+Nc)*(1+Nc))*(40*t*dim*u+14*dim*u^2-96*t*u-56*t^2+26*t^2*dim-40*u^2-dim^2*u^2-3*t^2*dim^2-4*t*dim^2*u)*e^2*(t+u)^(-1)*g^4
    box 3 13  3 1  1 -1 1 1
     I*Color(Nc*(-1+Nc)*(1+Nc))*e^2*(4*t-3*dim*u-2*t*dim+10*u)*(t+u)^(-1)*g^4
    box 3 13  3 0  1 0 1 1
     -(1/4*I)*Color(Nc*(-1+Nc)*(1+Nc))*e^2*(t+u)^(-1)*(46*t*dim*u+30*dim*u^2-112*t*u-16*t^2+8*t^2*dim-88*u^2-dim^2*u^2-3*t*dim^2*u)*g^4
    box 3 11  3 1  1 1 -1 1
     -(1/4*I)*Color(Nc*(-1+Nc)*(1+Nc))*e^2*(t*dim^2+12*t-8*dim*u-8*t*dim+dim^2*u+12*u)*(t+u)^(-1)*g^4
    box 3 11  3 0  1 1 0 1
     -(1/4*I)*Color(Nc*(-1+Nc)*(1+Nc))*(16*t*dim*u+14*dim*u^2+20*t*u+16*t^2+2*t^2*dim+4*u^2-4*dim^2*u^2-t^2*dim^2-5*t*dim^2*u)*e^2*(t+u)^(-1)*g^4
    box 3 7  3 1  1 1 1 -1
     (1/4*I)*Color(Nc*(-1+Nc)*(1+Nc))*e^2*(t+u)^(-1)*(8*t-30*dim*u-4*t*dim+3*dim^2*u+64*u)*g^4
    box 3 7  3 0  1 1 1 0
     -(1/2*I)*Color(Nc*(-1+Nc)*(1+Nc))*(26*t*dim*u+32*dim*u^2-56*t*u+4*t^2-2*t^2*dim-64*u^2-4*dim^2*u^2-3*t*dim^2*u)*e^2*(t+u)^(-1)*g^4
    box 2 12  2 1  0 -1 1 1
     -(2*I)*Color(Nc*(-1+Nc)*(1+Nc))*e^2*(t+u)^(-1)*(-2+dim)*g^4
    box 2 12  2 0  0 0 1 1
     -I*(4*t-dim*u+6*u)*Color(Nc*(-1+Nc)*(1+Nc))*e^2*(t+u)^(-1)*g^4
    box 2 10  2 0  0 1 0 1
     (1/4*I)*Color(Nc*(-1+Nc)*(1+Nc))*e^2*(t+u)^(-1)*(5*t*dim^2+108*t-48*dim*u-48*t*dim+5*dim^2*u+108*u)*g^4
    box 2 9  2 0  1 0 0 1
     -(1/4*I)*Color(Nc*(-1+Nc)*(1+Nc))*e^2*(t+u)^(-1)*(40*t-4*dim*u-12*t*dim-dim^2*u+28*u)*g^4
    box 2 6  2 0  0 1 1 0
     -(1/4*I)*(3*t*dim^2+64*t-26*dim*u-30*t*dim+3*dim^2*u+56*u)*Color(Nc*(-1+Nc)*(1+Nc))*e^2*(t+u)^(-1)*g^4
    box 2 5  2 1  1 0 1 -1
     -(2*I)*Color(Nc*(-1+Nc)*(1+Nc))*e^2*(t+u)^(-1)*(-2+dim)*g^4
    box 2 5  2 1  1 -1 1 0
     (2*I)*Color(Nc*(-1+Nc)*(1+Nc))*e^2*(t+u)^(-1)*(-2+dim)*g^4
    box 2 5  2 0  1 0 1 0
     (1/4*I)*Color(Nc*(-1+Nc)*(1+Nc))*e^2*(t+u)^(-1)*(48*t+22*dim*u-8*t*dim-3*dim^2*u-32*u)*g^4
    box 2 3  2 1  1 1 0 -1
     (2*I)*Color(Nc*(-1+Nc)*(1+Nc))*e^2*(t+u)^(-1)*(-2+dim)*g^4
    box 2 3  2 0  1 1 0 0
     -(1/4*I)*Color(Nc*(-1+Nc)*(1+Nc))*e^2*(t*dim^2+40*t-22*dim*u-14*t*dim+2*dim^2*u+52*u)*(t+u)^(-1)*g^4
    box 1 8  1 0  0 0 0 1
     (2*I)*Color(Nc*(-1+Nc)*(1+Nc))*e^2*(t+u)^(-1)*(-2+dim)*g^4
    box 1 4  1 0  0 0 1 0
     (2*I)*Color(Nc*(-1+Nc)*(1+Nc))*e^2*(t+u)^(-1)*(-2+dim)*g^4
    box 1 2  1 0  0 1 0 0
     -(2*I)*Color(Nc*(-1+Nc)*(1+Nc))*e^2*(t+u)^(-1)*(-2+dim)*g^4
    box 1 1  1 0  1 0 0 0
     -(2*I)*Color(Nc*(-1+Nc)*(1+Nc))*e^2*(t+u)^(-1)*(-2+dim)*g^4
;
name = tmpPPhsqgqbqb0r1vcomp12X2
  box 4 15  4 0  1 1 1 1
   -(1/4*I)*Color(Nc*(-1+Nc)*(1+Nc))*(10*t*dim*u+18*dim*u^2-40*t*u+8*t^2-8*t^2*dim-48*u^2-dim^2*u^2+2*t^2*dim^2+t*dim^2*u)*e^2*g^4
    box 3 14  3 1  -1 1 1 1
     -I*Color(Nc*(-1+Nc)*(1+Nc))*e^2*(-10+3*dim-6*t*u^(-1)+t*dim*u^(-1))*g^4
    box 3 14  3 0  0 1 1 1
     -(1/4*I)*Color(Nc*(-1+Nc)*(1+Nc))*e^2*(8*t^2*dim*u^(-1)-t*dim^2+64*t-30*dim*u-8*t^2*u^(-1)-14*t*dim+dim^2*u-2*t^2*dim^2*u^(-1)+88*u)*g^4
    box 3 13  3 1  1 -1 1 1
     I*Color(Nc*(-1+Nc)*(1+Nc))*e^2*(-2+dim)*g^4
    box 3 13  3 0  1 0 1 1
     -(1/4*I)*Color(Nc*(-1+Nc)*(1+Nc))*e^2*(2*t*dim^2+16*t+14*dim*u-12*t*dim-dim^2*u-40*u)*g^4
    box 3 11  3 1  1 1 -1 1
     (1/4*I)*Color(Nc*(-1+Nc)*(1+Nc))*e^2*(64+3*t*dim^2*u^(-1)-30*dim+56*t*u^(-1)-26*t*dim*u^(-1)+3*dim^2)*g^4
    box 3 11  3 0  1 1 0 1
     (1/2*I)*Color(Nc*(-1+Nc)*(1+Nc))*e^2*(4*t^2*dim*u^(-1)-5*t*dim^2-72*t+32*dim*u-4*t^2*u^(-1)+38*t*dim-4*dim^2*u-t^2*dim^2*u^(-1)-64*u)*g^4
    box 3 7  3 1  1 1 1 -1
     (1/4*I)*(-12+8*dim-dim^2)*Color(Nc*(-1+Nc)*(1+Nc))*e^2*g^4
    box 3 7  3 0  1 1 1 0
     -(1/4*I)*Color(Nc*(-1+Nc)*(1+Nc))*(3*t*dim^2+12*t-14*dim*u-12*t*dim+4*dim^2*u-4*u)*e^2*g^4
    box 2 12  2 1  -1 0 1 1
     (2*I)*Color(Nc*(-1+Nc)*(1+Nc))*e^2*(-2+dim)*g^4*u^(-1)
    box 2 12  2 0  0 0 1 1
     I*Color(Nc*(-1+Nc)*(1+Nc))*e^2*(-6+dim-2*t*u^(-1)+t*dim*u^(-1))*g^4
    box 2 10  2 1  0 1 -1 1
     (2*I)*Color(Nc*(-1+Nc)*(1+Nc))*e^2*(-2+dim)*g^4*u^(-1)
    box 2 10  2 1  -1 1 0 1
     -(2*I)*Color(Nc*(-1+Nc)*(1+Nc))*e^2*(-2+dim)*g^4*u^(-1)
    box 2 10  2 0  0 1 0 1
     -(1/4*I)*Color(Nc*(-1+Nc)*(1+Nc))*e^2*(32+3*t*dim^2*u^(-1)-22*dim+80*t*u^(-1)-30*t*dim*u^(-1)+3*dim^2)*g^4
    box 2 9  2 0  1 0 0 1
     (1/4*I)*Color(Nc*(-1+Nc)*(1+Nc))*e^2*(-56+26*dim+8*t*u^(-1)-4*t*dim*u^(-1)-3*dim^2)*g^4
    box 2 6  2 0  0 1 1 0
     (1/4*I)*Color(Nc*(-1+Nc)*(1+Nc))*e^2*(-28+t*dim^2*u^(-1)+4*dim+12*t*u^(-1)-8*t*dim*u^(-1)+dim^2)*g^4
    box 2 5  2 0  1 0 1 0
     -(1/4*I)*Color(Nc*(-1+Nc)*(1+Nc))*e^2*(-108+48*dim-5*dim^2)*g^4
    box 2 3  2 1  1 1 -1 0
     -(2*I)*Color(Nc*(-1+Nc)*(1+Nc))*e^2*(-2+dim)*g^4*u^(-1)
    box 2 3  2 0  1 1 0 0
     -(1/4*I)*Color(Nc*(-1+Nc)*(1+Nc))*e^2*(52+t*dim^2*u^(-1)-22*dim+12*t*u^(-1)-8*t*dim*u^(-1)+2*dim^2)*g^4
    box 1 8  1 0  0 0 0 1
     -(2*I)*Color(Nc*(-1+Nc)*(1+Nc))*e^2*(-2+dim)*g^4*u^(-1)
    box 1 4  1 0  0 0 1 0
     -(2*I)*Color(Nc*(-1+Nc)*(1+Nc))*e^2*(-2+dim)*g^4*u^(-1)
    box 1 2  1 0  0 1 0 0
     (2*I)*Color(Nc*(-1+Nc)*(1+Nc))*e^2*(-2+dim)*g^4*u^(-1)
    box 1 1  1 0  1 0 0 0
     (2*I)*Color(Nc*(-1+Nc)*(1+Nc))*e^2*(-2+dim)*g^4*u^(-1)
;
name = tmpPPhsqgqbqb0r1vcomp13X1
  boxx23 4 15  4 0  1 1 1 1
   (1/4*I)*Color(Nc^(-1)*(-1+Nc)*(1+Nc))*t*e^2*(t+u)^(-1)*(2*t*dim^2+32*t+76*dim*u-12*t*dim-16*dim^2*u-112*u+dim^3*u)*g^4*u
    boxx23 3 14  3 1  -1 1 1 1
     (1/4*I)*Color(Nc^(-1)*(-1+Nc)*(1+Nc))*t*e^2*(t+u)^(-1)*(-112+76*dim+dim^3-16*dim^2)*g^4
    boxx23 3 14  3 0  0 1 1 1
     (1/2*I)*Color(Nc^(-1)*(-1+Nc)*(1+Nc))*t*e^2*(t*dim^2-88*dim*u-6*t*dim+18*dim^2*u+128*u-dim^3*u)*(t+u)^(-1)*g^4
    boxx23 3 13  3 1  1 -1 1 1
     (1/2*I)*(8*t-10*dim*u-4*t*dim+dim^2*u+24*u)*Color(Nc^(-1)*(-1+Nc)*(1+Nc))*e^2*(t+u)^(-1)*g^4
    boxx23 3 13  3 0  1 0 1 1
     (1/4*I)*Color(Nc^(-1)*(-1+Nc)*(1+Nc))*e^2*(t+u)^(-1)*(32*t*dim*u-76*dim*u^2-80*t*u-16*t^2-dim^3*u^2+8*t^2*dim+112*u^2+16*dim^2*u^2-4*t*dim^2*u)*g^4
    boxx23 3 11  3 2  1 1 -2 1
     -(2*I)*Color(Nc^(-1)*(-1+Nc)*(1+Nc))*e^2*(t+u)^(-1)*(-2+dim)*g^4
    boxx23 3 11  3 1  1 1 -1 1
     (2*I)*Color(Nc^(-1)*(-1+Nc)*(1+Nc))*e^2*(dim*u-t*dim-2*u)*(t+u)^(-1)*g^4
    boxx23 3 11  3 0  1 1 0 1
     -(1/4*I)*(2*t*dim^2+32*t+68*dim*u-12*t*dim-16*dim^2*u-112*u+dim^3*u)*Color(Nc^(-1)*(-1+Nc)*(1+Nc))*t*e^2*(t+u)^(-1)*g^4
    boxx23 3 7  3 1  1 1 1 -1
     (1/2*I)*(8*t-10*dim*u-4*t*dim+dim^2*u+24*u)*Color(Nc^(-1)*(-1+Nc)*(1+Nc))*e^2*(t+u)^(-1)*g^4
    boxx23 3 7  3 0  1 1 1 0
     (1/4*I)*Color(Nc^(-1)*(-1+Nc)*(1+Nc))*e^2*(t+u)^(-1)*(32*t*dim*u-76*dim*u^2-80*t*u-16*t^2-dim^3*u^2+8*t^2*dim+112*u^2+16*dim^2*u^2-4*t*dim^2*u)*g^4
    boxx23 2 12  2 0  0 0 1 1
     (1/4*I)*Color(Nc^(-1)*(-1+Nc)*(1+Nc))*e^2*(t+u)^(-1)*(2*t*dim^2+32*t+76*dim*u-12*t*dim-16*dim^2*u-112*u+dim^3*u)*g^4
    boxx23 2 10  2 1  0 1 -1 1
     -(2*I)*Color(Nc^(-1)*(-1+Nc)*(1+Nc))*e^2*(t+u)^(-1)*(-2+dim)*g^4
    boxx23 2 10  2 0  0 1 0 1
     (1/4*I)*Color(Nc^(-1)*(-1+Nc)*(1+Nc))*(16*t*dim^2-t*dim^3+112*t-152*dim*u-84*t*dim+32*dim^2*u+224*u-2*dim^3*u)*e^2*(t+u)^(-1)*g^4
    boxx23 2 9  2 1  1 0 -1 1
     (4*I)*Color(Nc^(-1)*(-1+Nc)*(1+Nc))*e^2*(t+u)^(-1)*(-2+dim)*g^4
    boxx23 2 9  2 1  1 -1 0 1
     -(2*I)*Color(Nc^(-1)*(-1+Nc)*(1+Nc))*e^2*(t+u)^(-1)*(-2+dim)*g^4
    boxx23 2 9  2 0  1 0 0 1
     -(1/2*I)*Color(Nc^(-1)*(-1+Nc)*(1+Nc))*e^2*(t*dim^2+16*t-12*dim*u-14*t*dim+2*dim^2*u+24*u)*(t+u)^(-1)*g^4
    boxx23 2 6  2 0  0 1 1 0
     (1/4*I)*Color(Nc^(-1)*(-1+Nc)*(1+Nc))*e^2*(t+u)^(-1)*(2*t*dim^2+32*t+76*dim*u-12*t*dim-16*dim^2*u-112*u+dim^3*u)*g^4
    boxx23 2 5  2 1  1 0 1 -1
     (2*I)*Color(Nc^(-1)*(-1+Nc)*(1+Nc))*e^2*(t+u)^(-1)*(-2+dim)*g^4
    boxx23 2 5  2 1  1 -1 1 0
     (2*I)*Color(Nc^(-1)*(-1+Nc)*(1+Nc))*e^2*(t+u)^(-1)*(-2+dim)*g^4
    boxx23 2 5  2 0  1 0 1 0
     -I*Color(Nc^(-1)*(-1+Nc)*(1+Nc))*(8*t+4*dim*u-dim^2*u-4*u)*e^2*(t+u)^(-1)*g^4
    boxx23 2 3  2 1  1 1 0 -1
     -(2*I)*Color(Nc^(-1)*(-1+Nc)*(1+Nc))*e^2*(t+u)^(-1)*(-2+dim)*g^4
    boxx23 2 3  2 1  1 1 -1 0
     (4*I)*Color(Nc^(-1)*(-1+Nc)*(1+Nc))*e^2*(t+u)^(-1)*(-2+dim)*g^4
    boxx23 2 3  2 0  1 1 0 0
     -(1/2*I)*Color(Nc^(-1)*(-1+Nc)*(1+Nc))*e^2*(t*dim^2+16*t-12*dim*u-14*t*dim+2*dim^2*u+24*u)*(t+u)^(-1)*g^4
    boxx23 1 8  1 0  0 0 0 1
     (2*I)*Color(Nc^(-1)*(-1+Nc)*(1+Nc))*e^2*(t+u)^(-1)*(-2+dim)*g^4
    boxx23 1 4  1 0  0 0 1 0
     -(2*I)*Color(Nc^(-1)*(-1+Nc)*(1+Nc))*e^2*(t+u)^(-1)*(-2+dim)*g^4
    boxx23 1 2  1 0  0 1 0 0
     (2*I)*Color(Nc^(-1)*(-1+Nc)*(1+Nc))*e^2*(t+u)^(-1)*(-2+dim)*g^4
    boxx23 1 1  1 0  1 0 0 0
     -(6*I)*Color(Nc^(-1)*(-1+Nc)*(1+Nc))*e^2*(t+u)^(-1)*(-2+dim)*g^4
;
name = tmpPPhsqgqbqb0r1vcomp13X2
  boxx23 4 15  4 0  1 1 1 1
   -(1/4*I)*Color(Nc^(-1)*(-1+Nc)*(1+Nc))*t*e^2*(2*t*dim^2+8*t+68*dim*u-8*t*dim-14*dim^2*u-104*u+dim^3*u)*g^4
    boxx23 3 14  3 1  -1 1 1 1
     -(1/4*I)*Color(Nc^(-1)*(-1+Nc)*(1+Nc))*t*e^2*(-104+68*dim+dim^3-14*dim^2)*g^4*u^(-1)
    boxx23 3 14  3 0  0 1 1 1
     -(1/2*I)*Color(Nc^(-1)*(-1+Nc)*(1+Nc))*t*e^2*(112+t*dim^2*u^(-1)-76*dim+4*t*u^(-1)-4*t*dim*u^(-1)-dim^3+16*dim^2)*g^4
    boxx23 3 13  3 1  1 -1 1 1
     I*Color(Nc^(-1)*(-1+Nc)*(1+Nc))*e^2*(-2+dim)*g^4
    boxx23 3 13  3 0  1 0 1 1
     (1/4*I)*Color(Nc^(-1)*(-1+Nc)*(1+Nc))*e^2*(2*t*dim^2+16*t+68*dim*u-12*t*dim-14*dim^2*u-104*u+dim^3*u)*g^4
    boxx23 3 11  3 2  1 1 -2 1
     (2*I)*Color(Nc^(-1)*(-1+Nc)*(1+Nc))*e^2*(-2+dim)*g^4*u^(-1)
    boxx23 3 11  3 1  1 1 -1 1
     -(2*I)*Color(Nc^(-1)*(-1+Nc)*(1+Nc))*e^2*(-2+dim-2*t*u^(-1))*g^4
    boxx23 3 11  3 0  1 1 0 1
     (1/4*I)*Color(Nc^(-1)*(-1+Nc)*(1+Nc))*t*e^2*(-120+2*t*dim^2*u^(-1)+68*dim+8*t*u^(-1)-8*t*dim*u^(-1)+dim^3-14*dim^2)*g^4
    boxx23 3 7  3 1  1 1 1 -1
     I*Color(Nc^(-1)*(-1+Nc)*(1+Nc))*e^2*(-2+dim)*g^4
    boxx23 3 7  3 0  1 1 1 0
     (1/4*I)*Color(Nc^(-1)*(-1+Nc)*(1+Nc))*e^2*(2*t*dim^2+16*t+68*dim*u-12*t*dim-14*dim^2*u-104*u+dim^3*u)*g^4
    boxx23 2 12  2 0  0 0 1 1
     -(1/4*I)*Color(Nc^(-1)*(-1+Nc)*(1+Nc))*e^2*(-104+68*dim+8*t*u^(-1)-4*t*dim*u^(-1)+dim^3-14*dim^2)*g^4
    boxx23 2 10  2 1  0 1 -1 1
     -(2*I)*Color(Nc^(-1)*(-1+Nc)*(1+Nc))*e^2*(-2+dim)*g^4*u^(-1)
    boxx23 2 10  2 0  0 1 0 1
     -(1/4*I)*Color(Nc^(-1)*(-1+Nc)*(1+Nc))*(208+14*t*dim^2*u^(-1)-t*dim^3*u^(-1)-136*dim+120*t*u^(-1)-68*t*dim*u^(-1)-2*dim^3+28*dim^2)*e^2*g^4
    boxx23 2 9  2 1  1 0 -1 1
     -(2*I)*Color(Nc^(-1)*(-1+Nc)*(1+Nc))*e^2*(-2+dim)*g^4*u^(-1)
    boxx23 2 9  2 0  1 0 0 1
     -I*Color(Nc^(-1)*(-1+Nc)*(1+Nc))*e^2*(-16+8*dim-2*t*u^(-1)+t*dim*u^(-1)-dim^2)*g^4
    boxx23 2 6  2 0  0 1 1 0
     -(1/4*I)*Color(Nc^(-1)*(-1+Nc)*(1+Nc))*e^2*(-104+68*dim+8*t*u^(-1)-4*t*dim*u^(-1)+dim^3-14*dim^2)*g^4
    boxx23 2 5  2 0  1 0 1 0
     (2*I)*Color(Nc^(-1)*(-1+Nc)*(1+Nc))*e^2*(-16+8*dim-dim^2)*g^4
    boxx23 2 3  2 1  1 1 -1 0
     -(2*I)*Color(Nc^(-1)*(-1+Nc)*(1+Nc))*e^2*(-2+dim)*g^4*u^(-1)
    boxx23 2 3  2 0  1 1 0 0
     -I*Color(Nc^(-1)*(-1+Nc)*(1+Nc))*e^2*(-16+8*dim-2*t*u^(-1)+t*dim*u^(-1)-dim^2)*g^4
    boxx23 1 8  1 0  0 0 0 1
     (2*I)*Color(Nc^(-1)*(-1+Nc)*(1+Nc))*e^2*(-2+dim)*g^4*u^(-1)
    boxx23 1 4  1 0  0 0 1 0
     -(2*I)*Color(Nc^(-1)*(-1+Nc)*(1+Nc))*e^2*(-2+dim)*g^4*u^(-1)
    boxx23 1 2  1 0  0 1 0 0
     (2*I)*Color(Nc^(-1)*(-1+Nc)*(1+Nc))*e^2*(-2+dim)*g^4*u^(-1)
    boxx23 1 1  1 0  1 0 0 0
     (2*I)*Color(Nc^(-1)*(-1+Nc)*(1+Nc))*e^2*(-2+dim)*g^4*u^(-1)
;
