{
(* sector mappings *)
ZeroSectors["tree"] -> {
},
SectorsWithoutGraph["tree"] -> {
},
SectorRelations["tree"] -> {

},
ZeroSectors["treex12"] -> {
},
SectorsWithoutGraph["treex12"] -> {
},
SectorRelations["treex12"] -> {
 {"treex12",0} -> {{"tree",0}, }
},
ZeroSectors["treex12x34"] -> {
},
SectorsWithoutGraph["treex12x34"] -> {
},
SectorRelations["treex12x34"] -> {
 {"treex12x34",0} -> {{"tree",0}, }
},
ZeroSectors["treex12x345"] -> {
},
SectorsWithoutGraph["treex12x345"] -> {
},
SectorRelations["treex12x345"] -> {
 {"treex12x345",0} -> {{"tree",0}, }
},
ZeroSectors["treex12x35"] -> {
},
SectorsWithoutGraph["treex12x35"] -> {
},
SectorRelations["treex12x35"] -> {
 {"treex12x35",0} -> {{"tree",0}, }
},
ZeroSectors["treex12x354"] -> {
},
SectorsWithoutGraph["treex12x354"] -> {
},
SectorRelations["treex12x354"] -> {
 {"treex12x354",0} -> {{"tree",0}, }
},
ZeroSectors["treex12x45"] -> {
},
SectorsWithoutGraph["treex12x45"] -> {
},
SectorRelations["treex12x45"] -> {
 {"treex12x45",0} -> {{"tree",0}, }
},
ZeroSectors["treex123"] -> {
},
SectorsWithoutGraph["treex123"] -> {
},
SectorRelations["treex123"] -> {
 {"treex123",0} -> {{"tree",0}, }
},
ZeroSectors["treex123x45"] -> {
},
SectorsWithoutGraph["treex123x45"] -> {
},
SectorRelations["treex123x45"] -> {
 {"treex123x45",0} -> {{"tree",0}, }
},
ZeroSectors["treex1234"] -> {
},
SectorsWithoutGraph["treex1234"] -> {
},
SectorRelations["treex1234"] -> {
 {"treex1234",0} -> {{"tree",0}, }
},
ZeroSectors["treex12345"] -> {
},
SectorsWithoutGraph["treex12345"] -> {
},
SectorRelations["treex12345"] -> {
 {"treex12345",0} -> {{"tree",0}, }
},
ZeroSectors["treex1235"] -> {
},
SectorsWithoutGraph["treex1235"] -> {
},
SectorRelations["treex1235"] -> {
 {"treex1235",0} -> {{"tree",0}, }
},
ZeroSectors["treex12354"] -> {
},
SectorsWithoutGraph["treex12354"] -> {
},
SectorRelations["treex12354"] -> {
 {"treex12354",0} -> {{"tree",0}, }
},
ZeroSectors["treex124"] -> {
},
SectorsWithoutGraph["treex124"] -> {
},
SectorRelations["treex124"] -> {
 {"treex124",0} -> {{"tree",0}, }
},
ZeroSectors["treex124x35"] -> {
},
SectorsWithoutGraph["treex124x35"] -> {
},
SectorRelations["treex124x35"] -> {
 {"treex124x35",0} -> {{"tree",0}, }
},
ZeroSectors["treex1243"] -> {
},
SectorsWithoutGraph["treex1243"] -> {
},
SectorRelations["treex1243"] -> {
 {"treex1243",0} -> {{"tree",0}, }
},
ZeroSectors["treex12435"] -> {
},
SectorsWithoutGraph["treex12435"] -> {
},
SectorRelations["treex12435"] -> {
 {"treex12435",0} -> {{"tree",0}, }
},
ZeroSectors["treex1245"] -> {
},
SectorsWithoutGraph["treex1245"] -> {
},
SectorRelations["treex1245"] -> {
 {"treex1245",0} -> {{"tree",0}, }
},
ZeroSectors["treex12453"] -> {
},
SectorsWithoutGraph["treex12453"] -> {
},
SectorRelations["treex12453"] -> {
 {"treex12453",0} -> {{"tree",0}, }
},
ZeroSectors["treex125"] -> {
},
SectorsWithoutGraph["treex125"] -> {
},
SectorRelations["treex125"] -> {
 {"treex125",0} -> {{"tree",0}, }
},
ZeroSectors["treex125x34"] -> {
},
SectorsWithoutGraph["treex125x34"] -> {
},
SectorRelations["treex125x34"] -> {
 {"treex125x34",0} -> {{"tree",0}, }
},
ZeroSectors["treex1253"] -> {
},
SectorsWithoutGraph["treex1253"] -> {
},
SectorRelations["treex1253"] -> {
 {"treex1253",0} -> {{"tree",0}, }
},
ZeroSectors["treex12534"] -> {
},
SectorsWithoutGraph["treex12534"] -> {
},
SectorRelations["treex12534"] -> {
 {"treex12534",0} -> {{"tree",0}, }
},
ZeroSectors["treex1254"] -> {
},
SectorsWithoutGraph["treex1254"] -> {
},
SectorRelations["treex1254"] -> {
 {"treex1254",0} -> {{"tree",0}, }
},
ZeroSectors["treex12543"] -> {
},
SectorsWithoutGraph["treex12543"] -> {
},
SectorRelations["treex12543"] -> {
 {"treex12543",0} -> {{"tree",0}, }
},
ZeroSectors["treex13"] -> {
},
SectorsWithoutGraph["treex13"] -> {
},
SectorRelations["treex13"] -> {
 {"treex13",0} -> {{"tree",0}, }
},
ZeroSectors["treex13x24"] -> {
},
SectorsWithoutGraph["treex13x24"] -> {
},
SectorRelations["treex13x24"] -> {
 {"treex13x24",0} -> {{"tree",0}, }
},
ZeroSectors["treex13x245"] -> {
},
SectorsWithoutGraph["treex13x245"] -> {
},
SectorRelations["treex13x245"] -> {
 {"treex13x245",0} -> {{"tree",0}, }
},
ZeroSectors["treex13x25"] -> {
},
SectorsWithoutGraph["treex13x25"] -> {
},
SectorRelations["treex13x25"] -> {
 {"treex13x25",0} -> {{"tree",0}, }
},
ZeroSectors["treex13x254"] -> {
},
SectorsWithoutGraph["treex13x254"] -> {
},
SectorRelations["treex13x254"] -> {
 {"treex13x254",0} -> {{"tree",0}, }
},
ZeroSectors["treex13x45"] -> {
},
SectorsWithoutGraph["treex13x45"] -> {
},
SectorRelations["treex13x45"] -> {
 {"treex13x45",0} -> {{"tree",0}, }
},
ZeroSectors["treex132"] -> {
},
SectorsWithoutGraph["treex132"] -> {
},
SectorRelations["treex132"] -> {
 {"treex132",0} -> {{"tree",0}, }
},
ZeroSectors["treex132x45"] -> {
},
SectorsWithoutGraph["treex132x45"] -> {
},
SectorRelations["treex132x45"] -> {
 {"treex132x45",0} -> {{"tree",0}, }
},
ZeroSectors["treex1324"] -> {
},
SectorsWithoutGraph["treex1324"] -> {
},
SectorRelations["treex1324"] -> {
 {"treex1324",0} -> {{"tree",0}, }
},
ZeroSectors["treex13245"] -> {
},
SectorsWithoutGraph["treex13245"] -> {
},
SectorRelations["treex13245"] -> {
 {"treex13245",0} -> {{"tree",0}, }
},
ZeroSectors["treex1325"] -> {
},
SectorsWithoutGraph["treex1325"] -> {
},
SectorRelations["treex1325"] -> {
 {"treex1325",0} -> {{"tree",0}, }
},
ZeroSectors["treex13254"] -> {
},
SectorsWithoutGraph["treex13254"] -> {
},
SectorRelations["treex13254"] -> {
 {"treex13254",0} -> {{"tree",0}, }
},
ZeroSectors["treex134"] -> {
},
SectorsWithoutGraph["treex134"] -> {
},
SectorRelations["treex134"] -> {
 {"treex134",0} -> {{"tree",0}, }
},
ZeroSectors["treex134x25"] -> {
},
SectorsWithoutGraph["treex134x25"] -> {
},
SectorRelations["treex134x25"] -> {
 {"treex134x25",0} -> {{"tree",0}, }
},
ZeroSectors["treex1342"] -> {
},
SectorsWithoutGraph["treex1342"] -> {
},
SectorRelations["treex1342"] -> {
 {"treex1342",0} -> {{"tree",0}, }
},
ZeroSectors["treex13425"] -> {
},
SectorsWithoutGraph["treex13425"] -> {
},
SectorRelations["treex13425"] -> {
 {"treex13425",0} -> {{"tree",0}, }
},
ZeroSectors["treex1345"] -> {
},
SectorsWithoutGraph["treex1345"] -> {
},
SectorRelations["treex1345"] -> {
 {"treex1345",0} -> {{"tree",0}, }
},
ZeroSectors["treex13452"] -> {
},
SectorsWithoutGraph["treex13452"] -> {
},
SectorRelations["treex13452"] -> {
 {"treex13452",0} -> {{"tree",0}, }
},
ZeroSectors["treex135"] -> {
},
SectorsWithoutGraph["treex135"] -> {
},
SectorRelations["treex135"] -> {
 {"treex135",0} -> {{"tree",0}, }
},
ZeroSectors["treex135x24"] -> {
},
SectorsWithoutGraph["treex135x24"] -> {
},
SectorRelations["treex135x24"] -> {
 {"treex135x24",0} -> {{"tree",0}, }
},
ZeroSectors["treex1352"] -> {
},
SectorsWithoutGraph["treex1352"] -> {
},
SectorRelations["treex1352"] -> {
 {"treex1352",0} -> {{"tree",0}, }
},
ZeroSectors["treex13524"] -> {
},
SectorsWithoutGraph["treex13524"] -> {
},
SectorRelations["treex13524"] -> {
 {"treex13524",0} -> {{"tree",0}, }
},
ZeroSectors["treex1354"] -> {
},
SectorsWithoutGraph["treex1354"] -> {
},
SectorRelations["treex1354"] -> {
 {"treex1354",0} -> {{"tree",0}, }
},
ZeroSectors["treex13542"] -> {
},
SectorsWithoutGraph["treex13542"] -> {
},
SectorRelations["treex13542"] -> {
 {"treex13542",0} -> {{"tree",0}, }
},
ZeroSectors["treex14"] -> {
},
SectorsWithoutGraph["treex14"] -> {
},
SectorRelations["treex14"] -> {
 {"treex14",0} -> {{"tree",0}, }
},
ZeroSectors["treex14x23"] -> {
},
SectorsWithoutGraph["treex14x23"] -> {
},
SectorRelations["treex14x23"] -> {
 {"treex14x23",0} -> {{"tree",0}, }
},
ZeroSectors["treex14x235"] -> {
},
SectorsWithoutGraph["treex14x235"] -> {
},
SectorRelations["treex14x235"] -> {
 {"treex14x235",0} -> {{"tree",0}, }
},
ZeroSectors["treex14x25"] -> {
},
SectorsWithoutGraph["treex14x25"] -> {
},
SectorRelations["treex14x25"] -> {
 {"treex14x25",0} -> {{"tree",0}, }
},
ZeroSectors["treex14x253"] -> {
},
SectorsWithoutGraph["treex14x253"] -> {
},
SectorRelations["treex14x253"] -> {
 {"treex14x253",0} -> {{"tree",0}, }
},
ZeroSectors["treex14x35"] -> {
},
SectorsWithoutGraph["treex14x35"] -> {
},
SectorRelations["treex14x35"] -> {
 {"treex14x35",0} -> {{"tree",0}, }
},
ZeroSectors["treex142"] -> {
},
SectorsWithoutGraph["treex142"] -> {
},
SectorRelations["treex142"] -> {
 {"treex142",0} -> {{"tree",0}, }
},
ZeroSectors["treex142x35"] -> {
},
SectorsWithoutGraph["treex142x35"] -> {
},
SectorRelations["treex142x35"] -> {
 {"treex142x35",0} -> {{"tree",0}, }
},
ZeroSectors["treex1423"] -> {
},
SectorsWithoutGraph["treex1423"] -> {
},
SectorRelations["treex1423"] -> {
 {"treex1423",0} -> {{"tree",0}, }
},
ZeroSectors["treex14235"] -> {
},
SectorsWithoutGraph["treex14235"] -> {
},
SectorRelations["treex14235"] -> {
 {"treex14235",0} -> {{"tree",0}, }
},
ZeroSectors["treex1425"] -> {
},
SectorsWithoutGraph["treex1425"] -> {
},
SectorRelations["treex1425"] -> {
 {"treex1425",0} -> {{"tree",0}, }
},
ZeroSectors["treex14253"] -> {
},
SectorsWithoutGraph["treex14253"] -> {
},
SectorRelations["treex14253"] -> {
 {"treex14253",0} -> {{"tree",0}, }
},
ZeroSectors["treex143"] -> {
},
SectorsWithoutGraph["treex143"] -> {
},
SectorRelations["treex143"] -> {
 {"treex143",0} -> {{"tree",0}, }
},
ZeroSectors["treex143x25"] -> {
},
SectorsWithoutGraph["treex143x25"] -> {
},
SectorRelations["treex143x25"] -> {
 {"treex143x25",0} -> {{"tree",0}, }
},
ZeroSectors["treex1432"] -> {
},
SectorsWithoutGraph["treex1432"] -> {
},
SectorRelations["treex1432"] -> {
 {"treex1432",0} -> {{"tree",0}, }
},
ZeroSectors["treex14325"] -> {
},
SectorsWithoutGraph["treex14325"] -> {
},
SectorRelations["treex14325"] -> {
 {"treex14325",0} -> {{"tree",0}, }
},
ZeroSectors["treex1435"] -> {
},
SectorsWithoutGraph["treex1435"] -> {
},
SectorRelations["treex1435"] -> {
 {"treex1435",0} -> {{"tree",0}, }
},
ZeroSectors["treex14352"] -> {
},
SectorsWithoutGraph["treex14352"] -> {
},
SectorRelations["treex14352"] -> {
 {"treex14352",0} -> {{"tree",0}, }
},
ZeroSectors["treex145"] -> {
},
SectorsWithoutGraph["treex145"] -> {
},
SectorRelations["treex145"] -> {
 {"treex145",0} -> {{"tree",0}, }
},
ZeroSectors["treex145x23"] -> {
},
SectorsWithoutGraph["treex145x23"] -> {
},
SectorRelations["treex145x23"] -> {
 {"treex145x23",0} -> {{"tree",0}, }
},
ZeroSectors["treex1452"] -> {
},
SectorsWithoutGraph["treex1452"] -> {
},
SectorRelations["treex1452"] -> {
 {"treex1452",0} -> {{"tree",0}, }
},
ZeroSectors["treex14523"] -> {
},
SectorsWithoutGraph["treex14523"] -> {
},
SectorRelations["treex14523"] -> {
 {"treex14523",0} -> {{"tree",0}, }
},
ZeroSectors["treex1453"] -> {
},
SectorsWithoutGraph["treex1453"] -> {
},
SectorRelations["treex1453"] -> {
 {"treex1453",0} -> {{"tree",0}, }
},
ZeroSectors["treex14532"] -> {
},
SectorsWithoutGraph["treex14532"] -> {
},
SectorRelations["treex14532"] -> {
 {"treex14532",0} -> {{"tree",0}, }
},
ZeroSectors["treex15"] -> {
},
SectorsWithoutGraph["treex15"] -> {
},
SectorRelations["treex15"] -> {
 {"treex15",0} -> {{"tree",0}, }
},
ZeroSectors["treex15x23"] -> {
},
SectorsWithoutGraph["treex15x23"] -> {
},
SectorRelations["treex15x23"] -> {
 {"treex15x23",0} -> {{"tree",0}, }
},
ZeroSectors["treex15x234"] -> {
},
SectorsWithoutGraph["treex15x234"] -> {
},
SectorRelations["treex15x234"] -> {
 {"treex15x234",0} -> {{"tree",0}, }
},
ZeroSectors["treex15x24"] -> {
},
SectorsWithoutGraph["treex15x24"] -> {
},
SectorRelations["treex15x24"] -> {
 {"treex15x24",0} -> {{"tree",0}, }
},
ZeroSectors["treex15x243"] -> {
},
SectorsWithoutGraph["treex15x243"] -> {
},
SectorRelations["treex15x243"] -> {
 {"treex15x243",0} -> {{"tree",0}, }
},
ZeroSectors["treex15x34"] -> {
},
SectorsWithoutGraph["treex15x34"] -> {
},
SectorRelations["treex15x34"] -> {
 {"treex15x34",0} -> {{"tree",0}, }
},
ZeroSectors["treex152"] -> {
},
SectorsWithoutGraph["treex152"] -> {
},
SectorRelations["treex152"] -> {
 {"treex152",0} -> {{"tree",0}, }
},
ZeroSectors["treex152x34"] -> {
},
SectorsWithoutGraph["treex152x34"] -> {
},
SectorRelations["treex152x34"] -> {
 {"treex152x34",0} -> {{"tree",0}, }
},
ZeroSectors["treex1523"] -> {
},
SectorsWithoutGraph["treex1523"] -> {
},
SectorRelations["treex1523"] -> {
 {"treex1523",0} -> {{"tree",0}, }
},
ZeroSectors["treex15234"] -> {
},
SectorsWithoutGraph["treex15234"] -> {
},
SectorRelations["treex15234"] -> {
 {"treex15234",0} -> {{"tree",0}, }
},
ZeroSectors["treex1524"] -> {
},
SectorsWithoutGraph["treex1524"] -> {
},
SectorRelations["treex1524"] -> {
 {"treex1524",0} -> {{"tree",0}, }
},
ZeroSectors["treex15243"] -> {
},
SectorsWithoutGraph["treex15243"] -> {
},
SectorRelations["treex15243"] -> {
 {"treex15243",0} -> {{"tree",0}, }
},
ZeroSectors["treex153"] -> {
},
SectorsWithoutGraph["treex153"] -> {
},
SectorRelations["treex153"] -> {
 {"treex153",0} -> {{"tree",0}, }
},
ZeroSectors["treex153x24"] -> {
},
SectorsWithoutGraph["treex153x24"] -> {
},
SectorRelations["treex153x24"] -> {
 {"treex153x24",0} -> {{"tree",0}, }
},
ZeroSectors["treex1532"] -> {
},
SectorsWithoutGraph["treex1532"] -> {
},
SectorRelations["treex1532"] -> {
 {"treex1532",0} -> {{"tree",0}, }
},
ZeroSectors["treex15324"] -> {
},
SectorsWithoutGraph["treex15324"] -> {
},
SectorRelations["treex15324"] -> {
 {"treex15324",0} -> {{"tree",0}, }
},
ZeroSectors["treex1534"] -> {
},
SectorsWithoutGraph["treex1534"] -> {
},
SectorRelations["treex1534"] -> {
 {"treex1534",0} -> {{"tree",0}, }
},
ZeroSectors["treex15342"] -> {
},
SectorsWithoutGraph["treex15342"] -> {
},
SectorRelations["treex15342"] -> {
 {"treex15342",0} -> {{"tree",0}, }
},
ZeroSectors["treex154"] -> {
},
SectorsWithoutGraph["treex154"] -> {
},
SectorRelations["treex154"] -> {
 {"treex154",0} -> {{"tree",0}, }
},
ZeroSectors["treex154x23"] -> {
},
SectorsWithoutGraph["treex154x23"] -> {
},
SectorRelations["treex154x23"] -> {
 {"treex154x23",0} -> {{"tree",0}, }
},
ZeroSectors["treex1542"] -> {
},
SectorsWithoutGraph["treex1542"] -> {
},
SectorRelations["treex1542"] -> {
 {"treex1542",0} -> {{"tree",0}, }
},
ZeroSectors["treex15423"] -> {
},
SectorsWithoutGraph["treex15423"] -> {
},
SectorRelations["treex15423"] -> {
 {"treex15423",0} -> {{"tree",0}, }
},
ZeroSectors["treex1543"] -> {
},
SectorsWithoutGraph["treex1543"] -> {
},
SectorRelations["treex1543"] -> {
 {"treex1543",0} -> {{"tree",0}, }
},
ZeroSectors["treex15432"] -> {
},
SectorsWithoutGraph["treex15432"] -> {
},
SectorRelations["treex15432"] -> {
 {"treex15432",0} -> {{"tree",0}, }
},
ZeroSectors["treex23"] -> {
},
SectorsWithoutGraph["treex23"] -> {
},
SectorRelations["treex23"] -> {
 {"treex23",0} -> {{"tree",0}, }
},
ZeroSectors["treex23x45"] -> {
},
SectorsWithoutGraph["treex23x45"] -> {
},
SectorRelations["treex23x45"] -> {
 {"treex23x45",0} -> {{"tree",0}, }
},
ZeroSectors["treex234"] -> {
},
SectorsWithoutGraph["treex234"] -> {
},
SectorRelations["treex234"] -> {
 {"treex234",0} -> {{"tree",0}, }
},
ZeroSectors["treex2345"] -> {
},
SectorsWithoutGraph["treex2345"] -> {
},
SectorRelations["treex2345"] -> {
 {"treex2345",0} -> {{"tree",0}, }
},
ZeroSectors["treex235"] -> {
},
SectorsWithoutGraph["treex235"] -> {
},
SectorRelations["treex235"] -> {
 {"treex235",0} -> {{"tree",0}, }
},
ZeroSectors["treex2354"] -> {
},
SectorsWithoutGraph["treex2354"] -> {
},
SectorRelations["treex2354"] -> {
 {"treex2354",0} -> {{"tree",0}, }
},
ZeroSectors["treex24"] -> {
},
SectorsWithoutGraph["treex24"] -> {
},
SectorRelations["treex24"] -> {
 {"treex24",0} -> {{"tree",0}, }
},
ZeroSectors["treex24x35"] -> {
},
SectorsWithoutGraph["treex24x35"] -> {
},
SectorRelations["treex24x35"] -> {
 {"treex24x35",0} -> {{"tree",0}, }
},
ZeroSectors["treex243"] -> {
},
SectorsWithoutGraph["treex243"] -> {
},
SectorRelations["treex243"] -> {
 {"treex243",0} -> {{"tree",0}, }
},
ZeroSectors["treex2435"] -> {
},
SectorsWithoutGraph["treex2435"] -> {
},
SectorRelations["treex2435"] -> {
 {"treex2435",0} -> {{"tree",0}, }
},
ZeroSectors["treex245"] -> {
},
SectorsWithoutGraph["treex245"] -> {
},
SectorRelations["treex245"] -> {
 {"treex245",0} -> {{"tree",0}, }
},
ZeroSectors["treex2453"] -> {
},
SectorsWithoutGraph["treex2453"] -> {
},
SectorRelations["treex2453"] -> {
 {"treex2453",0} -> {{"tree",0}, }
},
ZeroSectors["treex25"] -> {
},
SectorsWithoutGraph["treex25"] -> {
},
SectorRelations["treex25"] -> {
 {"treex25",0} -> {{"tree",0}, }
},
ZeroSectors["treex25x34"] -> {
},
SectorsWithoutGraph["treex25x34"] -> {
},
SectorRelations["treex25x34"] -> {
 {"treex25x34",0} -> {{"tree",0}, }
},
ZeroSectors["treex253"] -> {
},
SectorsWithoutGraph["treex253"] -> {
},
SectorRelations["treex253"] -> {
 {"treex253",0} -> {{"tree",0}, }
},
ZeroSectors["treex2534"] -> {
},
SectorsWithoutGraph["treex2534"] -> {
},
SectorRelations["treex2534"] -> {
 {"treex2534",0} -> {{"tree",0}, }
},
ZeroSectors["treex254"] -> {
},
SectorsWithoutGraph["treex254"] -> {
},
SectorRelations["treex254"] -> {
 {"treex254",0} -> {{"tree",0}, }
},
ZeroSectors["treex2543"] -> {
},
SectorsWithoutGraph["treex2543"] -> {
},
SectorRelations["treex2543"] -> {
 {"treex2543",0} -> {{"tree",0}, }
},
ZeroSectors["treex34"] -> {
},
SectorsWithoutGraph["treex34"] -> {
},
SectorRelations["treex34"] -> {
 {"treex34",0} -> {{"tree",0}, }
},
ZeroSectors["treex345"] -> {
},
SectorsWithoutGraph["treex345"] -> {
},
SectorRelations["treex345"] -> {
 {"treex345",0} -> {{"tree",0}, }
},
ZeroSectors["treex35"] -> {
},
SectorsWithoutGraph["treex35"] -> {
},
SectorRelations["treex35"] -> {
 {"treex35",0} -> {{"tree",0}, }
},
ZeroSectors["treex354"] -> {
},
SectorsWithoutGraph["treex354"] -> {
},
SectorRelations["treex354"] -> {
 {"treex354",0} -> {{"tree",0}, }
},
ZeroSectors["treex45"] -> {
},
SectorsWithoutGraph["treex45"] -> {
},
SectorRelations["treex45"] -> {
 {"treex45",0} -> {{"tree",0}, }
},
ZeroSectors["pentagon"] -> {
 {"pentagon",0}, {"pentagon",1}, {"pentagon",2}, {"pentagon",3}, {"pentagon",4}, {"pentagon",6}, {"pentagon",8}, {"pentagon",12}, {"pentagon",16}, {"pentagon",17}, 
 {"pentagon",24}
},
SectorsWithoutGraph["pentagon"] -> {
},
SectorRelations["pentagon"] -> {
 {"pentagon",2} -> {{"pentagon",1}, l->(l-p1)},
 {"pentagon",4} -> {{"pentagon",1}, l->(k+l-p1)},
 {"pentagon",6} -> {{"pentagonx15",3}, l->(k-l-p1)},
 {"pentagon",8} -> {{"pentagon",1}, l->(k+px+l-p1)},
 {"pentagon",9} -> {{"pentagonx12x345",5}, l->(k+px+l-p1)},
 {"pentagon",10} -> {{"pentagonx14",5}, l->(k+px-l-p1)},
 {"pentagon",12} -> {{"pentagonx14",3}, l->(k+px-l-p1)},
 {"pentagon",13} -> {{"pentagonx14",11}, l->(k+px-l-p1)},
 {"pentagon",14} -> {{"pentagonx14",7}, l->(k+px-l-p1)},
 {"pentagon",16} -> {{"pentagon",1}, l->(p2+l)},
 {"pentagon",17} -> {{"pentagonx12",3}, l->(p2+l)},
 {"pentagon",18} -> {{"pentagonx12345",5}, l->(p2+l)},
 {"pentagon",19} -> {{"pentagonx12345",7}, l->(p2+l)},
 {"pentagon",20} -> {{"pentagonx13x254",5}, l->(p2-l)},
 {"pentagon",21} -> {{"pentagonx12x35",11}, l->(-l)},
 {"pentagon",22} -> {{"pentagonx15x234",11}, l->(k-l-p1)},
 {"pentagon",23} -> {{"pentagonx12345",15}, l->(p2+l)},
 {"pentagon",24} -> {{"pentagonx13",3}, l->(p2-l)},
 {"pentagon",25} -> {{"pentagonx12x345",7}, l->(-l)},
 {"pentagon",26} -> {{"pentagonx13",11}, l->(p2-l)},
 {"pentagon",27} -> {{"pentagonx134x25",15}, l->(k+px+l-p1)},
 {"pentagon",28} -> {{"pentagonx13x254",7}, l->(p2-l)},
 {"pentagon",29} -> {{"pentagonx12x35",15}, l->(-l)},
 {"pentagon",30} -> {{"pentagonx13x45",15}, l->(p2-l)}
},
ZeroSectors["pentagonx12"] -> {
},
SectorsWithoutGraph["pentagonx12"] -> {
},
SectorRelations["pentagonx12"] -> {
 {"pentagonx12",1} -> {{"pentagon",1}, }
},
ZeroSectors["pentagonx12x34"] -> {
},
SectorsWithoutGraph["pentagonx12x34"] -> {
},
SectorRelations["pentagonx12x34"] -> {
 {"pentagonx12x34",1} -> {{"pentagon",1}, },
 {"pentagonx12x34",3} -> {{"pentagonx12",3}, l->(-p2-l)},
 {"pentagonx12x34",5} -> {{"pentagonx12",5}, l->(k-p2-l)},
 {"pentagonx12x34",7} -> {{"pentagonx12",7}, }
},
ZeroSectors["pentagonx12x345"] -> {
},
SectorsWithoutGraph["pentagonx12x345"] -> {
},
SectorRelations["pentagonx12x345"] -> {
 {"pentagonx12x345",1} -> {{"pentagon",1}, },
 {"pentagonx12x345",3} -> {{"pentagonx12",3}, l->(-p2-l)},
 {"pentagonx12x345",11} -> {{"pentagonx12x34",11}, }
},
ZeroSectors["pentagonx12x35"] -> {
},
SectorsWithoutGraph["pentagonx12x35"] -> {
},
SectorRelations["pentagonx12x35"] -> {
 {"pentagonx12x35",1} -> {{"pentagon",1}, },
 {"pentagonx12x35",3} -> {{"pentagonx12",3}, l->(-p2-l)},
 {"pentagonx12x35",5} -> {{"pentagonx12x345",5}, l->(-k-px-l+p1)},
 {"pentagonx12x35",7} -> {{"pentagonx12x345",7}, },
 {"pentagonx12x35",31} -> {{"pentagon",31}, l->(-l)}
},
ZeroSectors["pentagonx12x354"] -> {
},
SectorsWithoutGraph["pentagonx12x354"] -> {
},
SectorRelations["pentagonx12x354"] -> {
 {"pentagonx12x354",1} -> {{"pentagon",1}, },
 {"pentagonx12x354",3} -> {{"pentagonx12",3}, l->(-p2-l)},
 {"pentagonx12x354",11} -> {{"pentagonx12x35",11}, }
},
ZeroSectors["pentagonx12x45"] -> {
},
SectorsWithoutGraph["pentagonx12x45"] -> {
},
SectorRelations["pentagonx12x45"] -> {
 {"pentagonx12x45",1} -> {{"pentagon",1}, },
 {"pentagonx12x45",3} -> {{"pentagonx12",3}, l->(-p2-l)},
 {"pentagonx12x45",5} -> {{"pentagonx12x354",5}, l->(-p2+px-l)},
 {"pentagonx12x45",7} -> {{"pentagonx12x354",7}, },
 {"pentagonx12x45",11} -> {{"pentagonx12",11}, }
},
ZeroSectors["pentagonx123"] -> {
},
SectorsWithoutGraph["pentagonx123"] -> {
},
SectorRelations["pentagonx123"] -> {
 {"pentagonx123",1} -> {{"pentagon",1}, },
 {"pentagonx123",3} -> {{"pentagonx12",3}, l->(-p2-l)},
 {"pentagonx123",5} -> {{"pentagonx12",5}, l->(k-p2-l)},
 {"pentagonx123",7} -> {{"pentagonx12",7}, },
 {"pentagonx123",11} -> {{"pentagonx12",11}, },
 {"pentagonx123",15} -> {{"pentagonx12",15}, }
},
ZeroSectors["pentagonx123x45"] -> {
},
SectorsWithoutGraph["pentagonx123x45"] -> {
},
SectorRelations["pentagonx123x45"] -> {
 {"pentagonx123x45",1} -> {{"pentagon",1}, },
 {"pentagonx123x45",3} -> {{"pentagonx12",3}, l->(-p2-l)},
 {"pentagonx123x45",5} -> {{"pentagonx12x354",5}, l->(-p2+px-l)},
 {"pentagonx123x45",7} -> {{"pentagonx12x354",7}, },
 {"pentagonx123x45",11} -> {{"pentagonx12",11}, },
 {"pentagonx123x45",15} -> {{"pentagonx12x45",15}, }
},
ZeroSectors["pentagonx1234"] -> {
},
SectorsWithoutGraph["pentagonx1234"] -> {
},
SectorRelations["pentagonx1234"] -> {
 {"pentagonx1234",1} -> {{"pentagon",1}, },
 {"pentagonx1234",3} -> {{"pentagonx12",3}, l->(-p2-l)},
 {"pentagonx1234",5} -> {{"pentagonx12",5}, l->(k-p2-l)},
 {"pentagonx1234",7} -> {{"pentagonx12",7}, },
 {"pentagonx1234",11} -> {{"pentagonx12x35",11}, l->(-p2-l)}
},
ZeroSectors["pentagonx12345"] -> {
},
SectorsWithoutGraph["pentagonx12345"] -> {
},
SectorRelations["pentagonx12345"] -> {
 {"pentagonx12345",1} -> {{"pentagon",1}, },
 {"pentagonx12345",3} -> {{"pentagonx12",3}, l->(-p2-l)},
 {"pentagonx12345",11} -> {{"pentagonx12x35",11}, l->(-p2-l)},
 {"pentagonx12345",31} -> {{"pentagon",31}, l->(-p2+l)}
},
ZeroSectors["pentagonx1235"] -> {
},
SectorsWithoutGraph["pentagonx1235"] -> {
},
SectorRelations["pentagonx1235"] -> {
 {"pentagonx1235",1} -> {{"pentagon",1}, },
 {"pentagonx1235",3} -> {{"pentagonx12",3}, l->(-p2-l)},
 {"pentagonx1235",5} -> {{"pentagonx12345",5}, l->(-p2-l-p1)},
 {"pentagonx1235",7} -> {{"pentagonx12345",7}, },
 {"pentagonx1235",11} -> {{"pentagonx12x34",11}, l->(-p2-l)},
 {"pentagonx1235",31} -> {{"pentagonx12x345",31}, l->(-p2-l)}
},
ZeroSectors["pentagonx12354"] -> {
},
SectorsWithoutGraph["pentagonx12354"] -> {
},
SectorRelations["pentagonx12354"] -> {
 {"pentagonx12354",1} -> {{"pentagon",1}, },
 {"pentagonx12354",3} -> {{"pentagonx12",3}, l->(-p2-l)},
 {"pentagonx12354",5} -> {{"pentagonx12x354",5}, l->(-p2+px-l)},
 {"pentagonx12354",7} -> {{"pentagonx12x354",7}, },
 {"pentagonx12354",11} -> {{"pentagonx12x34",11}, l->(-p2-l)}
},
ZeroSectors["pentagonx124"] -> {
},
SectorsWithoutGraph["pentagonx124"] -> {
},
SectorRelations["pentagonx124"] -> {
 {"pentagonx124",1} -> {{"pentagon",1}, },
 {"pentagonx124",3} -> {{"pentagonx12",3}, l->(-p2-l)},
 {"pentagonx124",5} -> {{"pentagonx12",5}, l->(k-p2-l)},
 {"pentagonx124",7} -> {{"pentagonx12",7}, },
 {"pentagonx124",11} -> {{"pentagonx12x35",11}, l->(-p2-l)},
 {"pentagonx124",15} -> {{"pentagonx1234",15}, }
},
ZeroSectors["pentagonx124x35"] -> {
},
SectorsWithoutGraph["pentagonx124x35"] -> {
},
SectorRelations["pentagonx124x35"] -> {
 {"pentagonx124x35",1} -> {{"pentagon",1}, },
 {"pentagonx124x35",3} -> {{"pentagonx12",3}, l->(-p2-l)},
 {"pentagonx124x35",5} -> {{"pentagonx12x345",5}, l->(-k-px-l+p1)},
 {"pentagonx124x35",7} -> {{"pentagonx12x345",7}, },
 {"pentagonx124x35",11} -> {{"pentagonx12",11}, l->(-p2-l)},
 {"pentagonx124x35",31} -> {{"pentagonx123x45",31}, l->(-p2-l)}
},
ZeroSectors["pentagonx1243"] -> {
},
SectorsWithoutGraph["pentagonx1243"] -> {
},
SectorRelations["pentagonx1243"] -> {
 {"pentagonx1243",1} -> {{"pentagon",1}, },
 {"pentagonx1243",3} -> {{"pentagonx12",3}, l->(-p2-l)},
 {"pentagonx1243",5} -> {{"pentagonx12",5}, l->(k-p2-l)},
 {"pentagonx1243",7} -> {{"pentagonx12",7}, },
 {"pentagonx1243",11} -> {{"pentagonx12x34",11}, },
 {"pentagonx1243",15} -> {{"pentagonx12x34",15}, }
},
ZeroSectors["pentagonx12435"] -> {
},
SectorsWithoutGraph["pentagonx12435"] -> {
},
SectorRelations["pentagonx12435"] -> {
 {"pentagonx12435",1} -> {{"pentagon",1}, },
 {"pentagonx12435",3} -> {{"pentagonx12",3}, l->(-p2-l)},
 {"pentagonx12435",5} -> {{"pentagonx12345",5}, l->(-p2-l-p1)},
 {"pentagonx12435",7} -> {{"pentagonx12345",7}, },
 {"pentagonx12435",11} -> {{"pentagonx12",11}, l->(-p2-l)},
 {"pentagonx12435",31} -> {{"pentagonx12x45",31}, l->(-p2-l)}
},
ZeroSectors["pentagonx1245"] -> {
},
SectorsWithoutGraph["pentagonx1245"] -> {
},
SectorRelations["pentagonx1245"] -> {
 {"pentagonx1245",1} -> {{"pentagon",1}, },
 {"pentagonx1245",3} -> {{"pentagonx12",3}, l->(-p2-l)},
 {"pentagonx1245",5} -> {{"pentagonx12345",5}, l->(-p2-l-p1)},
 {"pentagonx1245",7} -> {{"pentagonx12345",7}, },
 {"pentagonx1245",11} -> {{"pentagonx12x35",11}, l->(-p2-l)},
 {"pentagonx1245",15} -> {{"pentagonx12345",15}, },
 {"pentagonx1245",31} -> {{"pentagonx12x354",31}, l->(-p2-l)}
},
ZeroSectors["pentagonx12453"] -> {
},
SectorsWithoutGraph["pentagonx12453"] -> {
},
SectorRelations["pentagonx12453"] -> {
 {"pentagonx12453",1} -> {{"pentagon",1}, },
 {"pentagonx12453",3} -> {{"pentagonx12",3}, l->(-p2-l)},
 {"pentagonx12453",5} -> {{"pentagonx12x345",5}, l->(-k-px-l+p1)},
 {"pentagonx12453",7} -> {{"pentagonx12x345",7}, },
 {"pentagonx12453",11} -> {{"pentagonx12x34",11}, },
 {"pentagonx12453",15} -> {{"pentagonx12x345",15}, },
 {"pentagonx12453",31} -> {{"pentagonx12354",31}, l->(-p2-l)}
},
ZeroSectors["pentagonx125"] -> {
},
SectorsWithoutGraph["pentagonx125"] -> {
},
SectorRelations["pentagonx125"] -> {
 {"pentagonx125",1} -> {{"pentagon",1}, },
 {"pentagonx125",3} -> {{"pentagonx12",3}, l->(-p2-l)},
 {"pentagonx125",5} -> {{"pentagonx12345",5}, l->(-p2-l-p1)},
 {"pentagonx125",7} -> {{"pentagonx12345",7}, },
 {"pentagonx125",11} -> {{"pentagonx12x34",11}, l->(-p2-l)},
 {"pentagonx125",15} -> {{"pentagonx1235",15}, },
 {"pentagonx125",31} -> {{"pentagonx12x34",31}, l->(-p2-l)}
},
ZeroSectors["pentagonx125x34"] -> {
},
SectorsWithoutGraph["pentagonx125x34"] -> {
},
SectorRelations["pentagonx125x34"] -> {
 {"pentagonx125x34",1} -> {{"pentagon",1}, },
 {"pentagonx125x34",3} -> {{"pentagonx12",3}, l->(-p2-l)},
 {"pentagonx125x34",5} -> {{"pentagonx12345",5}, l->(-p2-l-p1)},
 {"pentagonx125x34",7} -> {{"pentagonx12345",7}, },
 {"pentagonx125x34",11} -> {{"pentagonx12",11}, l->(-p2-l)},
 {"pentagonx125x34",15} -> {{"pentagonx12435",15}, },
 {"pentagonx125x34",31} -> {{"pentagonx12",31}, l->(-p2-l)}
},
ZeroSectors["pentagonx1253"] -> {
},
SectorsWithoutGraph["pentagonx1253"] -> {
},
SectorRelations["pentagonx1253"] -> {
 {"pentagonx1253",1} -> {{"pentagon",1}, },
 {"pentagonx1253",3} -> {{"pentagonx12",3}, l->(-p2-l)},
 {"pentagonx1253",5} -> {{"pentagonx12x345",5}, l->(-k-px-l+p1)},
 {"pentagonx1253",7} -> {{"pentagonx12x345",7}, },
 {"pentagonx1253",11} -> {{"pentagonx12x35",11}, },
 {"pentagonx1253",15} -> {{"pentagonx12x35",15}, },
 {"pentagonx1253",31} -> {{"pentagonx1234",31}, l->(-p2-l)}
},
ZeroSectors["pentagonx12534"] -> {
},
SectorsWithoutGraph["pentagonx12534"] -> {
},
SectorRelations["pentagonx12534"] -> {
 {"pentagonx12534",1} -> {{"pentagon",1}, },
 {"pentagonx12534",3} -> {{"pentagonx12",3}, l->(-p2-l)},
 {"pentagonx12534",5} -> {{"pentagonx12x345",5}, l->(-k-px-l+p1)},
 {"pentagonx12534",7} -> {{"pentagonx12x345",7}, },
 {"pentagonx12534",11} -> {{"pentagonx12",11}, l->(-p2-l)},
 {"pentagonx12534",15} -> {{"pentagonx124x35",15}, },
 {"pentagonx12534",31} -> {{"pentagonx123",31}, l->(-p2-l)}
},
ZeroSectors["pentagonx1254"] -> {
},
SectorsWithoutGraph["pentagonx1254"] -> {
},
SectorRelations["pentagonx1254"] -> {
 {"pentagonx1254",1} -> {{"pentagon",1}, },
 {"pentagonx1254",3} -> {{"pentagonx12",3}, l->(-p2-l)},
 {"pentagonx1254",5} -> {{"pentagonx12x354",5}, l->(-p2+px-l)},
 {"pentagonx1254",7} -> {{"pentagonx12x354",7}, },
 {"pentagonx1254",11} -> {{"pentagonx12x34",11}, l->(-p2-l)},
 {"pentagonx1254",15} -> {{"pentagonx12354",15}, },
 {"pentagonx1254",31} -> {{"pentagonx1243",31}, l->(-p2-l)}
},
ZeroSectors["pentagonx12543"] -> {
},
SectorsWithoutGraph["pentagonx12543"] -> {
},
SectorRelations["pentagonx12543"] -> {
 {"pentagonx12543",1} -> {{"pentagon",1}, },
 {"pentagonx12543",3} -> {{"pentagonx12",3}, l->(-p2-l)},
 {"pentagonx12543",5} -> {{"pentagonx12x354",5}, l->(-p2+px-l)},
 {"pentagonx12543",7} -> {{"pentagonx12x354",7}, },
 {"pentagonx12543",11} -> {{"pentagonx12x35",11}, },
 {"pentagonx12543",15} -> {{"pentagonx12x354",15}, },
 {"pentagonx12543",31} -> {{"pentagonx124",31}, l->(-p2-l)}
},
ZeroSectors["pentagonx13"] -> {
},
SectorsWithoutGraph["pentagonx13"] -> {
},
SectorRelations["pentagonx13"] -> {
 {"pentagonx13",1} -> {{"pentagon",1}, },
 {"pentagonx13",31} -> {{"pentagonx12x345",31}, l->(p2+l)}
},
ZeroSectors["pentagonx13x24"] -> {
},
SectorsWithoutGraph["pentagonx13x24"] -> {
},
SectorRelations["pentagonx13x24"] -> {
 {"pentagonx13x24",1} -> {{"pentagon",1}, },
 {"pentagonx13x24",3} -> {{"pentagonx13",3}, l->(-k+p2-px-l+p1)},
 {"pentagonx13x24",5} -> {{"pentagonx13",5}, l->(p2-px-l+p1)},
 {"pentagonx13x24",7} -> {{"pentagonx13",7}, },
 {"pentagonx13x24",15} -> {{"pentagonx12x34",15}, l->(-px-l+p1)},
 {"pentagonx13x24",31} -> {{"pentagonx12x34",31}, l->(-px-l+p1)}
},
ZeroSectors["pentagonx13x245"] -> {
},
SectorsWithoutGraph["pentagonx13x245"] -> {
},
SectorRelations["pentagonx13x245"] -> {
 {"pentagonx13x245",1} -> {{"pentagon",1}, },
 {"pentagonx13x245",3} -> {{"pentagonx13",3}, l->(-k+p2-px-l+p1)},
 {"pentagonx13x245",5} -> {{"pentagonx12x345",5}, l->(-k-px-l+p1)},
 {"pentagonx13x245",7} -> {{"pentagonx12x345",7}, l->(-k-px-l+p1)},
 {"pentagonx13x245",11} -> {{"pentagonx13x24",11}, },
 {"pentagonx13x245",31} -> {{"pentagonx1234",31}, l->(-k+p2-px+l+p1)}
},
ZeroSectors["pentagonx13x25"] -> {
},
SectorsWithoutGraph["pentagonx13x25"] -> {
},
SectorRelations["pentagonx13x25"] -> {
 {"pentagonx13x25",1} -> {{"pentagon",1}, },
 {"pentagonx13x25",3} -> {{"pentagonx13",3}, l->(-k+p2-px-l+p1)},
 {"pentagonx13x25",5} -> {{"pentagonx12x345",5}, l->(-k-px-l+p1)},
 {"pentagonx13x25",7} -> {{"pentagonx12x345",7}, l->(-k-px-l+p1)},
 {"pentagonx13x25",31} -> {{"pentagonx12354",31}, l->(-k+p2-px+l+p1)}
},
ZeroSectors["pentagonx13x254"] -> {
},
SectorsWithoutGraph["pentagonx13x254"] -> {
},
SectorRelations["pentagonx13x254"] -> {
 {"pentagonx13x254",1} -> {{"pentagon",1}, },
 {"pentagonx13x254",3} -> {{"pentagonx13",3}, l->(-k+p2-px-l+p1)},
 {"pentagonx13x254",11} -> {{"pentagonx13x25",11}, },
 {"pentagonx13x254",15} -> {{"pentagonx12x354",15}, l->(-k-l+p1)},
 {"pentagonx13x254",31} -> {{"pentagonx12x354",31}, l->(-k-l+p1)}
},
ZeroSectors["pentagonx13x45"] -> {
},
SectorsWithoutGraph["pentagonx13x45"] -> {
},
SectorRelations["pentagonx13x45"] -> {
 {"pentagonx13x45",1} -> {{"pentagon",1}, },
 {"pentagonx13x45",3} -> {{"pentagonx13",3}, l->(-k+p2-px-l+p1)},
 {"pentagonx13x45",5} -> {{"pentagonx13x254",5}, l->(-k+p2-l+p1)},
 {"pentagonx13x45",7} -> {{"pentagonx13x254",7}, },
 {"pentagonx13x45",11} -> {{"pentagonx13",11}, },
 {"pentagonx13x45",31} -> {{"pentagon",31}, l->(p2-l)}
},
ZeroSectors["pentagonx132"] -> {
},
SectorsWithoutGraph["pentagonx132"] -> {
},
SectorRelations["pentagonx132"] -> {
 {"pentagonx132",1} -> {{"pentagon",1}, },
 {"pentagonx132",3} -> {{"pentagonx13",3}, l->(-k+p2-px-l+p1)},
 {"pentagonx132",5} -> {{"pentagonx13",5}, l->(p2-px-l+p1)},
 {"pentagonx132",7} -> {{"pentagonx13",7}, },
 {"pentagonx132",11} -> {{"pentagonx13",11}, },
 {"pentagonx132",15} -> {{"pentagonx13",15}, },
 {"pentagonx132",31} -> {{"pentagonx12x45",31}, l->(-l+p1)}
},
ZeroSectors["pentagonx132x45"] -> {
},
SectorsWithoutGraph["pentagonx132x45"] -> {
},
SectorRelations["pentagonx132x45"] -> {
 {"pentagonx132x45",1} -> {{"pentagon",1}, },
 {"pentagonx132x45",3} -> {{"pentagonx13",3}, l->(-k+p2-px-l+p1)},
 {"pentagonx132x45",5} -> {{"pentagonx13x254",5}, l->(-k+p2-l+p1)},
 {"pentagonx132x45",7} -> {{"pentagonx13x254",7}, },
 {"pentagonx132x45",11} -> {{"pentagonx13",11}, },
 {"pentagonx132x45",15} -> {{"pentagonx13x45",15}, },
 {"pentagonx132x45",31} -> {{"pentagonx12",31}, l->(-l+p1)}
},
ZeroSectors["pentagonx1324"] -> {
},
SectorsWithoutGraph["pentagonx1324"] -> {
},
SectorRelations["pentagonx1324"] -> {
 {"pentagonx1324",1} -> {{"pentagon",1}, },
 {"pentagonx1324",3} -> {{"pentagonx13",3}, l->(-k+p2-px-l+p1)},
 {"pentagonx1324",5} -> {{"pentagonx13",5}, l->(p2-px-l+p1)},
 {"pentagonx1324",7} -> {{"pentagonx13",7}, },
 {"pentagonx1324",11} -> {{"pentagonx13x25",11}, l->(-k+p2-px-l+p1)},
 {"pentagonx1324",31} -> {{"pentagonx12x354",31}, l->(p2-px+l)}
},
ZeroSectors["pentagonx13245"] -> {
},
SectorsWithoutGraph["pentagonx13245"] -> {
},
SectorRelations["pentagonx13245"] -> {
 {"pentagonx13245",1} -> {{"pentagon",1}, },
 {"pentagonx13245",3} -> {{"pentagonx13",3}, l->(-k+p2-px-l+p1)},
 {"pentagonx13245",11} -> {{"pentagonx13x25",11}, l->(-k+p2-px-l+p1)},
 {"pentagonx13245",31} -> {{"pentagonx124",31}, l->(-px-l)}
},
ZeroSectors["pentagonx1325"] -> {
},
SectorsWithoutGraph["pentagonx1325"] -> {
},
SectorRelations["pentagonx1325"] -> {
 {"pentagonx1325",1} -> {{"pentagon",1}, },
 {"pentagonx1325",3} -> {{"pentagonx13",3}, l->(-k+p2-px-l+p1)},
 {"pentagonx1325",5} -> {{"pentagonx13245",5}, l->(-k+p2-px-l)},
 {"pentagonx1325",7} -> {{"pentagonx13245",7}, },
 {"pentagonx1325",11} -> {{"pentagonx13x24",11}, l->(-k+p2-px-l+p1)},
 {"pentagonx1325",31} -> {{"pentagonx1243",31}, l->(-k+p2+l)}
},
ZeroSectors["pentagonx13254"] -> {
},
SectorsWithoutGraph["pentagonx13254"] -> {
},
SectorRelations["pentagonx13254"] -> {
 {"pentagonx13254",1} -> {{"pentagon",1}, },
 {"pentagonx13254",3} -> {{"pentagonx13",3}, l->(-k+p2-px-l+p1)},
 {"pentagonx13254",5} -> {{"pentagonx13x254",5}, l->(-k+p2-l+p1)},
 {"pentagonx13254",7} -> {{"pentagonx13x254",7}, },
 {"pentagonx13254",11} -> {{"pentagonx13x24",11}, l->(-k+p2-px-l+p1)},
 {"pentagonx13254",31} -> {{"pentagonx12x34",31}, l->(-k+p2+l)}
},
ZeroSectors["pentagonx134"] -> {
},
SectorsWithoutGraph["pentagonx134"] -> {
},
SectorRelations["pentagonx134"] -> {
 {"pentagonx134",1} -> {{"pentagon",1}, },
 {"pentagonx134",3} -> {{"pentagonx13",3}, l->(-k+p2-px-l+p1)},
 {"pentagonx134",5} -> {{"pentagonx13",5}, l->(p2-px-l+p1)},
 {"pentagonx134",7} -> {{"pentagonx13",7}, },
 {"pentagonx134",11} -> {{"pentagonx13x25",11}, l->(-k+p2-px-l+p1)},
 {"pentagonx134",15} -> {{"pentagonx1324",15}, },
 {"pentagonx134",31} -> {{"pentagonx12354",31}, l->(-l)}
},
ZeroSectors["pentagonx134x25"] -> {
},
SectorsWithoutGraph["pentagonx134x25"] -> {
},
SectorRelations["pentagonx134x25"] -> {
 {"pentagonx134x25",1} -> {{"pentagon",1}, },
 {"pentagonx134x25",3} -> {{"pentagonx13",3}, l->(-k+p2-px-l+p1)},
 {"pentagonx134x25",5} -> {{"pentagonx12x345",5}, l->(-k-px-l+p1)},
 {"pentagonx134x25",7} -> {{"pentagonx12x345",7}, l->(-k-px-l+p1)},
 {"pentagonx134x25",11} -> {{"pentagonx13",11}, l->(-k+p2-px-l+p1)},
 {"pentagonx134x25",31} -> {{"pentagonx12x345",31}, l->(-k-px-l+p1)}
},
ZeroSectors["pentagonx1342"] -> {
},
SectorsWithoutGraph["pentagonx1342"] -> {
},
SectorRelations["pentagonx1342"] -> {
 {"pentagonx1342",1} -> {{"pentagon",1}, },
 {"pentagonx1342",3} -> {{"pentagonx13",3}, l->(-k+p2-px-l+p1)},
 {"pentagonx1342",5} -> {{"pentagonx13",5}, l->(p2-px-l+p1)},
 {"pentagonx1342",7} -> {{"pentagonx13",7}, },
 {"pentagonx1342",11} -> {{"pentagonx13x24",11}, },
 {"pentagonx1342",15} -> {{"pentagonx12x34",15}, l->(-px-l+p1)},
 {"pentagonx1342",31} -> {{"pentagonx1243",31}, l->(-px-l+p1)}
},
ZeroSectors["pentagonx13425"] -> {
},
SectorsWithoutGraph["pentagonx13425"] -> {
},
SectorRelations["pentagonx13425"] -> {
 {"pentagonx13425",1} -> {{"pentagon",1}, },
 {"pentagonx13425",3} -> {{"pentagonx13",3}, l->(-k+p2-px-l+p1)},
 {"pentagonx13425",5} -> {{"pentagonx13245",5}, l->(-k+p2-px-l)},
 {"pentagonx13425",7} -> {{"pentagonx13245",7}, },
 {"pentagonx13425",11} -> {{"pentagonx13",11}, l->(-k+p2-px-l+p1)},
 {"pentagonx13425",15} -> {{"pentagonx12435",15}, l->(-k-px-l)},
 {"pentagonx13425",31} -> {{"pentagonx12x45",31}, l->(-k+p2-px+l)}
},
ZeroSectors["pentagonx1345"] -> {
},
SectorsWithoutGraph["pentagonx1345"] -> {
},
SectorRelations["pentagonx1345"] -> {
 {"pentagonx1345",1} -> {{"pentagon",1}, },
 {"pentagonx1345",3} -> {{"pentagonx13",3}, l->(-k+p2-px-l+p1)},
 {"pentagonx1345",5} -> {{"pentagonx13245",5}, l->(-k+p2-px-l)},
 {"pentagonx1345",7} -> {{"pentagonx13245",7}, },
 {"pentagonx1345",11} -> {{"pentagonx13x25",11}, l->(-k+p2-px-l+p1)},
 {"pentagonx1345",15} -> {{"pentagonx13245",15}, },
 {"pentagonx1345",31} -> {{"pentagonx123x45",31}, l->(-l)}
},
ZeroSectors["pentagonx13452"] -> {
},
SectorsWithoutGraph["pentagonx13452"] -> {
},
SectorRelations["pentagonx13452"] -> {
 {"pentagonx13452",1} -> {{"pentagon",1}, },
 {"pentagonx13452",3} -> {{"pentagonx13",3}, l->(-k+p2-px-l+p1)},
 {"pentagonx13452",5} -> {{"pentagonx12x345",5}, l->(-k-px-l+p1)},
 {"pentagonx13452",7} -> {{"pentagonx12x345",7}, l->(-k-px-l+p1)},
 {"pentagonx13452",11} -> {{"pentagonx13x24",11}, },
 {"pentagonx13452",15} -> {{"pentagonx13x245",15}, },
 {"pentagonx13452",31} -> {{"pentagonx123",31}, l->(-k+p2-px+l+p1)}
},
ZeroSectors["pentagonx135"] -> {
},
SectorsWithoutGraph["pentagonx135"] -> {
},
SectorRelations["pentagonx135"] -> {
 {"pentagonx135",1} -> {{"pentagon",1}, },
 {"pentagonx135",3} -> {{"pentagonx13",3}, l->(-k+p2-px-l+p1)},
 {"pentagonx135",5} -> {{"pentagonx13245",5}, l->(-k+p2-px-l)},
 {"pentagonx135",7} -> {{"pentagonx13245",7}, },
 {"pentagonx135",11} -> {{"pentagonx13x24",11}, l->(-k+p2-px-l+p1)},
 {"pentagonx135",15} -> {{"pentagonx1325",15}, },
 {"pentagonx135",31} -> {{"pentagonx123",31}, l->(-l)}
},
ZeroSectors["pentagonx135x24"] -> {
},
SectorsWithoutGraph["pentagonx135x24"] -> {
},
SectorRelations["pentagonx135x24"] -> {
 {"pentagonx135x24",1} -> {{"pentagon",1}, },
 {"pentagonx135x24",3} -> {{"pentagonx13",3}, l->(-k+p2-px-l+p1)},
 {"pentagonx135x24",5} -> {{"pentagonx13245",5}, l->(-k+p2-px-l)},
 {"pentagonx135x24",7} -> {{"pentagonx13245",7}, },
 {"pentagonx135x24",11} -> {{"pentagonx13",11}, l->(-k+p2-px-l+p1)},
 {"pentagonx135x24",15} -> {{"pentagonx12435",15}, l->(-k-px-l)},
 {"pentagonx135x24",31} -> {{"pentagonx12",31}, l->(-k+p2-px+l)}
},
ZeroSectors["pentagonx1352"] -> {
},
SectorsWithoutGraph["pentagonx1352"] -> {
},
SectorRelations["pentagonx1352"] -> {
 {"pentagonx1352",1} -> {{"pentagon",1}, },
 {"pentagonx1352",3} -> {{"pentagonx13",3}, l->(-k+p2-px-l+p1)},
 {"pentagonx1352",5} -> {{"pentagonx12x345",5}, l->(-k-px-l+p1)},
 {"pentagonx1352",7} -> {{"pentagonx12x345",7}, l->(-k-px-l+p1)},
 {"pentagonx1352",11} -> {{"pentagonx13x25",11}, },
 {"pentagonx1352",15} -> {{"pentagonx13x25",15}, },
 {"pentagonx1352",31} -> {{"pentagonx123x45",31}, l->(-k+p2-px+l+p1)}
},
ZeroSectors["pentagonx13524"] -> {
},
SectorsWithoutGraph["pentagonx13524"] -> {
},
SectorRelations["pentagonx13524"] -> {
 {"pentagonx13524",1} -> {{"pentagon",1}, },
 {"pentagonx13524",3} -> {{"pentagonx13",3}, l->(-k+p2-px-l+p1)},
 {"pentagonx13524",5} -> {{"pentagonx12x345",5}, l->(-k-px-l+p1)},
 {"pentagonx13524",7} -> {{"pentagonx12x345",7}, l->(-k-px-l+p1)},
 {"pentagonx13524",11} -> {{"pentagonx13",11}, l->(-k+p2-px-l+p1)},
 {"pentagonx13524",15} -> {{"pentagonx134x25",15}, },
 {"pentagonx13524",31} -> {{"pentagon",31}, l->(-k-px+l+p1)}
},
ZeroSectors["pentagonx1354"] -> {
},
SectorsWithoutGraph["pentagonx1354"] -> {
},
SectorRelations["pentagonx1354"] -> {
 {"pentagonx1354",1} -> {{"pentagon",1}, },
 {"pentagonx1354",3} -> {{"pentagonx13",3}, l->(-k+p2-px-l+p1)},
 {"pentagonx1354",5} -> {{"pentagonx13x254",5}, l->(-k+p2-l+p1)},
 {"pentagonx1354",7} -> {{"pentagonx13x254",7}, },
 {"pentagonx1354",11} -> {{"pentagonx13x24",11}, l->(-k+p2-px-l+p1)},
 {"pentagonx1354",15} -> {{"pentagonx13254",15}, },
 {"pentagonx1354",31} -> {{"pentagonx1234",31}, l->(-l)}
},
ZeroSectors["pentagonx13542"] -> {
},
SectorsWithoutGraph["pentagonx13542"] -> {
},
SectorRelations["pentagonx13542"] -> {
 {"pentagonx13542",1} -> {{"pentagon",1}, },
 {"pentagonx13542",3} -> {{"pentagonx13",3}, l->(-k+p2-px-l+p1)},
 {"pentagonx13542",5} -> {{"pentagonx13x254",5}, l->(-k+p2-l+p1)},
 {"pentagonx13542",7} -> {{"pentagonx13x254",7}, },
 {"pentagonx13542",11} -> {{"pentagonx13x25",11}, },
 {"pentagonx13542",15} -> {{"pentagonx12x354",15}, l->(-k-l+p1)},
 {"pentagonx13542",31} -> {{"pentagonx124",31}, l->(-k+p2+l+p1)}
},
ZeroSectors["pentagonx14"] -> {
},
SectorsWithoutGraph["pentagonx14"] -> {
},
SectorRelations["pentagonx14"] -> {
 {"pentagonx14",1} -> {{"pentagon",1}, },
 {"pentagonx14",15} -> {{"pentagon",15}, l->(k+px-l-p1)},
 {"pentagonx14",31} -> {{"pentagonx123x45",31}, l->(p2+l)}
},
ZeroSectors["pentagonx14x23"] -> {
},
SectorsWithoutGraph["pentagonx14x23"] -> {
},
SectorRelations["pentagonx14x23"] -> {
 {"pentagonx14x23",1} -> {{"pentagon",1}, },
 {"pentagonx14x23",3} -> {{"pentagonx14",3}, l->(px-l)},
 {"pentagonx14x23",5} -> {{"pentagonx14",5}, l->(k+px-l)},
 {"pentagonx14x23",7} -> {{"pentagonx14",7}, },
 {"pentagonx14x23",11} -> {{"pentagonx14",11}, },
 {"pentagonx14x23",15} -> {{"pentagon",15}, l->(k+px-l-p1)},
 {"pentagonx14x23",31} -> {{"pentagon",31}, l->(k+px-l-p1)}
},
ZeroSectors["pentagonx14x235"] -> {
},
SectorsWithoutGraph["pentagonx14x235"] -> {
},
SectorRelations["pentagonx14x235"] -> {
 {"pentagonx14x235",1} -> {{"pentagon",1}, },
 {"pentagonx14x235",3} -> {{"pentagonx14",3}, l->(px-l)},
 {"pentagonx14x235",5} -> {{"pentagonx12x354",5}, l->(-p2+px-l)},
 {"pentagonx14x235",7} -> {{"pentagonx12x354",7}, l->(-p2+px-l)},
 {"pentagonx14x235",31} -> {{"pentagonx12x354",31}, l->(-p2+px-l)}
},
ZeroSectors["pentagonx14x25"] -> {
},
SectorsWithoutGraph["pentagonx14x25"] -> {
},
SectorRelations["pentagonx14x25"] -> {
 {"pentagonx14x25",1} -> {{"pentagon",1}, },
 {"pentagonx14x25",3} -> {{"pentagonx14",3}, l->(px-l)},
 {"pentagonx14x25",5} -> {{"pentagonx12x354",5}, l->(-p2+px-l)},
 {"pentagonx14x25",7} -> {{"pentagonx12x354",7}, l->(-p2+px-l)},
 {"pentagonx14x25",11} -> {{"pentagonx14x235",11}, },
 {"pentagonx14x25",15} -> {{"pentagonx14x235",15}, },
 {"pentagonx14x25",31} -> {{"pentagonx12x45",31}, l->(-p2+px-l)}
},
ZeroSectors["pentagonx14x253"] -> {
},
SectorsWithoutGraph["pentagonx14x253"] -> {
},
SectorRelations["pentagonx14x253"] -> {
 {"pentagonx14x253",1} -> {{"pentagon",1}, },
 {"pentagonx14x253",3} -> {{"pentagonx14",3}, l->(px-l)},
 {"pentagonx14x253",5} -> {{"pentagonx13x254",5}, l->(-k+p2-l+p1)},
 {"pentagonx14x253",7} -> {{"pentagonx13x254",7}, l->(-k+p2-l+p1)},
 {"pentagonx14x253",31} -> {{"pentagonx12",31}, l->(-k+p2+l)}
},
ZeroSectors["pentagonx14x35"] -> {
},
SectorsWithoutGraph["pentagonx14x35"] -> {
},
SectorRelations["pentagonx14x35"] -> {
 {"pentagonx14x35",1} -> {{"pentagon",1}, },
 {"pentagonx14x35",3} -> {{"pentagonx14",3}, l->(px-l)},
 {"pentagonx14x35",5} -> {{"pentagonx13x254",5}, l->(-k+p2-l+p1)},
 {"pentagonx14x35",7} -> {{"pentagonx13x254",7}, l->(-k+p2-l+p1)},
 {"pentagonx14x35",11} -> {{"pentagonx14x253",11}, },
 {"pentagonx14x35",15} -> {{"pentagonx14x253",15}, },
 {"pentagonx14x35",31} -> {{"pentagonx124",31}, l->(-l)}
},
ZeroSectors["pentagonx142"] -> {
},
SectorsWithoutGraph["pentagonx142"] -> {
},
SectorRelations["pentagonx142"] -> {
 {"pentagonx142",1} -> {{"pentagon",1}, },
 {"pentagonx142",3} -> {{"pentagonx14",3}, l->(px-l)},
 {"pentagonx142",5} -> {{"pentagonx14",5}, l->(k+px-l)},
 {"pentagonx142",7} -> {{"pentagonx14",7}, },
 {"pentagonx142",11} -> {{"pentagonx14x253",11}, l->(px-l)},
 {"pentagonx142",15} -> {{"pentagonx12",15}, l->(k-p2+px-l)},
 {"pentagonx142",31} -> {{"pentagonx123",31}, l->(k-p2+px-l)}
},
ZeroSectors["pentagonx142x35"] -> {
},
SectorsWithoutGraph["pentagonx142x35"] -> {
},
SectorRelations["pentagonx142x35"] -> {
 {"pentagonx142x35",1} -> {{"pentagon",1}, },
 {"pentagonx142x35",3} -> {{"pentagonx14",3}, l->(px-l)},
 {"pentagonx142x35",5} -> {{"pentagonx13x254",5}, l->(-k+p2-l+p1)},
 {"pentagonx142x35",7} -> {{"pentagonx13x254",7}, l->(-k+p2-l+p1)},
 {"pentagonx142x35",11} -> {{"pentagonx14",11}, l->(px-l)},
 {"pentagonx142x35",15} -> {{"pentagonx12x35",15}, l->(-k-l+p1)},
 {"pentagonx142x35",31} -> {{"pentagonx1234",31}, l->(-k+p2+l+p1)}
},
ZeroSectors["pentagonx1423"] -> {
},
SectorsWithoutGraph["pentagonx1423"] -> {
},
SectorRelations["pentagonx1423"] -> {
 {"pentagonx1423",1} -> {{"pentagon",1}, },
 {"pentagonx1423",3} -> {{"pentagonx14",3}, l->(px-l)},
 {"pentagonx1423",5} -> {{"pentagonx14",5}, l->(k+px-l)},
 {"pentagonx1423",7} -> {{"pentagonx14",7}, },
 {"pentagonx1423",11} -> {{"pentagonx14x253",11}, l->(px-l)},
 {"pentagonx1423",15} -> {{"pentagonx12",15}, l->(k-p2+px-l)},
 {"pentagonx1423",31} -> {{"pentagonx12",31}, l->(k-p2+px-l)}
},
ZeroSectors["pentagonx14235"] -> {
},
SectorsWithoutGraph["pentagonx14235"] -> {
},
SectorRelations["pentagonx14235"] -> {
 {"pentagonx14235",1} -> {{"pentagon",1}, },
 {"pentagonx14235",3} -> {{"pentagonx14",3}, l->(px-l)},
 {"pentagonx14235",11} -> {{"pentagonx14x235",11}, },
 {"pentagonx14235",15} -> {{"pentagonx1235",15}, l->(-p2+px-l-p1)},
 {"pentagonx14235",31} -> {{"pentagonx12x34",31}, l->(px+l-p1)}
},
ZeroSectors["pentagonx1425"] -> {
},
SectorsWithoutGraph["pentagonx1425"] -> {
},
SectorRelations["pentagonx1425"] -> {
 {"pentagonx1425",1} -> {{"pentagon",1}, },
 {"pentagonx1425",3} -> {{"pentagonx14",3}, l->(px-l)},
 {"pentagonx1425",5} -> {{"pentagonx14235",5}, l->(px-l-p1)},
 {"pentagonx1425",7} -> {{"pentagonx14235",7}, },
 {"pentagonx1425",11} -> {{"pentagonx14x235",11}, },
 {"pentagonx1425",15} -> {{"pentagonx1235",15}, l->(-p2+px-l-p1)},
 {"pentagonx1425",31} -> {{"pentagonx12x345",31}, l->(px+l-p1)}
},
ZeroSectors["pentagonx14253"] -> {
},
SectorsWithoutGraph["pentagonx14253"] -> {
},
SectorRelations["pentagonx14253"] -> {
 {"pentagonx14253",1} -> {{"pentagon",1}, },
 {"pentagonx14253",3} -> {{"pentagonx14",3}, l->(px-l)},
 {"pentagonx14253",5} -> {{"pentagonx13x254",5}, l->(-k+p2-l+p1)},
 {"pentagonx14253",7} -> {{"pentagonx13x254",7}, l->(-k+p2-l+p1)},
 {"pentagonx14253",11} -> {{"pentagonx14",11}, l->(px-l)},
 {"pentagonx14253",15} -> {{"pentagonx12x35",15}, l->(-k-l+p1)},
 {"pentagonx14253",31} -> {{"pentagon",31}, l->(-k+l+p1)}
},
ZeroSectors["pentagonx143"] -> {
},
SectorsWithoutGraph["pentagonx143"] -> {
},
SectorRelations["pentagonx143"] -> {
 {"pentagonx143",1} -> {{"pentagon",1}, },
 {"pentagonx143",3} -> {{"pentagonx14",3}, l->(px-l)},
 {"pentagonx143",5} -> {{"pentagonx14",5}, l->(k+px-l)},
 {"pentagonx143",7} -> {{"pentagonx14",7}, },
 {"pentagonx143",11} -> {{"pentagonx14x235",11}, l->(px-l)},
 {"pentagonx143",15} -> {{"pentagonx13",15}, l->(p2-l+p1)},
 {"pentagonx143",31} -> {{"pentagonx12x45",31}, l->(p2+l)}
},
ZeroSectors["pentagonx143x25"] -> {
},
SectorsWithoutGraph["pentagonx143x25"] -> {
},
SectorRelations["pentagonx143x25"] -> {
 {"pentagonx143x25",1} -> {{"pentagon",1}, },
 {"pentagonx143x25",3} -> {{"pentagonx14",3}, l->(px-l)},
 {"pentagonx143x25",5} -> {{"pentagonx12x354",5}, l->(-p2+px-l)},
 {"pentagonx143x25",7} -> {{"pentagonx12x354",7}, l->(-p2+px-l)},
 {"pentagonx143x25",11} -> {{"pentagonx14",11}, l->(px-l)},
 {"pentagonx143x25",15} -> {{"pentagonx13x25",15}, l->(-k-l+p1)},
 {"pentagonx143x25",31} -> {{"pentagonx123x45",31}, l->(-p2+px-l)}
},
ZeroSectors["pentagonx1432"] -> {
},
SectorsWithoutGraph["pentagonx1432"] -> {
},
SectorRelations["pentagonx1432"] -> {
 {"pentagonx1432",1} -> {{"pentagon",1}, },
 {"pentagonx1432",3} -> {{"pentagonx14",3}, l->(px-l)},
 {"pentagonx1432",5} -> {{"pentagonx14",5}, l->(k+px-l)},
 {"pentagonx1432",7} -> {{"pentagonx14",7}, },
 {"pentagonx1432",11} -> {{"pentagonx14x235",11}, l->(px-l)},
 {"pentagonx1432",15} -> {{"pentagonx13",15}, l->(p2-l+p1)},
 {"pentagonx1432",31} -> {{"pentagonx12x345",31}, l->(-l+p1)}
},
ZeroSectors["pentagonx14325"] -> {
},
SectorsWithoutGraph["pentagonx14325"] -> {
},
SectorRelations["pentagonx14325"] -> {
 {"pentagonx14325",1} -> {{"pentagon",1}, },
 {"pentagonx14325",3} -> {{"pentagonx14",3}, l->(px-l)},
 {"pentagonx14325",5} -> {{"pentagonx14235",5}, l->(px-l-p1)},
 {"pentagonx14325",7} -> {{"pentagonx14235",7}, },
 {"pentagonx14325",11} -> {{"pentagonx14x253",11}, },
 {"pentagonx14325",15} -> {{"pentagonx1325",15}, l->(-k+p2-l)},
 {"pentagonx14325",31} -> {{"pentagonx123",31}, l->(-k+p2+l)}
},
ZeroSectors["pentagonx1435"] -> {
},
SectorsWithoutGraph["pentagonx1435"] -> {
},
SectorRelations["pentagonx1435"] -> {
 {"pentagonx1435",1} -> {{"pentagon",1}, },
 {"pentagonx1435",3} -> {{"pentagonx14",3}, l->(px-l)},
 {"pentagonx1435",5} -> {{"pentagonx14235",5}, l->(px-l-p1)},
 {"pentagonx1435",7} -> {{"pentagonx14235",7}, },
 {"pentagonx1435",11} -> {{"pentagonx14x253",11}, },
 {"pentagonx1435",15} -> {{"pentagonx1325",15}, l->(-k+p2-l)},
 {"pentagonx1435",31} -> {{"pentagonx1243",31}, l->(-l)}
},
ZeroSectors["pentagonx14352"] -> {
},
SectorsWithoutGraph["pentagonx14352"] -> {
},
SectorRelations["pentagonx14352"] -> {
 {"pentagonx14352",1} -> {{"pentagon",1}, },
 {"pentagonx14352",3} -> {{"pentagonx14",3}, l->(px-l)},
 {"pentagonx14352",5} -> {{"pentagonx12x354",5}, l->(-p2+px-l)},
 {"pentagonx14352",7} -> {{"pentagonx12x354",7}, l->(-p2+px-l)},
 {"pentagonx14352",11} -> {{"pentagonx14",11}, l->(px-l)},
 {"pentagonx14352",15} -> {{"pentagonx13x25",15}, l->(-k-l+p1)},
 {"pentagonx14352",31} -> {{"pentagonx12354",31}, l->(-p2+px-l)}
},
ZeroSectors["pentagonx145"] -> {
},
SectorsWithoutGraph["pentagonx145"] -> {
},
SectorRelations["pentagonx145"] -> {
 {"pentagonx145",1} -> {{"pentagon",1}, },
 {"pentagonx145",3} -> {{"pentagonx14",3}, l->(px-l)},
 {"pentagonx145",5} -> {{"pentagonx14235",5}, l->(px-l-p1)},
 {"pentagonx145",7} -> {{"pentagonx14235",7}, },
 {"pentagonx145",11} -> {{"pentagonx14",11}, },
 {"pentagonx145",31} -> {{"pentagonx12354",31}, l->(p2+l)}
},
ZeroSectors["pentagonx145x23"] -> {
},
SectorsWithoutGraph["pentagonx145x23"] -> {
},
SectorRelations["pentagonx145x23"] -> {
 {"pentagonx145x23",1} -> {{"pentagon",1}, },
 {"pentagonx145x23",3} -> {{"pentagonx14",3}, l->(px-l)},
 {"pentagonx145x23",5} -> {{"pentagonx14235",5}, l->(px-l-p1)},
 {"pentagonx145x23",7} -> {{"pentagonx14235",7}, },
 {"pentagonx145x23",11} -> {{"pentagonx14",11}, },
 {"pentagonx145x23",15} -> {{"pentagonx145",15}, },
 {"pentagonx145x23",31} -> {{"pentagonx1234",31}, l->(k-p2+px-l-p1)}
},
ZeroSectors["pentagonx1452"] -> {
},
SectorsWithoutGraph["pentagonx1452"] -> {
},
SectorRelations["pentagonx1452"] -> {
 {"pentagonx1452",1} -> {{"pentagon",1}, },
 {"pentagonx1452",3} -> {{"pentagonx14",3}, l->(px-l)},
 {"pentagonx1452",5} -> {{"pentagonx12x354",5}, l->(-p2+px-l)},
 {"pentagonx1452",7} -> {{"pentagonx12x354",7}, l->(-p2+px-l)},
 {"pentagonx1452",11} -> {{"pentagonx14x253",11}, l->(px-l)},
 {"pentagonx1452",31} -> {{"pentagonx1243",31}, l->(px+l)}
},
ZeroSectors["pentagonx14523"] -> {
},
SectorsWithoutGraph["pentagonx14523"] -> {
},
SectorRelations["pentagonx14523"] -> {
 {"pentagonx14523",1} -> {{"pentagon",1}, },
 {"pentagonx14523",3} -> {{"pentagonx14",3}, l->(px-l)},
 {"pentagonx14523",5} -> {{"pentagonx12x354",5}, l->(-p2+px-l)},
 {"pentagonx14523",7} -> {{"pentagonx12x354",7}, l->(-p2+px-l)},
 {"pentagonx14523",11} -> {{"pentagonx14x253",11}, l->(px-l)},
 {"pentagonx14523",15} -> {{"pentagonx1452",15}, },
 {"pentagonx14523",31} -> {{"pentagonx124",31}, l->(px+l)}
},
ZeroSectors["pentagonx1453"] -> {
},
SectorsWithoutGraph["pentagonx1453"] -> {
},
SectorRelations["pentagonx1453"] -> {
 {"pentagonx1453",1} -> {{"pentagon",1}, },
 {"pentagonx1453",3} -> {{"pentagonx14",3}, l->(px-l)},
 {"pentagonx1453",5} -> {{"pentagonx13x254",5}, l->(-k+p2-l+p1)},
 {"pentagonx1453",7} -> {{"pentagonx13x254",7}, l->(-k+p2-l+p1)},
 {"pentagonx1453",11} -> {{"pentagonx14x235",11}, l->(px-l)},
 {"pentagonx1453",31} -> {{"pentagonx12x354",31}, l->(p2+l)}
},
ZeroSectors["pentagonx14532"] -> {
},
SectorsWithoutGraph["pentagonx14532"] -> {
},
SectorRelations["pentagonx14532"] -> {
 {"pentagonx14532",1} -> {{"pentagon",1}, },
 {"pentagonx14532",3} -> {{"pentagonx14",3}, l->(px-l)},
 {"pentagonx14532",5} -> {{"pentagonx13x254",5}, l->(-k+p2-l+p1)},
 {"pentagonx14532",7} -> {{"pentagonx13x254",7}, l->(-k+p2-l+p1)},
 {"pentagonx14532",11} -> {{"pentagonx14x235",11}, l->(px-l)},
 {"pentagonx14532",15} -> {{"pentagonx1453",15}, },
 {"pentagonx14532",31} -> {{"pentagonx12x34",31}, l->(-l+p1)}
},
ZeroSectors["pentagonx15"] -> {
},
SectorsWithoutGraph["pentagonx15"] -> {
},
SectorRelations["pentagonx15"] -> {
 {"pentagonx15",1} -> {{"pentagon",1}, },
 {"pentagonx15",5} -> {{"pentagon",5}, l->(k-l-p1)},
 {"pentagonx15",7} -> {{"pentagon",7}, l->(k-l-p1)},
 {"pentagonx15",15} -> {{"pentagonx145",15}, l->(k+px-l-p1)},
 {"pentagonx15",31} -> {{"pentagonx1234",31}, l->(p2+l)}
},
ZeroSectors["pentagonx15x23"] -> {
},
SectorsWithoutGraph["pentagonx15x23"] -> {
},
SectorRelations["pentagonx15x23"] -> {
 {"pentagonx15x23",1} -> {{"pentagon",1}, },
 {"pentagonx15x23",3} -> {{"pentagonx15",3}, l->(k-l)},
 {"pentagonx15x23",5} -> {{"pentagon",5}, l->(k-l-p1)},
 {"pentagonx15x23",7} -> {{"pentagon",7}, l->(k-l-p1)},
 {"pentagonx15x23",11} -> {{"pentagonx15",11}, },
 {"pentagonx15x23",15} -> {{"pentagonx145",15}, l->(k+px-l-p1)},
 {"pentagonx15x23",31} -> {{"pentagonx12354",31}, l->(k-p2+px-l-p1)}
},
ZeroSectors["pentagonx15x234"] -> {
},
SectorsWithoutGraph["pentagonx15x234"] -> {
},
SectorRelations["pentagonx15x234"] -> {
 {"pentagonx15x234",1} -> {{"pentagon",1}, },
 {"pentagonx15x234",3} -> {{"pentagonx15",3}, l->(k-l)},
 {"pentagonx15x234",5} -> {{"pentagon",5}, l->(k-l-p1)},
 {"pentagonx15x234",7} -> {{"pentagon",7}, l->(k-l-p1)},
 {"pentagonx15x234",15} -> {{"pentagonx12345",15}, l->(k-p2-l-p1)},
 {"pentagonx15x234",31} -> {{"pentagonx12x354",31}, l->(k+l-p1)}
},
ZeroSectors["pentagonx15x24"] -> {
},
SectorsWithoutGraph["pentagonx15x24"] -> {
},
SectorRelations["pentagonx15x24"] -> {
 {"pentagonx15x24",1} -> {{"pentagon",1}, },
 {"pentagonx15x24",3} -> {{"pentagonx15",3}, l->(k-l)},
 {"pentagonx15x24",5} -> {{"pentagon",5}, l->(k-l-p1)},
 {"pentagonx15x24",7} -> {{"pentagon",7}, l->(k-l-p1)},
 {"pentagonx15x24",11} -> {{"pentagonx15x234",11}, },
 {"pentagonx15x24",15} -> {{"pentagonx12345",15}, l->(k-p2-l-p1)},
 {"pentagonx15x24",31} -> {{"pentagon",31}, l->(k-l-p1)}
},
ZeroSectors["pentagonx15x243"] -> {
},
SectorsWithoutGraph["pentagonx15x243"] -> {
},
SectorRelations["pentagonx15x243"] -> {
 {"pentagonx15x243",1} -> {{"pentagon",1}, },
 {"pentagonx15x243",3} -> {{"pentagonx15",3}, l->(k-l)},
 {"pentagonx15x243",5} -> {{"pentagon",5}, l->(k-l-p1)},
 {"pentagonx15x243",7} -> {{"pentagon",7}, l->(k-l-p1)},
 {"pentagonx15x243",15} -> {{"pentagonx13245",15}, l->(p2-px-l)},
 {"pentagonx15x243",31} -> {{"pentagonx123x45",31}, l->(p2-px+l)}
},
ZeroSectors["pentagonx15x34"] -> {
},
SectorsWithoutGraph["pentagonx15x34"] -> {
},
SectorRelations["pentagonx15x34"] -> {
 {"pentagonx15x34",1} -> {{"pentagon",1}, },
 {"pentagonx15x34",3} -> {{"pentagonx15",3}, l->(k-l)},
 {"pentagonx15x34",5} -> {{"pentagon",5}, l->(k-l-p1)},
 {"pentagonx15x34",7} -> {{"pentagon",7}, l->(k-l-p1)},
 {"pentagonx15x34",11} -> {{"pentagonx15x243",11}, },
 {"pentagonx15x34",15} -> {{"pentagonx13245",15}, l->(p2-px-l)},
 {"pentagonx15x34",31} -> {{"pentagonx124",31}, l->(p2+l)}
},
ZeroSectors["pentagonx152"] -> {
},
SectorsWithoutGraph["pentagonx152"] -> {
},
SectorRelations["pentagonx152"] -> {
 {"pentagonx152",1} -> {{"pentagon",1}, },
 {"pentagonx152",3} -> {{"pentagonx15",3}, l->(k-l)},
 {"pentagonx152",5} -> {{"pentagonx12",5}, l->(k-p2-l)},
 {"pentagonx152",7} -> {{"pentagonx12",7}, l->(k-p2-l)},
 {"pentagonx152",11} -> {{"pentagonx15x243",11}, l->(k-l)},
 {"pentagonx152",15} -> {{"pentagonx1452",15}, l->(k-p2+px-l)},
 {"pentagonx152",31} -> {{"pentagonx124",31}, l->(k-p2-l)}
},
ZeroSectors["pentagonx152x34"] -> {
},
SectorsWithoutGraph["pentagonx152x34"] -> {
},
SectorRelations["pentagonx152x34"] -> {
 {"pentagonx152x34",1} -> {{"pentagon",1}, },
 {"pentagonx152x34",3} -> {{"pentagonx15",3}, l->(k-l)},
 {"pentagonx152x34",5} -> {{"pentagonx12",5}, l->(k-p2-l)},
 {"pentagonx152x34",7} -> {{"pentagonx12",7}, l->(k-p2-l)},
 {"pentagonx152x34",11} -> {{"pentagonx15",11}, l->(k-l)},
 {"pentagonx152x34",15} -> {{"pentagonx13x245",15}, l->(-px-l+p1)},
 {"pentagonx152x34",31} -> {{"pentagonx1234",31}, l->(k-p2-l)}
},
ZeroSectors["pentagonx1523"] -> {
},
SectorsWithoutGraph["pentagonx1523"] -> {
},
SectorRelations["pentagonx1523"] -> {
 {"pentagonx1523",1} -> {{"pentagon",1}, },
 {"pentagonx1523",3} -> {{"pentagonx15",3}, l->(k-l)},
 {"pentagonx1523",5} -> {{"pentagonx12",5}, l->(k-p2-l)},
 {"pentagonx1523",7} -> {{"pentagonx12",7}, l->(k-p2-l)},
 {"pentagonx1523",11} -> {{"pentagonx15x243",11}, l->(k-l)},
 {"pentagonx1523",15} -> {{"pentagonx1452",15}, l->(k-p2+px-l)},
 {"pentagonx1523",31} -> {{"pentagonx1243",31}, l->(k-p2-l)}
},
ZeroSectors["pentagonx15234"] -> {
},
SectorsWithoutGraph["pentagonx15234"] -> {
},
SectorRelations["pentagonx15234"] -> {
 {"pentagonx15234",1} -> {{"pentagon",1}, },
 {"pentagonx15234",3} -> {{"pentagonx15",3}, l->(k-l)},
 {"pentagonx15234",5} -> {{"pentagonx12",5}, l->(k-p2-l)},
 {"pentagonx15234",7} -> {{"pentagonx12",7}, l->(k-p2-l)},
 {"pentagonx15234",11} -> {{"pentagonx15x234",11}, },
 {"pentagonx15234",31} -> {{"pentagonx12x34",31}, l->(k-p2-l)}
},
ZeroSectors["pentagonx1524"] -> {
},
SectorsWithoutGraph["pentagonx1524"] -> {
},
SectorRelations["pentagonx1524"] -> {
 {"pentagonx1524",1} -> {{"pentagon",1}, },
 {"pentagonx1524",3} -> {{"pentagonx15",3}, l->(k-l)},
 {"pentagonx1524",5} -> {{"pentagonx12",5}, l->(k-p2-l)},
 {"pentagonx1524",7} -> {{"pentagonx12",7}, l->(k-p2-l)},
 {"pentagonx1524",11} -> {{"pentagonx15x234",11}, },
 {"pentagonx1524",15} -> {{"pentagonx15234",15}, },
 {"pentagonx1524",31} -> {{"pentagonx12",31}, l->(k-p2-l)}
},
ZeroSectors["pentagonx15243"] -> {
},
SectorsWithoutGraph["pentagonx15243"] -> {
},
SectorRelations["pentagonx15243"] -> {
 {"pentagonx15243",1} -> {{"pentagon",1}, },
 {"pentagonx15243",3} -> {{"pentagonx15",3}, l->(k-l)},
 {"pentagonx15243",5} -> {{"pentagonx12",5}, l->(k-p2-l)},
 {"pentagonx15243",7} -> {{"pentagonx12",7}, l->(k-p2-l)},
 {"pentagonx15243",11} -> {{"pentagonx15",11}, l->(k-l)},
 {"pentagonx15243",15} -> {{"pentagonx13x245",15}, l->(-px-l+p1)},
 {"pentagonx15243",31} -> {{"pentagonx123",31}, l->(k-p2-l)}
},
ZeroSectors["pentagonx153"] -> {
},
SectorsWithoutGraph["pentagonx153"] -> {
},
SectorRelations["pentagonx153"] -> {
 {"pentagonx153",1} -> {{"pentagon",1}, },
 {"pentagonx153",3} -> {{"pentagonx15",3}, l->(k-l)},
 {"pentagonx153",5} -> {{"pentagonx13",5}, l->(p2-px-l+p1)},
 {"pentagonx153",7} -> {{"pentagonx13",7}, l->(p2-px-l+p1)},
 {"pentagonx153",11} -> {{"pentagonx15x234",11}, l->(k-l)},
 {"pentagonx153",15} -> {{"pentagonx1453",15}, l->(p2-l+p1)},
 {"pentagonx153",31} -> {{"pentagonx12x34",31}, l->(p2+l)}
},
ZeroSectors["pentagonx153x24"] -> {
},
SectorsWithoutGraph["pentagonx153x24"] -> {
},
SectorRelations["pentagonx153x24"] -> {
 {"pentagonx153x24",1} -> {{"pentagon",1}, },
 {"pentagonx153x24",3} -> {{"pentagonx15",3}, l->(k-l)},
 {"pentagonx153x24",5} -> {{"pentagonx13",5}, l->(p2-px-l+p1)},
 {"pentagonx153x24",7} -> {{"pentagonx13",7}, l->(p2-px-l+p1)},
 {"pentagonx153x24",11} -> {{"pentagonx15",11}, l->(k-l)},
 {"pentagonx153x24",15} -> {{"pentagonx12x345",15}, l->(-px-l+p1)},
 {"pentagonx153x24",31} -> {{"pentagonx12x345",31}, l->(-px-l+p1)}
},
ZeroSectors["pentagonx1532"] -> {
},
SectorsWithoutGraph["pentagonx1532"] -> {
},
SectorRelations["pentagonx1532"] -> {
 {"pentagonx1532",1} -> {{"pentagon",1}, },
 {"pentagonx1532",3} -> {{"pentagonx15",3}, l->(k-l)},
 {"pentagonx1532",5} -> {{"pentagonx13",5}, l->(p2-px-l+p1)},
 {"pentagonx1532",7} -> {{"pentagonx13",7}, l->(p2-px-l+p1)},
 {"pentagonx1532",11} -> {{"pentagonx15x234",11}, l->(k-l)},
 {"pentagonx1532",15} -> {{"pentagonx1453",15}, l->(p2-l+p1)},
 {"pentagonx1532",31} -> {{"pentagonx12x354",31}, l->(-l+p1)}
},
ZeroSectors["pentagonx15324"] -> {
},
SectorsWithoutGraph["pentagonx15324"] -> {
},
SectorRelations["pentagonx15324"] -> {
 {"pentagonx15324",1} -> {{"pentagon",1}, },
 {"pentagonx15324",3} -> {{"pentagonx15",3}, l->(k-l)},
 {"pentagonx15324",5} -> {{"pentagonx13",5}, l->(p2-px-l+p1)},
 {"pentagonx15324",7} -> {{"pentagonx13",7}, l->(p2-px-l+p1)},
 {"pentagonx15324",11} -> {{"pentagonx15x243",11}, },
 {"pentagonx15324",31} -> {{"pentagonx12x45",31}, l->(p2-px+l)}
},
ZeroSectors["pentagonx1534"] -> {
},
SectorsWithoutGraph["pentagonx1534"] -> {
},
SectorRelations["pentagonx1534"] -> {
 {"pentagonx1534",1} -> {{"pentagon",1}, },
 {"pentagonx1534",3} -> {{"pentagonx15",3}, l->(k-l)},
 {"pentagonx1534",5} -> {{"pentagonx13",5}, l->(p2-px-l+p1)},
 {"pentagonx1534",7} -> {{"pentagonx13",7}, l->(p2-px-l+p1)},
 {"pentagonx1534",11} -> {{"pentagonx15x243",11}, },
 {"pentagonx1534",15} -> {{"pentagonx15324",15}, },
 {"pentagonx1534",31} -> {{"pentagonx1243",31}, l->(p2+l)}
},
ZeroSectors["pentagonx15342"] -> {
},
SectorsWithoutGraph["pentagonx15342"] -> {
},
SectorRelations["pentagonx15342"] -> {
 {"pentagonx15342",1} -> {{"pentagon",1}, },
 {"pentagonx15342",3} -> {{"pentagonx15",3}, l->(k-l)},
 {"pentagonx15342",5} -> {{"pentagonx13",5}, l->(p2-px-l+p1)},
 {"pentagonx15342",7} -> {{"pentagonx13",7}, l->(p2-px-l+p1)},
 {"pentagonx15342",11} -> {{"pentagonx15",11}, l->(k-l)},
 {"pentagonx15342",15} -> {{"pentagonx12x345",15}, l->(-px-l+p1)},
 {"pentagonx15342",31} -> {{"pentagonx12354",31}, l->(p2-px+l+p1)}
},
ZeroSectors["pentagonx154"] -> {
},
SectorsWithoutGraph["pentagonx154"] -> {
},
SectorRelations["pentagonx154"] -> {
 {"pentagonx154",1} -> {{"pentagon",1}, },
 {"pentagonx154",3} -> {{"pentagonx15",3}, l->(k-l)},
 {"pentagonx154",5} -> {{"pentagonx14",5}, l->(k+px-l)},
 {"pentagonx154",7} -> {{"pentagonx14",7}, l->(k+px-l)},
 {"pentagonx154",11} -> {{"pentagonx15",11}, },
 {"pentagonx154",31} -> {{"pentagonx123",31}, l->(p2+l)}
},
ZeroSectors["pentagonx154x23"] -> {
},
SectorsWithoutGraph["pentagonx154x23"] -> {
},
SectorRelations["pentagonx154x23"] -> {
 {"pentagonx154x23",1} -> {{"pentagon",1}, },
 {"pentagonx154x23",3} -> {{"pentagonx15",3}, l->(k-l)},
 {"pentagonx154x23",5} -> {{"pentagonx14",5}, l->(k+px-l)},
 {"pentagonx154x23",7} -> {{"pentagonx14",7}, l->(k+px-l)},
 {"pentagonx154x23",11} -> {{"pentagonx15",11}, },
 {"pentagonx154x23",15} -> {{"pentagonx154",15}, },
 {"pentagonx154x23",31} -> {{"pentagonx12x345",31}, l->(k+px+l-p1)}
},
ZeroSectors["pentagonx1542"] -> {
},
SectorsWithoutGraph["pentagonx1542"] -> {
},
SectorRelations["pentagonx1542"] -> {
 {"pentagonx1542",1} -> {{"pentagon",1}, },
 {"pentagonx1542",3} -> {{"pentagonx15",3}, l->(k-l)},
 {"pentagonx1542",5} -> {{"pentagonx14",5}, l->(k+px-l)},
 {"pentagonx1542",7} -> {{"pentagonx14",7}, l->(k+px-l)},
 {"pentagonx1542",11} -> {{"pentagonx15x243",11}, l->(k-l)},
 {"pentagonx1542",15} -> {{"pentagonx12x45",15}, l->(k-p2+px-l)},
 {"pentagonx1542",31} -> {{"pentagonx123x45",31}, l->(k-p2+px-l)}
},
ZeroSectors["pentagonx15423"] -> {
},
SectorsWithoutGraph["pentagonx15423"] -> {
},
SectorRelations["pentagonx15423"] -> {
 {"pentagonx15423",1} -> {{"pentagon",1}, },
 {"pentagonx15423",3} -> {{"pentagonx15",3}, l->(k-l)},
 {"pentagonx15423",5} -> {{"pentagonx14",5}, l->(k+px-l)},
 {"pentagonx15423",7} -> {{"pentagonx14",7}, l->(k+px-l)},
 {"pentagonx15423",11} -> {{"pentagonx15x243",11}, l->(k-l)},
 {"pentagonx15423",15} -> {{"pentagonx12x45",15}, l->(k-p2+px-l)},
 {"pentagonx15423",31} -> {{"pentagonx12x45",31}, l->(k-p2+px-l)}
},
ZeroSectors["pentagonx1543"] -> {
},
SectorsWithoutGraph["pentagonx1543"] -> {
},
SectorRelations["pentagonx1543"] -> {
 {"pentagonx1543",1} -> {{"pentagon",1}, },
 {"pentagonx1543",3} -> {{"pentagonx15",3}, l->(k-l)},
 {"pentagonx1543",5} -> {{"pentagonx14",5}, l->(k+px-l)},
 {"pentagonx1543",7} -> {{"pentagonx14",7}, l->(k+px-l)},
 {"pentagonx1543",11} -> {{"pentagonx15x234",11}, l->(k-l)},
 {"pentagonx1543",15} -> {{"pentagonx13x45",15}, l->(p2-l+p1)},
 {"pentagonx1543",31} -> {{"pentagonx12",31}, l->(p2+l)}
},
ZeroSectors["pentagonx15432"] -> {
},
SectorsWithoutGraph["pentagonx15432"] -> {
},
SectorRelations["pentagonx15432"] -> {
 {"pentagonx15432",1} -> {{"pentagon",1}, },
 {"pentagonx15432",3} -> {{"pentagonx15",3}, l->(k-l)},
 {"pentagonx15432",5} -> {{"pentagonx14",5}, l->(k+px-l)},
 {"pentagonx15432",7} -> {{"pentagonx14",7}, l->(k+px-l)},
 {"pentagonx15432",11} -> {{"pentagonx15x234",11}, l->(k-l)},
 {"pentagonx15432",15} -> {{"pentagonx13x45",15}, l->(p2-l+p1)},
 {"pentagonx15432",31} -> {{"pentagon",31}, l->(l+p1)}
},
ZeroSectors["pentagonx23"] -> {
},
SectorsWithoutGraph["pentagonx23"] -> {
},
SectorRelations["pentagonx23"] -> {
 {"pentagonx23",1} -> {{"pentagon",1}, },
 {"pentagonx23",3} -> {{"pentagon",3}, l->(-l-p1)},
 {"pentagonx23",5} -> {{"pentagon",5}, l->(k-l-p1)},
 {"pentagonx23",7} -> {{"pentagon",7}, },
 {"pentagonx23",11} -> {{"pentagon",11}, },
 {"pentagonx23",15} -> {{"pentagon",15}, },
 {"pentagonx23",31} -> {{"pentagonx123x45",31}, l->(k-p2+px-l-p1)}
},
ZeroSectors["pentagonx23x45"] -> {
},
SectorsWithoutGraph["pentagonx23x45"] -> {
},
SectorRelations["pentagonx23x45"] -> {
 {"pentagonx23x45",1} -> {{"pentagon",1}, },
 {"pentagonx23x45",3} -> {{"pentagon",3}, l->(-l-p1)},
 {"pentagonx23x45",5} -> {{"pentagonx14235",5}, l->(px-l-p1)},
 {"pentagonx23x45",7} -> {{"pentagonx14235",7}, l->(px-l-p1)},
 {"pentagonx23x45",11} -> {{"pentagon",11}, },
 {"pentagonx23x45",15} -> {{"pentagonx154",15}, l->(k+px-l-p1)},
 {"pentagonx23x45",31} -> {{"pentagonx123",31}, l->(k-p2+px-l-p1)}
},
ZeroSectors["pentagonx234"] -> {
},
SectorsWithoutGraph["pentagonx234"] -> {
},
SectorRelations["pentagonx234"] -> {
 {"pentagonx234",1} -> {{"pentagon",1}, },
 {"pentagonx234",3} -> {{"pentagon",3}, l->(-l-p1)},
 {"pentagonx234",5} -> {{"pentagon",5}, l->(k-l-p1)},
 {"pentagonx234",7} -> {{"pentagon",7}, },
 {"pentagonx234",15} -> {{"pentagonx1234",15}, l->(k-p2-l-p1)},
 {"pentagonx234",31} -> {{"pentagonx124",31}, l->(k-p2-l-p1)}
},
ZeroSectors["pentagonx2345"] -> {
},
SectorsWithoutGraph["pentagonx2345"] -> {
},
SectorRelations["pentagonx2345"] -> {
 {"pentagonx2345",1} -> {{"pentagon",1}, },
 {"pentagonx2345",3} -> {{"pentagon",3}, l->(-l-p1)},
 {"pentagonx2345",5} -> {{"pentagonx12345",5}, l->(-p2-l-p1)},
 {"pentagonx2345",7} -> {{"pentagonx12345",7}, l->(-p2-l-p1)},
 {"pentagonx2345",11} -> {{"pentagonx234",11}, },
 {"pentagonx2345",15} -> {{"pentagonx15234",15}, l->(k-p2-l-p1)},
 {"pentagonx2345",31} -> {{"pentagonx12",31}, l->(l-p1)}
},
ZeroSectors["pentagonx235"] -> {
},
SectorsWithoutGraph["pentagonx235"] -> {
},
SectorRelations["pentagonx235"] -> {
 {"pentagonx235",1} -> {{"pentagon",1}, },
 {"pentagonx235",3} -> {{"pentagon",3}, l->(-l-p1)},
 {"pentagonx235",5} -> {{"pentagonx12345",5}, l->(-p2-l-p1)},
 {"pentagonx235",7} -> {{"pentagonx12345",7}, l->(-p2-l-p1)},
 {"pentagonx235",15} -> {{"pentagonx14x235",15}, l->(-p2+px-l-p1)},
 {"pentagonx235",31} -> {{"pentagonx12x45",31}, l->(l-p1)}
},
ZeroSectors["pentagonx2354"] -> {
},
SectorsWithoutGraph["pentagonx2354"] -> {
},
SectorRelations["pentagonx2354"] -> {
 {"pentagonx2354",1} -> {{"pentagon",1}, },
 {"pentagonx2354",3} -> {{"pentagon",3}, l->(-l-p1)},
 {"pentagonx2354",5} -> {{"pentagonx14235",5}, l->(px-l-p1)},
 {"pentagonx2354",7} -> {{"pentagonx14235",7}, l->(px-l-p1)},
 {"pentagonx2354",11} -> {{"pentagonx235",11}, },
 {"pentagonx2354",15} -> {{"pentagonx12354",15}, l->(-p2+px-l-p1)},
 {"pentagonx2354",31} -> {{"pentagonx1243",31}, l->(px+l-p1)}
},
ZeroSectors["pentagonx24"] -> {
},
SectorsWithoutGraph["pentagonx24"] -> {
},
SectorRelations["pentagonx24"] -> {
 {"pentagonx24",1} -> {{"pentagon",1}, },
 {"pentagonx24",3} -> {{"pentagon",3}, l->(-l-p1)},
 {"pentagonx24",5} -> {{"pentagon",5}, l->(k-l-p1)},
 {"pentagonx24",7} -> {{"pentagon",7}, },
 {"pentagonx24",11} -> {{"pentagonx234",11}, },
 {"pentagonx24",15} -> {{"pentagonx1234",15}, l->(k-p2-l-p1)},
 {"pentagonx24",31} -> {{"pentagonx1234",31}, l->(k-p2-l-p1)}
},
ZeroSectors["pentagonx24x35"] -> {
},
SectorsWithoutGraph["pentagonx24x35"] -> {
},
SectorRelations["pentagonx24x35"] -> {
 {"pentagonx24x35",1} -> {{"pentagon",1}, },
 {"pentagonx24x35",3} -> {{"pentagon",3}, l->(-l-p1)},
 {"pentagonx24x35",5} -> {{"pentagonx13245",5}, l->(-k+p2-px-l)},
 {"pentagonx24x35",7} -> {{"pentagonx13245",7}, l->(-k+p2-px-l)},
 {"pentagonx24x35",11} -> {{"pentagon",11}, l->(-l-p1)},
 {"pentagonx24x35",15} -> {{"pentagonx124x35",15}, l->(-k-px-l)},
 {"pentagonx24x35",31} -> {{"pentagonx123",31}, l->(-k+p2-px+l)}
},
ZeroSectors["pentagonx243"] -> {
},
SectorsWithoutGraph["pentagonx243"] -> {
},
SectorRelations["pentagonx243"] -> {
 {"pentagonx243",1} -> {{"pentagon",1}, },
 {"pentagonx243",3} -> {{"pentagon",3}, l->(-l-p1)},
 {"pentagonx243",5} -> {{"pentagon",5}, l->(k-l-p1)},
 {"pentagonx243",7} -> {{"pentagon",7}, },
 {"pentagonx243",11} -> {{"pentagonx235",11}, l->(-l-p1)},
 {"pentagonx243",15} -> {{"pentagonx1324",15}, l->(p2-px-l)},
 {"pentagonx243",31} -> {{"pentagonx12354",31}, l->(p2-px+l)}
},
ZeroSectors["pentagonx2435"] -> {
},
SectorsWithoutGraph["pentagonx2435"] -> {
},
SectorRelations["pentagonx2435"] -> {
 {"pentagonx2435",1} -> {{"pentagon",1}, },
 {"pentagonx2435",3} -> {{"pentagon",3}, l->(-l-p1)},
 {"pentagonx2435",5} -> {{"pentagonx12345",5}, l->(-p2-l-p1)},
 {"pentagonx2435",7} -> {{"pentagonx12345",7}, l->(-p2-l-p1)},
 {"pentagonx2435",11} -> {{"pentagon",11}, l->(-l-p1)},
 {"pentagonx2435",15} -> {{"pentagonx134x25",15}, l->(-k-px-l)},
 {"pentagonx2435",31} -> {{"pentagonx12x345",31}, l->(l-p1)}
},
ZeroSectors["pentagonx245"] -> {
},
SectorsWithoutGraph["pentagonx245"] -> {
},
SectorRelations["pentagonx245"] -> {
 {"pentagonx245",1} -> {{"pentagon",1}, },
 {"pentagonx245",3} -> {{"pentagon",3}, l->(-l-p1)},
 {"pentagonx245",5} -> {{"pentagonx12345",5}, l->(-p2-l-p1)},
 {"pentagonx245",7} -> {{"pentagonx12345",7}, l->(-p2-l-p1)},
 {"pentagonx245",11} -> {{"pentagonx234",11}, },
 {"pentagonx245",15} -> {{"pentagonx15234",15}, l->(k-p2-l-p1)},
 {"pentagonx245",31} -> {{"pentagonx12x34",31}, l->(l-p1)}
},
ZeroSectors["pentagonx2453"] -> {
},
SectorsWithoutGraph["pentagonx2453"] -> {
},
SectorRelations["pentagonx2453"] -> {
 {"pentagonx2453",1} -> {{"pentagon",1}, },
 {"pentagonx2453",3} -> {{"pentagon",3}, l->(-l-p1)},
 {"pentagonx2453",5} -> {{"pentagonx13245",5}, l->(-k+p2-px-l)},
 {"pentagonx2453",7} -> {{"pentagonx13245",7}, l->(-k+p2-px-l)},
 {"pentagonx2453",11} -> {{"pentagonx235",11}, l->(-l-p1)},
 {"pentagonx2453",15} -> {{"pentagonx15324",15}, l->(p2-px-l)},
 {"pentagonx2453",31} -> {{"pentagonx1243",31}, l->(-px-l)}
},
ZeroSectors["pentagonx25"] -> {
},
SectorsWithoutGraph["pentagonx25"] -> {
},
SectorRelations["pentagonx25"] -> {
 {"pentagonx25",1} -> {{"pentagon",1}, },
 {"pentagonx25",3} -> {{"pentagon",3}, l->(-l-p1)},
 {"pentagonx25",5} -> {{"pentagonx12345",5}, l->(-p2-l-p1)},
 {"pentagonx25",7} -> {{"pentagonx12345",7}, l->(-p2-l-p1)},
 {"pentagonx25",11} -> {{"pentagonx235",11}, },
 {"pentagonx25",15} -> {{"pentagonx14x235",15}, l->(-p2+px-l-p1)},
 {"pentagonx25",31} -> {{"pentagonx12x354",31}, l->(l-p1)}
},
ZeroSectors["pentagonx25x34"] -> {
},
SectorsWithoutGraph["pentagonx25x34"] -> {
},
SectorRelations["pentagonx25x34"] -> {
 {"pentagonx25x34",1} -> {{"pentagon",1}, },
 {"pentagonx25x34",3} -> {{"pentagon",3}, l->(-l-p1)},
 {"pentagonx25x34",5} -> {{"pentagonx12345",5}, l->(-p2-l-p1)},
 {"pentagonx25x34",7} -> {{"pentagonx12345",7}, l->(-p2-l-p1)},
 {"pentagonx25x34",11} -> {{"pentagon",11}, l->(-l-p1)},
 {"pentagonx25x34",15} -> {{"pentagonx134x25",15}, l->(-k-px-l)},
 {"pentagonx25x34",31} -> {{"pentagon",31}, l->(-l-p1)}
},
ZeroSectors["pentagonx253"] -> {
},
SectorsWithoutGraph["pentagonx253"] -> {
},
SectorRelations["pentagonx253"] -> {
 {"pentagonx253",1} -> {{"pentagon",1}, },
 {"pentagonx253",3} -> {{"pentagon",3}, l->(-l-p1)},
 {"pentagonx253",5} -> {{"pentagonx13245",5}, l->(-k+p2-px-l)},
 {"pentagonx253",7} -> {{"pentagonx13245",7}, l->(-k+p2-px-l)},
 {"pentagonx253",11} -> {{"pentagonx234",11}, l->(-l-p1)},
 {"pentagonx253",15} -> {{"pentagonx14x253",15}, l->(-k+p2-l)},
 {"pentagonx253",31} -> {{"pentagonx124",31}, l->(-k+p2+l)}
},
ZeroSectors["pentagonx2534"] -> {
},
SectorsWithoutGraph["pentagonx2534"] -> {
},
SectorRelations["pentagonx2534"] -> {
 {"pentagonx2534",1} -> {{"pentagon",1}, },
 {"pentagonx2534",3} -> {{"pentagon",3}, l->(-l-p1)},
 {"pentagonx2534",5} -> {{"pentagonx13245",5}, l->(-k+p2-px-l)},
 {"pentagonx2534",7} -> {{"pentagonx13245",7}, l->(-k+p2-px-l)},
 {"pentagonx2534",11} -> {{"pentagon",11}, l->(-l-p1)},
 {"pentagonx2534",15} -> {{"pentagonx124x35",15}, l->(-k-px-l)},
 {"pentagonx2534",31} -> {{"pentagonx123x45",31}, l->(-k+p2-px+l)}
},
ZeroSectors["pentagonx254"] -> {
},
SectorsWithoutGraph["pentagonx254"] -> {
},
SectorRelations["pentagonx254"] -> {
 {"pentagonx254",1} -> {{"pentagon",1}, },
 {"pentagonx254",3} -> {{"pentagon",3}, l->(-l-p1)},
 {"pentagonx254",5} -> {{"pentagonx14235",5}, l->(px-l-p1)},
 {"pentagonx254",7} -> {{"pentagonx14235",7}, l->(px-l-p1)},
 {"pentagonx254",11} -> {{"pentagonx235",11}, },
 {"pentagonx254",15} -> {{"pentagonx12354",15}, l->(-p2+px-l-p1)},
 {"pentagonx254",31} -> {{"pentagonx12354",31}, l->(-p2+px-l-p1)}
},
ZeroSectors["pentagonx2543"] -> {
},
SectorsWithoutGraph["pentagonx2543"] -> {
},
SectorRelations["pentagonx2543"] -> {
 {"pentagonx2543",1} -> {{"pentagon",1}, },
 {"pentagonx2543",3} -> {{"pentagon",3}, l->(-l-p1)},
 {"pentagonx2543",5} -> {{"pentagonx14235",5}, l->(px-l-p1)},
 {"pentagonx2543",7} -> {{"pentagonx14235",7}, l->(px-l-p1)},
 {"pentagonx2543",11} -> {{"pentagonx234",11}, l->(-l-p1)},
 {"pentagonx2543",15} -> {{"pentagonx13254",15}, l->(-k+p2-l)},
 {"pentagonx2543",31} -> {{"pentagonx1234",31}, l->(-k+p2+l)}
},
ZeroSectors["pentagonx34"] -> {
},
SectorsWithoutGraph["pentagonx34"] -> {
},
SectorRelations["pentagonx34"] -> {
 {"pentagonx34",1} -> {{"pentagon",1}, },
 {"pentagonx34",3} -> {{"pentagon",3}, l->(-l-p1)},
 {"pentagonx34",5} -> {{"pentagon",5}, l->(k-l-p1)},
 {"pentagonx34",7} -> {{"pentagon",7}, },
 {"pentagonx34",11} -> {{"pentagonx235",11}, l->(-l-p1)},
 {"pentagonx34",15} -> {{"pentagonx1324",15}, l->(p2-px-l)},
 {"pentagonx34",31} -> {{"pentagonx12x354",31}, l->(-l)}
},
ZeroSectors["pentagonx345"] -> {
},
SectorsWithoutGraph["pentagonx345"] -> {
},
SectorRelations["pentagonx345"] -> {
 {"pentagonx345",1} -> {{"pentagon",1}, },
 {"pentagonx345",3} -> {{"pentagon",3}, l->(-l-p1)},
 {"pentagonx345",5} -> {{"pentagonx13245",5}, l->(-k+p2-px-l)},
 {"pentagonx345",7} -> {{"pentagonx13245",7}, l->(-k+p2-px-l)},
 {"pentagonx345",11} -> {{"pentagonx235",11}, l->(-l-p1)},
 {"pentagonx345",15} -> {{"pentagonx15324",15}, l->(p2-px-l)},
 {"pentagonx345",31} -> {{"pentagonx12x45",31}, l->(-l)}
},
ZeroSectors["pentagonx35"] -> {
},
SectorsWithoutGraph["pentagonx35"] -> {
},
SectorRelations["pentagonx35"] -> {
 {"pentagonx35",1} -> {{"pentagon",1}, },
 {"pentagonx35",3} -> {{"pentagon",3}, l->(-l-p1)},
 {"pentagonx35",5} -> {{"pentagonx13245",5}, l->(-k+p2-px-l)},
 {"pentagonx35",7} -> {{"pentagonx13245",7}, l->(-k+p2-px-l)},
 {"pentagonx35",11} -> {{"pentagonx234",11}, l->(-l-p1)},
 {"pentagonx35",15} -> {{"pentagonx14x253",15}, l->(-k+p2-l)},
 {"pentagonx35",31} -> {{"pentagonx12",31}, l->(-l)}
},
ZeroSectors["pentagonx354"] -> {
},
SectorsWithoutGraph["pentagonx354"] -> {
},
SectorRelations["pentagonx354"] -> {
 {"pentagonx354",1} -> {{"pentagon",1}, },
 {"pentagonx354",3} -> {{"pentagon",3}, l->(-l-p1)},
 {"pentagonx354",5} -> {{"pentagonx14235",5}, l->(px-l-p1)},
 {"pentagonx354",7} -> {{"pentagonx14235",7}, l->(px-l-p1)},
 {"pentagonx354",11} -> {{"pentagonx234",11}, l->(-l-p1)},
 {"pentagonx354",15} -> {{"pentagonx13254",15}, l->(-k+p2-l)},
 {"pentagonx354",31} -> {{"pentagonx12x34",31}, l->(-l)}
},
ZeroSectors["pentagonx45"] -> {
},
SectorsWithoutGraph["pentagonx45"] -> {
},
SectorRelations["pentagonx45"] -> {
 {"pentagonx45",1} -> {{"pentagon",1}, },
 {"pentagonx45",3} -> {{"pentagon",3}, l->(-l-p1)},
 {"pentagonx45",5} -> {{"pentagonx14235",5}, l->(px-l-p1)},
 {"pentagonx45",7} -> {{"pentagonx14235",7}, l->(px-l-p1)},
 {"pentagonx45",11} -> {{"pentagon",11}, },
 {"pentagonx45",15} -> {{"pentagonx154",15}, l->(k+px-l-p1)},
 {"pentagonx45",31} -> {{"pentagonx12x345",31}, l->(-l)}
},
ReduzeVersion -> "2.6"
}
