integralfamilies:

  - name: "tree"
    loop_momenta: []

  - name: "box"
    loop_momenta: [l]
    propagators:
      - [ "l",        0   ]
      - [ "l+p1",     0   ]
      - [ "l+p1-px",  0   ]
      - [ "l-p2",     0   ]