# Kinematics for prompt photon
# photon has momentum pg; gluon(quark) has momentum px

---
kinematics:
  incoming_momenta: [p1, p2]
  outgoing_momenta: [pg, px]
  momentum_conservation: [pg, p1 + p2 - px]
  kinematic_invariants:
    - [t,  2]
    - [u,  2]
  scalarproduct_rules:
    - [[p1,p1],  0]
    - [[p2,p2],  0]
    - [[pg,pg],  0]
    - [[px,px],  0]
    - [[p2-px, p2-px], t]
    - [[p1-px, p1-px], u]
